# Generated by Django 5.2.14 on 2026-06-30 12:54

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import trueppm_api.apps.sso.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "workspace",
            "0001_squashed_0014_workspacemembership_availability_effective_from_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OIDCIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("issuer", models.CharField(max_length=512)),
                ("subject", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sso_oidc_identity",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issuer", "subject"), name="uniq_oidc_identity_iss_sub"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OIDCProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("display_name", models.CharField(blank=True, default="", max_length=255)),
                ("issuer_url", models.URLField(blank=True, default="")),
                ("client_id", models.CharField(blank=True, default="", max_length=255)),
                ("client_secret_ciphertext", models.BinaryField(blank=True, default=b"")),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        default=trueppm_api.apps.sso.models._default_scopes,
                        size=None,
                    ),
                ),
                (
                    "allowed_email_domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("auto_create_members", models.BooleanField(default=False)),
                (
                    "default_role",
                    models.PositiveSmallIntegerField(
                        choices=[(100, "Member"), (300, "Admin"), (400, "Owner")], default=100
                    ),
                ),
                ("allow_password_signin", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_providers",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "sso_oidc_provider",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace",), name="uniq_oidc_provider_workspace"
                    )
                ],
            },
        ),
    ]
