# Generated by Django 5.2.16 on 2026-07-18 01:11
#
# ADR-0517: adopt allauth.socialaccount. Create the SsoProviderPolicy side row,
# migrate every OIDCProvider → (SocialApp + SsoProviderPolicy) and every
# OIDCIdentity → SocialAccount, then drop the bespoke sso_oidc_* tables. SSO is
# unshipped, so this is a NO-OP on a fresh install (no OIDCProvider rows exist);
# it exists for dev-DB parity and to keep makemigrations --check honest.

import uuid
from typing import Any

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings as django_settings
from django.db import migrations, models

# The two allauth provider modules we enable; the migrated singleton is generic OIDC.
_ALLAUTH_OPENID_CONNECT = "openid_connect"
_MIGRATED_SLUG = "generic"


def _copy_oidc_config_to_allauth(apps: Any, schema_editor: Any) -> None:
    """Port each OIDCProvider → SocialApp + SsoProviderPolicy, each OIDCIdentity → SocialAccount.

    Uses ``apps.get_model`` (never a direct import) so it runs against the historical
    schema. The client secret is already Fernet-encrypted under the same
    ``INTEGRATION_ENCRYPTION_KEY``, so the ciphertext bytes are copied verbatim into
    the side row — ``SocialApp.secret`` stays empty (control 2, ADR-0517 §3.1).

    Assumes the OSS single-workspace topology: every OIDCProvider collapses into one
    SocialApp under the constant "generic" slug. Multiple OIDCProviders across
    multiple workspaces would collide on that slug — but that cannot occur in OSS,
    which is single-workspace (Workspace is a singleton).
    """
    OIDCProvider = apps.get_model("sso", "OIDCProvider")
    OIDCIdentity = apps.get_model("sso", "OIDCIdentity")
    SsoProviderPolicy = apps.get_model("sso", "SsoProviderPolicy")
    SocialApp = apps.get_model("socialaccount", "SocialApp")
    SocialAccount = apps.get_model("socialaccount", "SocialAccount")
    Site = apps.get_model("sites", "Site")

    site_id = int(getattr(django_settings, "SITE_ID", 1))
    site = Site.objects.filter(pk=site_id).first()

    for provider in OIDCProvider.objects.all():
        app, _created = SocialApp.objects.get_or_create(
            provider=_ALLAUTH_OPENID_CONNECT,
            provider_id=_MIGRATED_SLUG,
            defaults={
                "name": provider.display_name or "OIDC",
                "client_id": provider.client_id,
                "secret": "",
                "settings": {"server_url": provider.issuer_url},
            },
        )
        if site is not None:
            app.sites.add(site)

        SsoProviderPolicy.objects.get_or_create(
            social_app=app,
            defaults={
                "workspace_id": provider.workspace_id,
                "slug": _MIGRATED_SLUG,
                "enabled": provider.enabled,
                "allowed_email_domains": list(provider.allowed_email_domains or []),
                "auto_create_members": provider.auto_create_members,
                "default_role": provider.default_role,
                "allow_password_signin": provider.allow_password_signin,
                "github_org": "",
                "secret_ciphertext": bytes(provider.client_secret_ciphertext or b""),
            },
        )

    for identity in OIDCIdentity.objects.all():
        SocialAccount.objects.get_or_create(
            provider=_MIGRATED_SLUG,
            uid=identity.subject,
            defaults={
                "user_id": identity.user_id,
                "extra_data": {"iss": identity.issuer},
            },
        )


def _noop_reverse(apps: Any, schema_editor: Any) -> None:
    """Reverse is a no-op: the bespoke tables are gone; we do not reconstruct them."""


class Migration(migrations.Migration):
    dependencies = [
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
        ("sites", "0002_alter_domain_unique"),
        ("sso", "0001_initial"),
        ("workspace", "0016_historicalworkspace_calendar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SsoProviderPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("slug", models.CharField(max_length=64)),
                (
                    "allowed_email_domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("auto_create_members", models.BooleanField(default=False)),
                (
                    "default_role",
                    models.PositiveSmallIntegerField(
                        choices=[(100, "Member"), (300, "Admin"), (400, "Owner")], default=100
                    ),
                ),
                ("allow_password_signin", models.BooleanField(default=True)),
                ("github_org", models.CharField(blank=True, default="", max_length=255)),
                ("secret_ciphertext", models.BinaryField(blank=True, default=b"")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "social_app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trueppm_policy",
                        to="socialaccount.socialapp",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_provider_policies",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "sso_provider_policy",
            },
        ),
        migrations.AddConstraint(
            model_name="ssoproviderpolicy",
            constraint=models.UniqueConstraint(
                fields=("workspace", "slug"), name="uniq_sso_policy_workspace_slug"
            ),
        ),
        # Data copy MUST run before the fields/models it reads are dropped below.
        migrations.RunPython(_copy_oidc_config_to_allauth, _noop_reverse),
        migrations.RemoveField(
            model_name="oidcprovider",
            name="workspace",
        ),
        migrations.DeleteModel(
            name="OIDCIdentity",
        ),
        migrations.DeleteModel(
            name="OIDCProvider",
        ),
    ]
