# Generated by Django 6.0.3 on 2026-05-24 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_engine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workflowhistoryevent",
            name="workflow_history_lookup_idx",
        ),
    ]
