# Generated by Django 5.2.14 on 2026-07-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workflow_engine",
            "0001_squashed_0002_remove_workflowhistoryevent_workflow_history_lookup_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workflowoutboxrow",
            index=models.Index(
                fields=["status", "dispatched_at"], name="workflow_outbox_recovery_idx"
            ),
        ),
    ]
