# Generated by Django 5.2.14 on 2026-06-23 21:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("access", "0001_initial"),
        ("access", "0002_alter_projectmembership_id"),
        ("access", "0003_projectmembership_soft_delete"),
        ("access", "0004_alter_projectmembership_role"),
        ("access", "0005_program_entity_and_membership"),
        ("access", "0006_role_ordinal_spacing"),
        ("access", "0007_projectmembership_joined_at_and_more"),
        ("access", "0008_projectmembership_source_group"),
        ("access", "0009_projectmembership_pm_proj_serverver_idx"),
        ("access", "0010_programmembership_joined_at_and_more"),
        ("access", "0011_alter_programmembership_unique_together_and_more"),
        ("access", "0012_programmembership_role_title"),
    ]

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("projects", "0036_program_entity_and_membership"),
        ("projects", "0053_dependency_dep_pred_serverver_idx_and_more"),
        ("projects", "0078_alter_risktask_unique_together_and_more"),
        ("workspace", "0001_initial"),
        ("workspace", "0003_workspaceexportjob"),
        ("workspace", "0006_alter_groupmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "Viewer"),
                            (100, "Team Member"),
                            (200, "Resource Manager"),
                            (300, "Project Manager"),
                            (400, "Project Admin"),
                        ]
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "joined_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("role_changed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "source_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_memberships",
                        to="workspace.group",
                    ),
                ),
            ],
            options={
                "db_table": "access_project_membership",
                "unique_together": set(),
                "indexes": [
                    models.Index(fields=["project", "server_version"], name="pm_proj_serverver_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "user"), name="uniq_project_membership_project_user"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgramMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "Viewer"),
                            (100, "Team Member"),
                            (200, "Resource Manager"),
                            (300, "Project Manager"),
                            (400, "Project Admin"),
                        ]
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="projects.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("role_changed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("role_title", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "db_table": "access_program_membership",
                "unique_together": set(),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "user"), name="uniq_program_membership_program_user"
                    )
                ],
            },
        ),
    ]
