# Generated by Django 5.2.14 on 2026-05-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0007_projectmembership_joined_at_and_more"),
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="source_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_memberships",
                to="workspace.group",
            ),
        ),
    ]
