# Generated by Django 5.2.14 on 2026-05-29 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0008_projectmembership_source_group"),
        ("projects", "0053_dependency_dep_pred_serverver_idx_and_more"),
        ("workspace", "0003_workspaceexportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(fields=["project", "server_version"], name="pm_proj_serverver_idx"),
        ),
    ]
