# Generated by Django 5.2.14 on 2026-06-15 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0010_programmembership_joined_at_and_more"),
        ("projects", "0078_alter_risktask_unique_together_and_more"),
        ("workspace", "0006_alter_groupmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="programmembership",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="projectmembership",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="programmembership",
            constraint=models.UniqueConstraint(
                fields=("program", "user"), name="uniq_program_membership_program_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="uniq_project_membership_project_user"
            ),
        ),
    ]
