# Generated by Django 5.2.14 on 2026-06-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0011_alter_programmembership_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmembership",
            name="role_title",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
