# Generated by Django 5.2.17 on 2026-10-05 19:51

import importlib
import uuid
from typing import Any

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def _original(app: str, module: str, name: str) -> Any:
    """Return a callable from a retained original migration module.

    The original migrations stay on disk (migration rule 6), so the callable is
    resolved from there rather than copied into this file.
    """
    # Every call site passes a constant app/module/name from this file, never user input.
    # nosemgrep: python.lang.security.audit.non-literal-import.non-literal-import
    return getattr(importlib.import_module(f"trueppm_api.apps.{app}.migrations.{module}"), name)


class Migration(migrations.Migration):
    replaces = [
        ("access", "0013_userdefinedmentiongroup"),
        ("access", "0014_programmembership_progm_serverver_idx"),
        ("access", "0015_programuserdefinedmentiongroup"),
        ("access", "0016_externalstakeholder"),
        ("access", "0017_viewer_ordinal_one"),
        ("access", "0018_programmembership_sync_seq_and_more"),
        ("access", "0019_programmembership_reinstated_at_and_more"),
    ]

    dependencies = [
        ("access", "0001_squashed_0012_programmembership_role_title"),
        ("projects", "0107_task_activity_event"),
        ("projects", "0109_projectexportjob"),
        ("projects", "0111_projectcalendarlayer"),
        ("projects", "0127_historicalprogram_mcp_enabled_and_more"),
        ("projects", "0128_acceptancecriterion_sync_seq_apitoken_sync_seq_and_more"),
        ("workspace", "0020_viewer_ordinal_one"),
        ("workspace", "0021_group_sync_seq_groupmembership_sync_seq_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDefinedMentionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(blank=True, default="", max_length=140)),
                ("email_default_on", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mention_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="mention_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "muted_by",
                    models.ManyToManyField(
                        blank=True, related_name="muted_mention_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mention_groups",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "access_user_defined_mention_group",
                "indexes": [
                    models.Index(
                        fields=["project", "server_version"], name="udmg_proj_serverver_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("project"),
                        django.db.models.functions.text.Lower("name"),
                        condition=models.Q(("is_deleted", False)),
                        name="uniq_mention_group_project_name_ci",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="programmembership",
            index=models.Index(fields=["program", "server_version"], name="progm_serverver_idx"),
        ),
        migrations.CreateModel(
            name="ExternalStakeholder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_stakeholders",
                        to="projects.program",
                    ),
                ),
            ],
            options={
                "db_table": "access_external_stakeholder",
                "indexes": [
                    models.Index(fields=["program", "is_deleted"], name="extstake_prog_deleted_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("program"),
                        django.db.models.functions.text.Lower("email"),
                        condition=models.Q(("is_deleted", False)),
                        name="uniq_external_stakeholder_program_email_ci",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="programmembership",
            name="role",
            field=models.IntegerField(
                choices=[
                    (1, "Viewer"),
                    (100, "Team Member"),
                    (200, "Resource Manager"),
                    (300, "Project Manager"),
                    (400, "Project Admin"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="role",
            field=models.IntegerField(
                choices=[
                    (1, "Viewer"),
                    (100, "Team Member"),
                    (200, "Resource Manager"),
                    (300, "Project Manager"),
                    (400, "Project Admin"),
                ]
            ),
        ),
        migrations.RunPython(
            code=_original("access", "0017_viewer_ordinal_one", "viewer_zero_to_one"),
            reverse_code=_original("access", "0017_viewer_ordinal_one", "viewer_one_to_zero"),
        ),
        migrations.AddField(
            model_name="programmembership",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name="ProgramUserDefinedMentionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(blank=True, default="", max_length=140)),
                ("email_default_on", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_program_mention_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="program_mention_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "muted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="muted_program_mention_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mention_groups",
                        to="projects.program",
                    ),
                ),
                ("sync_seq", models.BigIntegerField(default=0, editable=False)),
            ],
            options={
                "db_table": "access_program_user_defined_mention_group",
                "indexes": [
                    models.Index(
                        fields=["program", "server_version"], name="pudmg_prog_serverver_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("program"),
                        django.db.models.functions.text.Lower("name"),
                        condition=models.Q(("is_deleted", False)),
                        name="uniq_program_mention_group_program_name_ci",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="userdefinedmentiongroup",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="programmembership",
            index=models.Index(fields=["program", "sync_seq"], name="progm_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="programuserdefinedmentiongroup",
            index=models.Index(fields=["program", "sync_seq"], name="pudmg_prog_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(fields=["project", "sync_seq"], name="pm_proj_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="userdefinedmentiongroup",
            index=models.Index(fields=["project", "sync_seq"], name="udmg_proj_syncseq_idx"),
        ),
        migrations.AddField(
            model_name="programmembership",
            name="reinstated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="reinstated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
