# Generated by Django 5.2.15 on 2026-07-06 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0013_userdefinedmentiongroup"),
        ("projects", "0109_projectexportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="programmembership",
            index=models.Index(fields=["program", "server_version"], name="progm_serverver_idx"),
        ),
    ]
