# Generated by Django 5.2.15 on 2026-07-06 12:02

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0014_programmembership_progm_serverver_idx"),
        ("projects", "0109_projectexportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramUserDefinedMentionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(blank=True, default="", max_length=140)),
                ("email_default_on", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_program_mention_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="program_mention_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "muted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="muted_program_mention_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mention_groups",
                        to="projects.program",
                    ),
                ),
            ],
            options={
                "db_table": "access_program_user_defined_mention_group",
                "indexes": [
                    models.Index(
                        fields=["program", "server_version"], name="pudmg_prog_serverver_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("program"),
                        django.db.models.functions.text.Lower("name"),
                        condition=models.Q(("is_deleted", False)),
                        name="uniq_program_mention_group_program_name_ci",
                    )
                ],
            },
        ),
    ]
