# Generated by Django 5.2.15 on 2026-07-06 19:48

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0015_programuserdefinedmentiongroup"),
        ("projects", "0111_projectcalendarlayer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalStakeholder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_stakeholders",
                        to="projects.program",
                    ),
                ),
            ],
            options={
                "db_table": "access_external_stakeholder",
                "indexes": [
                    models.Index(fields=["program", "is_deleted"], name="extstake_prog_deleted_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("program"),
                        django.db.models.functions.text.Lower("email"),
                        condition=models.Q(("is_deleted", False)),
                        name="uniq_external_stakeholder_program_email_ci",
                    )
                ],
            },
        ),
    ]
