# Generated by Django 5.2.16 on 2026-07-28 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0017_viewer_ordinal_one"),
        ("projects", "0128_acceptancecriterion_sync_seq_apitoken_sync_seq_and_more"),
        ("workspace", "0021_group_sync_seq_groupmembership_sync_seq_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="programmembership",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="programuserdefinedmentiongroup",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="userdefinedmentiongroup",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="programmembership",
            index=models.Index(fields=["program", "sync_seq"], name="progm_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="programuserdefinedmentiongroup",
            index=models.Index(fields=["program", "sync_seq"], name="pudmg_prog_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(fields=["project", "sync_seq"], name="pm_proj_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="userdefinedmentiongroup",
            index=models.Index(fields=["project", "sync_seq"], name="udmg_proj_syncseq_idx"),
        ),
    ]
