# Generated by Django 5.2.17 on 2026-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0018_programmembership_sync_seq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmembership",
            name="reinstated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="reinstated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
