# Generated by Django 5.2.17 on 2026-10-05 20:20

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("timetracking", "0001_initial"),
        ("timetracking", "0002_timesheetsubmission"),
        ("timetracking", "0003_timeentry_deleted_at_timeentry_deleted_by"),
        ("timetracking", "0004_timeentry_sync_seq_and_more"),
    ]

    dependencies = [
        ("projects", "0097_backlogitem_backlogitem_tags_gin_and_more"),
        ("projects", "0128_acceptancecriterion_sync_seq_apitoken_sync_seq_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveTimer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.task",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_timer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "timetracking_active_timer",
            },
        ),
        migrations.CreateModel(
            name="TimesheetSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("week_start", models.DateField()),
                ("submitted_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "timetracking_timesheet_submission",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "week_start"), name="uniq_timesheet_submission_user_week"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "minutes",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ]
                    ),
                ),
                ("entry_date", models.DateField(default=django.utils.timezone.localdate)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("timer", "Timer")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="projects.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_time_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("sync_seq", models.BigIntegerField(default=0, editable=False)),
            ],
            options={
                "db_table": "timetracking_time_entry",
                "indexes": [
                    models.Index(
                        fields=["user", "entry_date"], name="timetrackin_user_id_8b4245_idx"
                    ),
                    models.Index(
                        fields=["user", "task", "entry_date"], name="timetrackin_user_id_8c4ce4_idx"
                    ),
                    models.Index(
                        fields=["task", "server_version"], name="timetrackin_task_id_efb2b5_idx"
                    ),
                    models.Index(
                        fields=["task", "sync_seq"], name="timetrackin_task_id_a6ce52_idx"
                    ),
                ],
            },
        ),
    ]
