# Generated by Django 5.2.16 on 2026-07-28 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0128_acceptancecriterion_sync_seq_apitoken_sync_seq_and_more"),
        ("timetracking", "0003_timeentry_deleted_at_timeentry_deleted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["task", "sync_seq"], name="timetrackin_task_id_a6ce52_idx"),
        ),
    ]
