# Generated by Django 6.0.3 on 2026-05-20 02:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0038_taskcomment_commentreaction_commentacknowledgement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("mentioned_group_key", models.CharField(blank=True, default="", max_length=32)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("project_visible", "Project visible"),
                            ("team_only", "Team only"),
                            ("private", "Private"),
                        ],
                        default="project_visible",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentioner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentions_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="projects.project",
                    ),
                ),
                (
                    "task_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="projects.taskcomment",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_mention",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("email_pending", models.BooleanField(db_index=True, default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_failed_at", models.DateTimeField(blank=True, null=True)),
                ("email_attempts", models.PositiveIntegerField(default=0)),
                (
                    "mention",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="notifications.mention",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="projects.project",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("channel", models.CharField(max_length=32)),
                ("enabled", models.BooleanField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_preference",
            },
        ),
        migrations.AddIndex(
            model_name="mention",
            index=models.Index(
                fields=["mentioned_user", "-created_at"], name="ix_mention_user_recent"
            ),
        ),
        migrations.AddIndex(
            model_name="mention",
            index=models.Index(fields=["project", "-created_at"], name="ix_mention_project_recent"),
        ),
        migrations.AddConstraint(
            model_name="mention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mentioned_user__isnull", False),
                    models.Q(("mentioned_group_key", ""), _negated=True),
                    _connector="OR",
                ),
                name="mention_must_have_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="mention",
            constraint=models.CheckConstraint(
                condition=models.Q(("task_comment__isnull", False)), name="mention_must_have_source"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"], name="ix_notif_unread"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("email_pending", True)),
                fields=["email_pending", "-created_at"],
                name="ix_notif_email_pending",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "event_type", "channel"), name="uq_notifpref_user_event_channel"
            ),
        ),
    ]
