# Generated by Django 6.0.3 on 2026-05-22 13:25

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import trueppm_api.apps.notifications.models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        ("projects", "0043_merge_20260522_1118"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectNotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "matrix",
                    models.JSONField(default=trueppm_api.apps.notifications.models._default_matrix),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=True)),
                ("quiet_hours_from", models.TimeField(default=datetime.time(20, 0))),
                ("quiet_hours_until", models.TimeField(default=datetime.time(7, 0))),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences_by_user",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_project_preference",
                "indexes": [
                    models.Index(fields=["project", "user"], name="ix_projnotifpref_proj_user")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "user"), name="uq_projnotifpref_project_user"
                    )
                ],
            },
        ),
    ]
