# Generated by Django 6.0.3 on 2026-05-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_clean_unknown_matrix_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="notification",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
