# Generated by Django 6.0.3 on 2026-06-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("notifications", "0005_notification_body_notification_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="projects.task",
            ),
        ),
    ]
