# Generated by Django 5.2.17 on 2026-10-05 20:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("notifications", "0007_workspaceemailsettings"),
        ("notifications", "0008_notification_snoozed_until"),
        ("notifications", "0009_usernotificationsettings"),
        ("notifications", "0010_projectnotificationpreference_schema_version"),
        ("notifications", "0011_usernotificationsettings_digest_hour_and_more"),
    ]

    dependencies = [
        ("notifications", "0001_squashed_0006_notification_task"),
        ("projects", "0126_projectcustomfield_show_on_card_taskcustomfieldvalue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceEmailSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
                ),
                (
                    "transport_mode",
                    models.CharField(
                        choices=[
                            ("cloud", "TruePPM cloud (Django settings)"),
                            ("smtp", "Custom SMTP"),
                            ("sendgrid", "SendGrid"),
                            ("ses", "Amazon SES"),
                        ],
                        default="cloud",
                        max_length=16,
                    ),
                ),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                ("port", models.PositiveIntegerField(default=587)),
                (
                    "security",
                    models.CharField(
                        choices=[("none", "None"), ("tls", "STARTTLS"), ("ssl", "SSL/TLS")],
                        default="tls",
                        max_length=8,
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("password_ciphertext", models.BinaryField(blank=True, default=b"")),
                ("from_name", models.CharField(blank=True, default="", max_length=255)),
                ("from_email", models.EmailField(blank=True, default="", max_length=254)),
                ("reply_to", models.EmailField(blank=True, default="", max_length=254)),
                ("dkim_selector", models.CharField(blank=True, default="", max_length=63)),
                ("max_recipients", models.PositiveIntegerField(default=50)),
                ("throttle_per_min", models.PositiveIntegerField(default=0)),
                ("bounce_webhook_url", models.URLField(blank=True, default="", max_length=512)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace email settings",
                "verbose_name_plural": "workspace email settings",
                "db_table": "notifications_workspace_email_settings",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="snoozed_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="projectnotificationpreference",
            name="schema_version",
            field=models.IntegerField(
                default=1,
                help_text="Matrix shape version; upgraded on read via the migration registry (ADR-0086).",
            ),
        ),
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dnd_enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "digest_hour",
                    models.IntegerField(
                        default=17,
                        help_text="Local hour (0-23) at which scheduled digests are sent.",
                    ),
                ),
                (
                    "digest_timezone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="IANA timezone for the digest slot; blank uses the server timezone.",
                        max_length=64,
                    ),
                ),
                (
                    "digest_weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=6,
                        help_text="Day of week for scheduled digests, 0=Monday..6=Sunday (Python weekday()).",
                    ),
                ),
            ],
            options={
                "verbose_name": "user notification settings",
                "verbose_name_plural": "user notification settings",
                "db_table": "notifications_user_settings",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="NotificationDigestRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("period_start", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("notification_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digest_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_digest_run",
                "indexes": [models.Index(fields=["created_at"], name="digestrun_created_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "event_type", "period_start"),
                        name="uniq_digest_run_user_event_period",
                    )
                ],
            },
        ),
    ]
