# Generated by Django 5.2.15 on 2026-07-05 02:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_squashed_0006_notification_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceEmailSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
                ),
                (
                    "transport_mode",
                    models.CharField(
                        choices=[
                            ("cloud", "TruePPM cloud (Django settings)"),
                            ("smtp", "Custom SMTP"),
                            ("sendgrid", "SendGrid"),
                            ("ses", "Amazon SES"),
                        ],
                        default="cloud",
                        max_length=16,
                    ),
                ),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                ("port", models.PositiveIntegerField(default=587)),
                (
                    "security",
                    models.CharField(
                        choices=[("none", "None"), ("tls", "STARTTLS"), ("ssl", "SSL/TLS")],
                        default="tls",
                        max_length=8,
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("password_ciphertext", models.BinaryField(blank=True, default=b"")),
                ("from_name", models.CharField(blank=True, default="", max_length=255)),
                ("from_email", models.EmailField(blank=True, default="", max_length=254)),
                ("reply_to", models.EmailField(blank=True, default="", max_length=254)),
                ("dkim_selector", models.CharField(blank=True, default="", max_length=63)),
                ("max_recipients", models.PositiveIntegerField(default=50)),
                ("throttle_per_min", models.PositiveIntegerField(default=0)),
                ("bounce_webhook_url", models.URLField(blank=True, default="", max_length=512)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace email settings",
                "verbose_name_plural": "workspace email settings",
                "db_table": "notifications_workspace_email_settings",
            },
        ),
    ]
