# Generated by Django 5.2.15 on 2026-07-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0007_workspaceemailsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="snoozed_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
