# Generated by Django 5.2.16 on 2026-07-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_usernotificationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectnotificationpreference",
            name="schema_version",
            field=models.IntegerField(
                default=1,
                help_text="Matrix shape version; upgraded on read via the migration registry (ADR-0086).",
            ),
        ),
    ]
