# Generated by Django 5.2.16 on 2026-07-27 01:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0010_projectnotificationpreference_schema_version"),
        ("projects", "0126_projectcustomfield_show_on_card_taskcustomfieldvalue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationsettings",
            name="digest_hour",
            field=models.IntegerField(
                default=17, help_text="Local hour (0-23) at which scheduled digests are sent."
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsettings",
            name="digest_timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone for the digest slot; blank uses the server timezone.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsettings",
            name="digest_weekday",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=6,
                help_text="Day of week for scheduled digests, 0=Monday..6=Sunday (Python weekday()).",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="NotificationDigestRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("period_start", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("notification_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digest_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_digest_run",
                "indexes": [models.Index(fields=["created_at"], name="digestrun_created_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "event_type", "period_start"),
                        name="uniq_digest_run_user_event_period",
                    )
                ],
            },
        ),
    ]
