# Generated by Django 5.2.14 on 2026-06-23 21:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("profiles", "0001_initial"),
        ("profiles", "0002_userprofile_hidden_views"),
        ("profiles", "0003_projectvisit"),
        ("profiles", "0004_userprofile_role_context"),
    ]

    initial = True

    dependencies = [
        ("projects", "0086_board_card_search_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "visited_at",
                    models.DateTimeField(help_text="When the user last opened this project."),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "project visit",
                "verbose_name_plural": "project visits",
                "indexes": [
                    models.Index(
                        fields=["user", "-visited_at"], name="projectvisit_user_recent_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "project"), name="uq_project_visit_user_project"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "default_landing",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic (based on your role)"),
                            ("my_work", "My Work"),
                            ("project_overview", "Project Overview"),
                            ("portfolio", "Portfolio"),
                        ],
                        default="auto",
                        help_text="Which screen the app opens on. 'auto' uses the role-based policy.",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hidden_views",
                    models.JSONField(blank=True, default=list, help_text="Hidden nav view keys."),
                ),
                (
                    "role_context",
                    models.CharField(
                        choices=[
                            ("pm", "PM"),
                            ("scrum_master", "Scrum Master"),
                            ("unified", "Unified Today"),
                        ],
                        default="unified",
                        help_text="Active role-context view: PM, Scrum Master, or Unified Today (#412).",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
    ]
