# Generated by Django 5.2.14 on 2026-06-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hidden_views",
            field=models.JSONField(blank=True, default=list, help_text="Hidden nav view keys."),
        ),
    ]
