# Generated by Django 5.2.14 on 2026-06-20 15:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_userprofile_hidden_views"),
        ("projects", "0086_board_card_search_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "visited_at",
                    models.DateTimeField(help_text="When the user last opened this project."),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "project visit",
                "verbose_name_plural": "project visits",
                "indexes": [
                    models.Index(
                        fields=["user", "-visited_at"], name="projectvisit_user_recent_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "project"), name="uq_project_visit_user_project"
                    )
                ],
            },
        ),
    ]
