# Generated by Django 5.2.14 on 2026-06-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_projectvisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role_context",
            field=models.CharField(
                choices=[
                    ("pm", "PM"),
                    ("scrum_master", "Scrum Master"),
                    ("unified", "Unified Today"),
                ],
                default="unified",
                help_text="Active role-context view: PM, Scrum Master, or Unified Today (#412).",
                max_length=12,
            ),
        ),
    ]
