# Generated by Django 5.2.17 on 2026-10-05 20:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("profiles", "0005_userprofile_schedule_in_deliver"),
        ("profiles", "0006_userprofile_date_format_userprofile_timezone"),
        ("profiles", "0007_userpin"),
        ("profiles", "0008_remove_userprofile_schedule_in_deliver"),
        ("profiles", "0009_auth_user_email_upper_idx"),
    ]

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("profiles", "0001_squashed_0004_userprofile_role_context"),
        ("projects", "0126_projectcustomfield_show_on_card_taskcustomfieldvalue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("auto", "Automatic (based on your locale)"),
                    ("iso", "2026-07-14"),
                    ("us", "Jul 14, 2026"),
                    ("eu", "14 Jul 2026"),
                ],
                default="auto",
                help_text="Date-format style for all displayed dates. 'auto' follows browser locale.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                default="auto",
                help_text="IANA timezone for displaying instant timestamps, or 'auto' to use the browser's detected zone. Display-only; API datetimes stay UTC.",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="UserPin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "pinned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the user pinned this item. Never exposed on a shared payload.",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="projects.program",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user pin",
                "verbose_name_plural": "user pins",
                "indexes": [
                    models.Index(fields=["user", "-pinned_at"], name="userpin_user_recent_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("program__isnull", True), ("project__isnull", False)),
                            models.Q(("program__isnull", False), ("project__isnull", True)),
                            _connector="OR",
                        ),
                        name="ck_userpin_project_xor_program",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("project__isnull", False)),
                        fields=("user", "project"),
                        name="uq_userpin_user_project",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("program__isnull", False)),
                        fields=("user", "program"),
                        name="uq_userpin_user_program",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS auth_user_email_upper_idx ON auth_user (UPPER(email::text));",
            reverse_sql="DROP INDEX IF EXISTS auth_user_email_upper_idx;",
        ),
    ]
