# Generated by Django 5.2.15 on 2026-07-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_squashed_0004_userprofile_role_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="schedule_in_deliver",
            field=models.BooleanField(
                default=False,
                help_text="Also surface Schedule under Deliver (opt-in, display-only).",
            ),
        ),
    ]
