# Generated by Django 5.2.16 on 2026-07-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_userprofile_schedule_in_deliver"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("auto", "Automatic (based on your locale)"),
                    ("iso", "2026-07-14"),
                    ("us", "Jul 14, 2026"),
                    ("eu", "14 Jul 2026"),
                ],
                default="auto",
                help_text="Date-format style for all displayed dates. 'auto' follows browser locale.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                default="auto",
                help_text="IANA timezone for displaying instant timestamps, or 'auto' to use the browser's detected zone. Display-only; API datetimes stay UTC.",
                max_length=64,
            ),
        ),
    ]
