# Generated by Django 5.2.16 on 2026-07-26 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_userprofile_date_format_userprofile_timezone"),
        ("projects", "0126_projectcustomfield_show_on_card_taskcustomfieldvalue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "pinned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the user pinned this item. Never exposed on a shared payload.",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="projects.program",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user pin",
                "verbose_name_plural": "user pins",
                "indexes": [
                    models.Index(fields=["user", "-pinned_at"], name="userpin_user_recent_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("program__isnull", True), ("project__isnull", False)),
                            models.Q(("program__isnull", False), ("project__isnull", True)),
                            _connector="OR",
                        ),
                        name="ck_userpin_project_xor_program",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("project__isnull", False)),
                        fields=("user", "project"),
                        name="uq_userpin_user_project",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("program__isnull", False)),
                        fields=("user", "program"),
                        name="uq_userpin_user_program",
                    ),
                ],
            },
        ),
    ]
