# Generated by Django 5.2.16 on 2026-08-30

from django.db import migrations


class Migration(migrations.Migration):
    """Drop ``UserProfile.schedule_in_deliver`` (ADR-0942 §3, #3137).

    The Schedule-in-Deliver placement opt-in (ADR-0203, #1645) let a user echo the
    Schedule view into the DELIVER band while it stayed in PLAN. ADR-0942 adopts "one
    home per item, per render" — a nav item listed twice is two objects to the person
    using it — so nothing reads the flag any more.

    Removed rather than deprecated to a no-op. A boolean that still round-trips and is
    read by nothing is documented, echoes back, and lies to every API and MCP client
    about what the product does; the honest option at pre-1.0 alpha, for a display-only
    field no rollup, report, export, schedule computation or webhook reads, is deletion
    and a 400 on a stale write. That 400 does not come for free — DRF's default is to
    drop an unrecognised key and answer 200 — so it is implemented explicitly by
    ``UserProfileSerializer.RETIRED_FIELDS``.

    **Rolling-upgrade window.** The Helm API deployment has no ``strategy:`` block, so
    Kubernetes rolls with the default RollingUpdate and old pods keep serving while the
    new pod's init container runs ``migrate_locked``. The moment this migration applies,
    an old pod's ``get_profile_prefs`` — which names its columns explicitly in
    ``.only(...)``, ``schedule_in_deliver`` among them — selects a column that no longer
    exists and 500s on ``/auth/me/``, the web shell's bootstrap call. The window is
    bounded by rollout duration and does not exist on single-replica installs, which is
    every self-hosted deployment we know of at pre-1.0 alpha. The rolling-safe shape
    would have been two releases (drop the code references in N, the column in N+1);
    this is deliberately one, and this note is the record of that trade rather than an
    oversight.

    **What happens to a user who had it on.** Their column is dropped and their
    preference is gone; the rail renders the calm default (Schedule in PLAN only), which
    is what every non-opted-in user already saw. Nothing else about their profile
    changes — this migration touches one column and no other field, row, or default. The
    need the opt-in served is now met by adjacency and one hop: PLAN sits directly above
    DELIVER. That is weaker than the opt-in, and ADR-0942 says so; the recorded response
    to a real complaint is band order or an explicit shortcut affordance, never a
    restored duplicate.

    No data to preserve and no constraint added, so the constraint-safety gate does not
    apply. Irreversible in practice: reversing it recreates the column at its ``False``
    default, not at whatever each user had chosen.
    """

    dependencies = [
        ("profiles", "0007_userpin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="schedule_in_deliver",
        ),
    ]
