# Generated by Django 5.2.14 on 2026-06-15 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0002_workshopparticipant_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workshopparticipant",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="workshopparticipant",
            constraint=models.UniqueConstraint(
                fields=("session", "user"), name="uniq_workshop_participant_session_user"
            ),
        ),
    ]
