# Generated by Django 5.2.16 on 2026-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_squashed_0002_default_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
