# Generated by Django 5.2.14 on 2026-06-23 21:38

import uuid

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import trueppm_api.apps.workspace.models


class Migration(migrations.Migration):
    replaces = [
        ("workspace", "0001_initial"),
        ("workspace", "0002_remove_workspace_fiscal_year_start_and_more"),
        ("workspace", "0003_workspaceexportjob"),
        ("workspace", "0004_alter_workspaceinvite_status"),
        ("workspace", "0005_workspace_iteration_label_and_more"),
        ("workspace", "0006_alter_groupmembership_unique_together_and_more"),
        ("workspace", "0007_workspace_public_sharing_override_policy"),
        ("workspace", "0008_workspace_mc_history_attribution_audience_and_more"),
        ("workspace", "0009_workspace_methodology_and_more"),
        ("workspace", "0010_workspace_logo"),
        (
            "workspace",
            "0011_historicalworkspace_task_duration_change_percent_override_policy_and_more",
        ),
        ("workspace", "0012_historicalworkspace_allowed_attachment_types_and_more"),
        ("workspace", "0013_auditevent"),
        ("workspace", "0014_workspacemembership_availability_effective_from_and_more"),
    ]

    initial = True

    dependencies = [
        ("projects", "0047_apitokenauditentry_program_and_more"),
        ("projects", "0078_alter_risktask_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
                ),
                ("name", models.CharField(default="TruePPM Workspace", max_length=255)),
                ("subdomain", models.CharField(blank=True, default="", max_length=63)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "work_week",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BooleanField(),
                        default=trueppm_api.apps.workspace.models._default_work_week,
                        size=7,
                    ),
                ),
                ("default_project_view", models.CharField(default="board", max_length=32)),
                ("allow_guests", models.BooleanField(default=True)),
                ("public_sharing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "fiscal_year_start_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                ("iteration_label", models.CharField(default="Sprint", max_length=32)),
                (
                    "iteration_label_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                (
                    "public_sharing_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                (
                    "mc_history_attribution_audience",
                    models.CharField(
                        choices=[
                            ("admin_owner", "Admins and Owners"),
                            ("scheduler_plus", "Schedulers and above"),
                            ("none", "No one"),
                        ],
                        default="admin_owner",
                        max_length=16,
                    ),
                ),
                ("mc_history_enabled", models.BooleanField(default=True)),
                (
                    "mc_history_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                ("mc_history_retention_cap", models.PositiveIntegerField(default=100)),
                (
                    "methodology",
                    models.CharField(
                        choices=[
                            ("WATERFALL", "Waterfall"),
                            ("AGILE", "Agile"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="HYBRID",
                        max_length=16,
                    ),
                ),
                (
                    "methodology_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        default="",
                        upload_to=trueppm_api.apps.workspace.models._workspace_logo_upload_to,
                    ),
                ),
                ("logo_mime", models.CharField(blank=True, default="", max_length=64)),
                (
                    "task_duration_change_percent_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                (
                    "task_duration_change_percent_policy",
                    models.CharField(
                        choices=[
                            ("keep", "Keep percent-complete"),
                            ("prorate", "Prorate percent-complete"),
                            ("confirm", "Confirm percent-complete (client prompt)"),
                        ],
                        default="keep",
                        max_length=16,
                    ),
                ),
                (
                    "allowed_attachment_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=trueppm_api.apps.workspace.models._default_allowed_attachment_types,
                        size=None,
                    ),
                ),
                ("attachments_enabled", models.BooleanField(default=True)),
                (
                    "attachments_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "workspace_workspace",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="groups_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_group",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=512)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workspace_export_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="wsexport_status_created_idx"
                    ),
                    models.Index(fields=["expires_at"], name="wsexport_expires_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.IntegerField(
                        choices=[(100, "Member"), (300, "Admin"), (400, "Owner")], default=100
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("email_token", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("email_pending", models.BooleanField(db_index=True, default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_failed_at", models.DateTimeField(blank=True, null=True)),
                ("email_attempts", models.PositiveIntegerField(default=0)),
                (
                    "accepted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_invites_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_invite",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("email_pending", True)),
                        fields=["email_pending", "-created_at"],
                        name="ix_invite_email_pending",
                    ),
                    models.Index(fields=["status", "-created_at"], name="ix_invite_status"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "joined_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workspace.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workspace_group_membership",
                "unique_together": set(),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "user"), name="uniq_group_membership_group_user"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GroupProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "Viewer"),
                            (100, "Team Member"),
                            (200, "Resource Manager"),
                            (300, "Project Manager"),
                            (400, "Project Admin"),
                        ],
                        default=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_projects_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="workspace.group",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_links",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_group_project",
                "unique_together": set(),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "project"), name="uniq_group_project_group_project"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalWorkspace",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(db_index=True, default=1, editable=False),
                ),
                ("name", models.CharField(default="TruePPM Workspace", max_length=255)),
                ("subdomain", models.CharField(blank=True, default="", max_length=63)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "fiscal_year_start_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "work_week",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BooleanField(),
                        default=trueppm_api.apps.workspace.models._default_work_week,
                        size=7,
                    ),
                ),
                ("default_project_view", models.CharField(default="board", max_length=32)),
                ("allow_guests", models.BooleanField(default=True)),
                ("public_sharing", models.BooleanField(default=False)),
                ("iteration_label", models.CharField(default="Sprint", max_length=32)),
                (
                    "iteration_label_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                (
                    "public_sharing_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                ("mc_history_enabled", models.BooleanField(default=True)),
                ("mc_history_retention_cap", models.PositiveIntegerField(default=100)),
                (
                    "mc_history_attribution_audience",
                    models.CharField(
                        choices=[
                            ("admin_owner", "Admins and Owners"),
                            ("scheduler_plus", "Schedulers and above"),
                            ("none", "No one"),
                        ],
                        default="admin_owner",
                        max_length=16,
                    ),
                ),
                (
                    "mc_history_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                (
                    "methodology",
                    models.CharField(
                        choices=[
                            ("WATERFALL", "Waterfall"),
                            ("AGILE", "Agile"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="HYBRID",
                        max_length=16,
                    ),
                ),
                (
                    "methodology_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("logo", models.TextField(blank=True, default="", max_length=100)),
                ("logo_mime", models.CharField(blank=True, default="", max_length=64)),
                (
                    "task_duration_change_percent_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                (
                    "task_duration_change_percent_policy",
                    models.CharField(
                        choices=[
                            ("keep", "Keep percent-complete"),
                            ("prorate", "Prorate percent-complete"),
                            ("confirm", "Confirm percent-complete (client prompt)"),
                        ],
                        default="keep",
                        max_length=16,
                    ),
                ),
                (
                    "allowed_attachment_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=trueppm_api.apps.workspace.models._default_allowed_attachment_types,
                        size=None,
                    ),
                ),
                ("attachments_enabled", models.BooleanField(default=True)),
                (
                    "attachments_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical workspace",
                "verbose_name_plural": "historical workspaces",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("member_added", "Member added"),
                            ("member_removed", "Member removed"),
                            ("member_role_changed", "Member role changed"),
                            ("ownership_transferred", "Ownership transferred"),
                            ("project_created", "Project created"),
                            ("project_deleted", "Project deleted"),
                            ("workspace_settings_changed", "Workspace settings changed"),
                            ("workspace_export_triggered", "Workspace export triggered"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("target_type", models.CharField(blank=True, default="", max_length=40)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("target_label", models.CharField(blank=True, default="", max_length=512)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workspace_auditevent",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="auditevent_type_created_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "role",
                    models.IntegerField(
                        choices=[(100, "Member"), (300, "Admin"), (400, "Owner")], default=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("guest", "Guest"),
                            ("deactivated", "Deactivated"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("role_changed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workspace.workspace",
                    ),
                ),
                ("availability_effective_from", models.DateField(blank=True, null=True)),
                ("availability_effective_to", models.DateField(blank=True, null=True)),
                ("availability_notes", models.TextField(blank=True, default="")),
                (
                    "availability_percent",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "workspace_membership",
                "unique_together": set(),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "user"),
                        name="uniq_workspace_membership_workspace_user",
                    )
                ],
            },
        ),
    ]
