# Generated by Django 5.2.14 on 2026-05-25 17:53

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import trueppm_api.apps.workspace.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0047_apitokenauditentry_program_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
                ),
                ("name", models.CharField(default="TruePPM Workspace", max_length=255)),
                ("subdomain", models.CharField(blank=True, default="", max_length=63)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("fiscal_year_start", models.CharField(default="January 1", max_length=32)),
                (
                    "work_week",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BooleanField(),
                        default=trueppm_api.apps.workspace.models._default_work_week,
                        size=7,
                    ),
                ),
                ("default_project_view", models.CharField(default="board", max_length=32)),
                ("allow_guests", models.BooleanField(default=True)),
                ("public_sharing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workspace_workspace",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="groups_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_group",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "joined_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workspace.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workspace_group_membership",
                "unique_together": {("group", "user")},
            },
        ),
        migrations.CreateModel(
            name="GroupProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "Viewer"),
                            (100, "Team Member"),
                            (200, "Resource Manager"),
                            (300, "Project Manager"),
                            (400, "Project Admin"),
                        ],
                        default=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_projects_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="workspace.group",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_links",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_group_project",
                "unique_together": {("group", "project")},
            },
        ),
        migrations.CreateModel(
            name="WorkspaceInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.IntegerField(
                        choices=[(100, "Member"), (300, "Admin"), (400, "Owner")], default=100
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("email_token", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("email_pending", models.BooleanField(db_index=True, default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_failed_at", models.DateTimeField(blank=True, null=True)),
                ("email_attempts", models.PositiveIntegerField(default=0)),
                (
                    "accepted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_invites_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_invite",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("email_pending", True)),
                        fields=["email_pending", "-created_at"],
                        name="ix_invite_email_pending",
                    ),
                    models.Index(fields=["status", "-created_at"], name="ix_invite_status"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "role",
                    models.IntegerField(
                        choices=[(100, "Member"), (300, "Admin"), (400, "Owner")], default=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("guest", "Guest"),
                            ("deactivated", "Deactivated"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("role_changed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_membership",
                "unique_together": {("workspace", "user")},
            },
        ),
    ]
