# Generated by Django 5.2.14 on 2026-05-26 17:29
"""#756: replace the free-text ``Workspace.fiscal_year_start`` CharField with a
structured ``fiscal_year_start_month`` / ``fiscal_year_start_day`` pair.

Operations are deliberately ordered Add → parse (RunPython) → Remove so the
free-text column is still readable while we translate it into month/day. The
parser is intentionally lenient — "January 1", "April", "4/1", "Apr 6" all
resolve — and falls back to (1, 1) with a logged warning for anything it cannot
read, so the migration never aborts on a hand-edited value.
"""

import logging

import django.core.validators
from django.db import migrations, models

logger = logging.getLogger(__name__)

_MONTH_LOOKUP = {
    "january": 1,
    "jan": 1,
    "february": 2,
    "feb": 2,
    "march": 3,
    "mar": 3,
    "april": 4,
    "apr": 4,
    "may": 5,
    "june": 6,
    "jun": 6,
    "july": 7,
    "jul": 7,
    "august": 8,
    "aug": 8,
    "september": 9,
    "sep": 9,
    "sept": 9,
    "october": 10,
    "oct": 10,
    "november": 11,
    "nov": 11,
    "december": 12,
    "dec": 12,
}


def _max_day(month: int) -> int:
    """Year-agnostic day ceiling (Feb=28; 30-day months reject 31)."""
    if month == 2:
        return 28
    if month in (4, 6, 9, 11):
        return 30
    return 31


def _parse_fiscal_text(raw: str) -> tuple[int, int]:
    """Best-effort parse of a free-text fiscal anchor into ``(month, day)``.

    Returns ``(1, 1)`` for anything unrecognized. Day is clamped to the month's
    valid range so the structured value is always internally consistent.
    """
    if not raw:
        return (1, 1)
    text = raw.strip().lower()

    month: int | None = None
    day = 1

    # Numeric "M/D" or "M-D" (also bare "M").
    for sep in ("/", "-"):
        if sep in text:
            parts = [p.strip() for p in text.split(sep) if p.strip()]
            if parts and parts[0].isdigit():
                m = int(parts[0])
                if 1 <= m <= 12:
                    month = m
                    if len(parts) > 1 and parts[1].isdigit():
                        day = int(parts[1])
            break

    # Word form: "<monthname> [day]".
    if month is None:
        tokens = text.replace(",", " ").split()
        if tokens:
            month = _MONTH_LOOKUP.get(tokens[0])
            for tok in tokens[1:]:
                if tok.isdigit():
                    day = int(tok)
                    break

    if month is None:
        logger.warning(
            "workspace.fiscal_year_start migration: could not parse %r; defaulting to January 1.",
            raw,
        )
        return (1, 1)

    if day < 1 or day > _max_day(month):
        day = 1
    return (month, day)


def _forward(apps, schema_editor):
    Workspace = apps.get_model("workspace", "Workspace")
    for ws in Workspace.objects.all():
        month, day = _parse_fiscal_text(ws.fiscal_year_start or "")
        ws.fiscal_year_start_month = month
        ws.fiscal_year_start_day = day
        ws.save(update_fields=["fiscal_year_start_month", "fiscal_year_start_day"])


def _reverse(apps, schema_editor):
    """Reconstruct the free-text label from the structured pair."""
    names = (
        "",
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    )
    Workspace = apps.get_model("workspace", "Workspace")
    for ws in Workspace.objects.all():
        ws.fiscal_year_start = f"{names[ws.fiscal_year_start_month]} {ws.fiscal_year_start_day}"
        ws.save(update_fields=["fiscal_year_start"])


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="fiscal_year_start_month",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="fiscal_year_start_day",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.RunPython(_forward, _reverse),
        migrations.RemoveField(
            model_name="workspace",
            name="fiscal_year_start",
        ),
    ]
