# Generated by Django 5.2.14 on 2026-05-26 17:29
"""#756: replace the free-text ``Workspace.fiscal_year_start`` CharField with a
structured ``fiscal_year_start_month`` / ``fiscal_year_start_day`` pair.

Operations are deliberately ordered Add → parse (RunPython) → Remove so the
free-text column is still readable while we translate it into month/day. The
parser is intentionally lenient — "January 1", "April", "4/1", "Apr 6" all
resolve — and falls back to (1, 1) with a logged warning for anything it cannot
read, so the migration never aborts on a hand-edited value.
"""

from typing import Any

import django.core.validators
from django.db import migrations, models

from trueppm_api.apps.workspace.backfill import _parse_fiscal_text


def _forward(apps: Any, schema_editor: Any) -> None:
    Workspace = apps.get_model("workspace", "Workspace")
    for ws in Workspace.objects.all():
        month, day = _parse_fiscal_text(ws.fiscal_year_start or "")
        ws.fiscal_year_start_month = month
        ws.fiscal_year_start_day = day
        ws.save(update_fields=["fiscal_year_start_month", "fiscal_year_start_day"])


def _reverse(apps: Any, schema_editor: Any) -> None:
    """Reconstruct the free-text label from the structured pair."""
    names = (
        "",
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    )
    Workspace = apps.get_model("workspace", "Workspace")
    for ws in Workspace.objects.all():
        ws.fiscal_year_start = f"{names[ws.fiscal_year_start_month]} {ws.fiscal_year_start_day}"
        ws.save(update_fields=["fiscal_year_start"])


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="fiscal_year_start_month",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="fiscal_year_start_day",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.RunPython(_forward, _reverse, elidable=True),
        migrations.RemoveField(
            model_name="workspace",
            name="fiscal_year_start",
        ),
    ]
