# Generated by Django 5.2.14 on 2026-05-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0003_workspaceexportjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("revoked", "Revoked"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
