# Generated by Django 5.2.14 on 2026-06-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0004_alter_workspaceinvite_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="iteration_label",
            field=models.CharField(default="Sprint", max_length=32),
        ),
        migrations.AddField(
            model_name="workspace",
            name="iteration_label_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
    ]
