# Generated by Django 5.2.14 on 2026-06-15 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0078_alter_risktask_unique_together_and_more"),
        ("workspace", "0005_workspace_iteration_label_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupmembership",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="groupproject",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="workspacemembership",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                fields=("group", "user"), name="uniq_group_membership_group_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupproject",
            constraint=models.UniqueConstraint(
                fields=("group", "project"), name="uniq_group_project_group_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacemembership",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user"), name="uniq_workspace_membership_workspace_user"
            ),
        ),
    ]
