# Generated by Django 5.2.14 on 2026-06-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0006_alter_groupmembership_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="public_sharing_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
    ]
