# Generated by Django 5.2.14 on 2026-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0007_workspace_public_sharing_override_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="mc_history_attribution_audience",
            field=models.CharField(
                choices=[
                    ("admin_owner", "Admins and Owners"),
                    ("scheduler_plus", "Schedulers and above"),
                    ("none", "No one"),
                ],
                default="admin_owner",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="mc_history_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="mc_history_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="mc_history_retention_cap",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
