# Generated by Django 5.2.14 on 2026-06-19 13:24

import uuid

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import trueppm_api.apps.workspace.models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0008_workspace_mc_history_attribution_audience_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="methodology",
            field=models.CharField(
                choices=[("WATERFALL", "Waterfall"), ("AGILE", "Agile"), ("HYBRID", "Hybrid")],
                default="HYBRID",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="methodology_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalWorkspace",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(db_index=True, default=1, editable=False),
                ),
                ("name", models.CharField(default="TruePPM Workspace", max_length=255)),
                ("subdomain", models.CharField(blank=True, default="", max_length=63)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "fiscal_year_start_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "work_week",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BooleanField(),
                        default=trueppm_api.apps.workspace.models._default_work_week,
                        size=7,
                    ),
                ),
                ("default_project_view", models.CharField(default="board", max_length=32)),
                ("allow_guests", models.BooleanField(default=True)),
                ("public_sharing", models.BooleanField(default=False)),
                ("iteration_label", models.CharField(default="Sprint", max_length=32)),
                (
                    "iteration_label_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                (
                    "public_sharing_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                ("mc_history_enabled", models.BooleanField(default=True)),
                ("mc_history_retention_cap", models.PositiveIntegerField(default=100)),
                (
                    "mc_history_attribution_audience",
                    models.CharField(
                        choices=[
                            ("admin_owner", "Admins and Owners"),
                            ("scheduler_plus", "Schedulers and above"),
                            ("none", "No one"),
                        ],
                        default="admin_owner",
                        max_length=16,
                    ),
                ),
                (
                    "mc_history_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                (
                    "methodology",
                    models.CharField(
                        choices=[
                            ("WATERFALL", "Waterfall"),
                            ("AGILE", "Agile"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="HYBRID",
                        max_length=16,
                    ),
                ),
                (
                    "methodology_override_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit"),
                            ("suggest", "Suggest"),
                            ("enforce", "Enforce"),
                        ],
                        default="suggest",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical workspace",
                "verbose_name_plural": "historical workspaces",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
