# Generated by Django 5.2.14 on 2026-06-20 12:36

from django.db import migrations, models

import trueppm_api.apps.workspace.models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0009_workspace_methodology_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkspace",
            name="logo",
            field=models.TextField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="logo_mime",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="workspace",
            name="logo",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=trueppm_api.apps.workspace.models._workspace_logo_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="logo_mime",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
