# Generated by Django 5.2.14 on 2026-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0010_workspace_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkspace",
            name="task_duration_change_percent_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="task_duration_change_percent_policy",
            field=models.CharField(
                choices=[
                    ("keep", "Keep percent-complete"),
                    ("prorate", "Prorate percent-complete"),
                    ("confirm", "Confirm percent-complete (client prompt)"),
                ],
                default="keep",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="task_duration_change_percent_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="task_duration_change_percent_policy",
            field=models.CharField(
                choices=[
                    ("keep", "Keep percent-complete"),
                    ("prorate", "Prorate percent-complete"),
                    ("confirm", "Confirm percent-complete (client prompt)"),
                ],
                default="keep",
                max_length=16,
            ),
        ),
    ]
