# Generated by Django 5.2.14 on 2026-06-20 15:44

import django.contrib.postgres.fields
from django.db import migrations, models

import trueppm_api.apps.workspace.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workspace",
            "0011_historicalworkspace_task_duration_change_percent_override_policy_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkspace",
            name="allowed_attachment_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=trueppm_api.apps.workspace.models._default_allowed_attachment_types,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="attachments_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="attachments_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="allowed_attachment_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=trueppm_api.apps.workspace.models._default_allowed_attachment_types,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="attachments_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="attachments_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
    ]
