# Generated by Django 5.2.14 on 2026-06-21 01:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0012_historicalworkspace_allowed_attachment_types_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("member_added", "Member added"),
                            ("member_removed", "Member removed"),
                            ("member_role_changed", "Member role changed"),
                            ("ownership_transferred", "Ownership transferred"),
                            ("project_created", "Project created"),
                            ("project_deleted", "Project deleted"),
                            ("workspace_settings_changed", "Workspace settings changed"),
                            ("workspace_export_triggered", "Workspace export triggered"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("target_type", models.CharField(blank=True, default="", max_length=40)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("target_label", models.CharField(blank=True, default="", max_length=512)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workspace_auditevent",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="auditevent_type_created_idx"
                    )
                ],
            },
        ),
    ]
