# Generated by Django 5.2.14 on 2026-06-21 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0013_auditevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemembership",
            name="availability_effective_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="availability_effective_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="availability_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="availability_percent",
            field=models.PositiveSmallIntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
