# Generated by Django 5.2.17 on 2026-10-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("workspace", "0015_trash_restore_1113"),
        ("workspace", "0016_historicalworkspace_calendar_and_more"),
        ("workspace", "0017_historicalworkspace_estimation_scale_and_more"),
        ("workspace", "0018_historicalworkspace_feedback_enabled_and_more"),
        ("workspace", "0019_historicalworkspace_mcp_enabled_and_more"),
        ("workspace", "0020_viewer_ordinal_one"),
        ("workspace", "0021_group_sync_seq_groupmembership_sync_seq_and_more"),
        ("workspace", "0022_historicalworkspace_sprint_picker_ready_only_default_and_more"),
        ("workspace", "0023_alter_auditevent_event_type"),
        ("workspace", "0024_alter_auditevent_event_type"),
        ("workspace", "0025_alter_auditevent_event_type"),
        ("workspace", "0026_alter_auditevent_event_type"),
        ("workspace", "0027_alter_auditevent_event_type"),
    ]

    dependencies = [
        ("projects", "0119_historicalprogram_calendar_program_calendar"),
        (
            "workspace",
            "0001_squashed_0014_workspacemembership_availability_effective_from_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkspace",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.calendar",
            ),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="calendar_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="projects.calendar",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="calendar_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="estimation_scale",
            field=models.CharField(
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                default="fibonacci",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="estimation_scale",
            field=models.CharField(
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                default="fibonacci",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="feedback_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="feedback_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workspace",
            name="feedback_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="feedback_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="mcp_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="mcp_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="groupproject",
            name="role",
            field=models.IntegerField(
                choices=[
                    (1, "Viewer"),
                    (100, "Team Member"),
                    (200, "Resource Manager"),
                    (300, "Project Manager"),
                    (400, "Project Admin"),
                ],
                default=100,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("member_added", "Member added"),
                    ("member_removed", "Member removed"),
                    ("member_role_changed", "Member role changed"),
                    ("member_status_changed", "Member status changed"),
                    ("ownership_transferred", "Ownership transferred"),
                    ("project_created", "Project created"),
                    ("project_deleted", "Project deleted"),
                    ("project_restored", "Project restored"),
                    ("template_published", "Template published"),
                    ("workspace_settings_changed", "Workspace settings changed"),
                    ("workspace_export_triggered", "Workspace export triggered"),
                    ("invite_sent", "Invite sent"),
                    ("invite_accepted", "Invite accepted"),
                    ("invite_revoked", "Invite revoked"),
                    ("calendar_changed", "Calendar changed"),
                    ("sso_provider_created", "SSO provider created"),
                    ("sso_provider_updated", "SSO provider updated"),
                    ("sso_provider_deleted", "SSO provider deleted"),
                    ("sso_secret_rotated", "SSO client secret rotated"),
                    ("sso_account_linked", "SSO account linked"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
