# Generated by Django 5.2.14 on 2026-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workspace",
            "0001_squashed_0014_workspacemembership_availability_effective_from_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("member_added", "Member added"),
                    ("member_removed", "Member removed"),
                    ("member_role_changed", "Member role changed"),
                    ("ownership_transferred", "Ownership transferred"),
                    ("project_created", "Project created"),
                    ("project_deleted", "Project deleted"),
                    ("project_restored", "Project restored"),
                    ("workspace_settings_changed", "Workspace settings changed"),
                    ("workspace_export_triggered", "Workspace export triggered"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
