# Generated by Django 5.2.16 on 2026-07-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0119_historicalprogram_calendar_program_calendar"),
        ("workspace", "0015_trash_restore_1113"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkspace",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.calendar",
            ),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="calendar_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="projects.calendar",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="calendar_override_policy",
            field=models.CharField(
                choices=[("inherit", "Inherit"), ("suggest", "Suggest"), ("enforce", "Enforce")],
                default="suggest",
                max_length=16,
            ),
        ),
    ]
