# Generated by Django 5.2.16 on 2026-07-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0016_historicalworkspace_calendar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkspace",
            name="estimation_scale",
            field=models.CharField(
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                default="fibonacci",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="estimation_scale",
            field=models.CharField(
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                default="fibonacci",
                max_length=16,
            ),
        ),
    ]
