# Generated by Django 5.2.16 on 2026-07-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0017_historicalworkspace_estimation_scale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkspace",
            name="feedback_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalworkspace",
            name="feedback_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workspace",
            name="feedback_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="feedback_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
