# Generated by Django 5.2.16 on 2026-07-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0018_historicalworkspace_feedback_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkspace",
            name="mcp_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="mcp_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
