# Generated by Django 5.2.16 on 2026-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0020_viewer_ordinal_one"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
