# Generated by Django 5.2.16 on 2026-07-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0021_group_sync_seq_groupmembership_sync_seq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkspace",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(default=True),
        ),
    ]
