# Generated by Django 5.2.16 on 2026-08-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0022_historicalworkspace_sprint_picker_ready_only_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("member_added", "Member added"),
                    ("member_removed", "Member removed"),
                    ("member_role_changed", "Member role changed"),
                    ("member_status_changed", "Member status changed"),
                    ("ownership_transferred", "Ownership transferred"),
                    ("project_created", "Project created"),
                    ("project_deleted", "Project deleted"),
                    ("project_restored", "Project restored"),
                    ("workspace_settings_changed", "Workspace settings changed"),
                    ("workspace_export_triggered", "Workspace export triggered"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
