# Generated by Django 5.2.16 on 2026-08-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0025_alter_auditevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("member_added", "Member added"),
                    ("member_removed", "Member removed"),
                    ("member_role_changed", "Member role changed"),
                    ("member_status_changed", "Member status changed"),
                    ("ownership_transferred", "Ownership transferred"),
                    ("project_created", "Project created"),
                    ("project_deleted", "Project deleted"),
                    ("project_restored", "Project restored"),
                    ("template_published", "Template published"),
                    ("workspace_settings_changed", "Workspace settings changed"),
                    ("workspace_export_triggered", "Workspace export triggered"),
                    ("invite_sent", "Invite sent"),
                    ("invite_accepted", "Invite accepted"),
                    ("invite_revoked", "Invite revoked"),
                    ("calendar_changed", "Calendar changed"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
