# Generated by Django 6.0.3 on 2026-05-24 12:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0046_merge_20260523_2248"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_batch_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("response_status", models.PositiveSmallIntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_batches",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["created_at"], name="syncbatch_created_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "client_batch_id"),
                        name="syncbatch_project_client_batch_uniq",
                    )
                ],
            },
        ),
    ]
