# Generated by Django 5.2.14 on 2026-06-23 21:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("sync", "0001_initial"),
        ("sync", "0002_remove_syncbatch_syncbatch_project_client_batch_uniq_and_more"),
    ]

    initial = True

    dependencies = [
        ("projects", "0046_merge_20260523_2248"),
        ("projects", "0054_sprintscopechange_goal_impact_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_batch_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("response_status", models.PositiveSmallIntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_batches",
                        to="projects.project",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["created_at"], name="syncbatch_created_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "actor_user", "client_batch_id"),
                        name="syncbatch_project_actor_client_batch_uniq",
                    )
                ],
            },
        ),
    ]
