# Generated by Django 5.2.14 on 2026-05-30 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0054_sprintscopechange_goal_impact_and_more"),
        ("sync", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="syncbatch",
            name="syncbatch_project_client_batch_uniq",
        ),
        migrations.AddField(
            model_name="syncbatch",
            name="actor_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # safe-constraint: widens the (project, client_batch_id) uniqueness removed
        # above to (project, actor_user, client_batch_id). A superset of an already
        # unique key is unique, so no existing row can violate the wider constraint.
        migrations.AddConstraint(
            model_name="syncbatch",
            constraint=models.UniqueConstraint(
                fields=("project", "actor_user", "client_batch_id"),
                name="syncbatch_project_actor_client_batch_uniq",
            ),
        ),
    ]
