# Generated by Django 5.2.17 on 2026-10-05 20:38

import django.db.models.deletion
from django.db import migrations, models

import trueppm_api.apps.sync.backfill


class Migration(migrations.Migration):
    replaces = [
        ("sync", "0003_boardevent"),
        ("sync", "0004_seed_sync_seq"),
        ("sync", "0005_program_sync_sequence"),
    ]

    dependencies = [
        ("access", "0018_programmembership_sync_seq_and_more"),
        ("integrations", "0011_tasklink_sync_seq_tasklink_tasklink_syncseq_idx"),
        ("projects", "0109_projectexportjob"),
        ("projects", "0128_acceptancecriterion_sync_seq_apitoken_sync_seq_and_more"),
        (
            "sync",
            "0001_squashed_0002_remove_syncbatch_syncbatch_project_client_batch_uniq_and_more",
        ),
        ("timetracking", "0004_timeentry_sync_seq_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_events",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["project", "id"], name="boardevent_project_seq_idx"),
                    models.Index(fields=["created_at"], name="boardevent_created_idx"),
                ],
            },
        ),
        migrations.RunPython(
            code=trueppm_api.apps.sync.backfill.seed_sync_seq,
            reverse_code=trueppm_api.apps.sync.backfill.unseed_sync_seq,
        ),
        migrations.CreateModel(
            name="ProgramSyncSequence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.BigIntegerField(default=0, editable=False)),
            ],
            options={
                "verbose_name": "program sync sequence",
                "verbose_name_plural": "program sync sequence",
            },
        ),
        migrations.RunPython(
            code=trueppm_api.apps.sync.backfill.seed_program_sync_seq,
            reverse_code=trueppm_api.apps.sync.backfill.unseed_program_sync_seq,
        ),
    ]
