# Generated by Django 5.2.15 on 2026-07-05 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0109_projectexportjob"),
        (
            "sync",
            "0001_squashed_0002_remove_syncbatch_syncbatch_project_client_batch_uniq_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_events",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["project", "id"], name="boardevent_project_seq_idx"),
                    models.Index(fields=["created_at"], name="boardevent_created_idx"),
                ],
            },
        ),
    ]
