# Generated by Django 5.2.14 on 2026-06-23 21:38

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("integrations", "0001_initial"),
        ("integrations", "0002_tasklink"),
        ("integrations", "0003_tasklink_tasklink_serverver_idx"),
        ("integrations", "0004_tasklink_custom_title_tasklink_labels"),
        ("integrations", "0005_boardautomation"),
        ("integrations", "0006_tasklink_description_tasklink_preview_type_and_more"),
    ]

    initial = True

    dependencies = [
        ("projects", "0051_alter_calendar_working_days_alter_dependency_lag_and_more"),
        ("projects", "0053_dependency_dep_pred_serverver_idx_and_more"),
        ("projects", "0088_historicalprogram_allowed_attachment_types_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("secret_ciphertext", models.BinaryField()),
                ("base_url", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration credential",
                "verbose_name_plural": "Integration credentials",
                "ordering": ("provider",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "provider"),
                        name="integrations_credential_unique_per_user_provider",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BoardAutomation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("secret_ciphertext", models.BinaryField(blank=True, default=b"")),
                ("secret_set_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_automation",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "board automation",
                "verbose_name_plural": "board automations",
            },
        ),
        migrations.CreateModel(
            name="TaskLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("url", models.URLField(max_length=2048)),
                ("provider", models.CharField(max_length=32)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("draft", "draft"),
                            ("merged", "merged"),
                            ("closed", "closed"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="projects.task",
                    ),
                ),
                ("custom_title", models.CharField(blank=True, default="", max_length=512)),
                (
                    "labels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("description", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "preview_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("document", "document"),
                            ("spreadsheet", "spreadsheet"),
                            ("presentation", "presentation"),
                            ("image", "image"),
                            ("pdf", "pdf"),
                            ("folder", "folder"),
                            ("file", "file"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True, default="", max_length=2048)),
            ],
            options={
                "verbose_name": "Task link",
                "verbose_name_plural": "Task links",
                "ordering": ("display_order", "id"),
                "indexes": [
                    models.Index(
                        fields=["task", "display_order"], name="integrations_link_task_order"
                    ),
                    models.Index(fields=["task", "server_version"], name="tasklink_serverver_idx"),
                ],
            },
        ),
    ]
