# Generated by Django 5.2.14 on 2026-05-26 18:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
        ("projects", "0051_alter_calendar_working_days_alter_dependency_lag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("url", models.URLField(max_length=2048)),
                ("provider", models.CharField(max_length=32)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("draft", "draft"),
                            ("merged", "merged"),
                            ("closed", "closed"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task link",
                "verbose_name_plural": "Task links",
                "ordering": ("display_order", "id"),
                "indexes": [
                    models.Index(
                        fields=["task", "display_order"], name="integrations_link_task_order"
                    )
                ],
            },
        ),
    ]
