# Generated by Django 5.2.14 on 2026-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_tasklink"),
        ("projects", "0053_dependency_dep_pred_serverver_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tasklink",
            index=models.Index(fields=["task", "server_version"], name="tasklink_serverver_idx"),
        ),
    ]
