# Generated by Django 5.2.14 on 2026-06-06 22:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_tasklink_tasklink_serverver_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklink",
            name="custom_title",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="tasklink",
            name="labels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=40), blank=True, default=list, size=None
            ),
        ),
    ]
