# Generated by Django 5.2.14 on 2026-06-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0005_boardautomation"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklink",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="tasklink",
            name="preview_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("document", "document"),
                    ("spreadsheet", "spreadsheet"),
                    ("presentation", "presentation"),
                    ("image", "image"),
                    ("pdf", "pdf"),
                    ("folder", "folder"),
                    ("file", "file"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tasklink",
            name="thumbnail_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
    ]
