# Generated by Django 5.2.15 on 2026-07-05 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_squashed_0006_tasklink_description_tasklink_preview_type_and_more"),
        ("projects", "0107_task_activity_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklink",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddIndex(
            model_name="tasklink",
            index=models.Index(fields=["-created_at", "-id"], name="tasklink_created_idx"),
        ),
    ]
