# Generated by Django 5.2.17 on 2026-10-05 19:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("integrations", "0007_tasklink_created_at"),
        ("integrations", "0008_integrationcredential_config_externalworkitem"),
        ("integrations", "0009_externalsyncrequest_and_more"),
        ("integrations", "0010_externalworkitem_due_date"),
        ("integrations", "0011_tasklink_sync_seq_tasklink_tasklink_syncseq_idx"),
        ("integrations", "0012_boardautomation_last_delivery_at_and_more"),
        ("integrations", "0013_externalsyncrequest_attempt_count_and_more"),
        ("integrations", "0014_tasklink_created_by"),
    ]

    dependencies = [
        ("integrations", "0001_squashed_0006_tasklink_description_tasklink_preview_type_and_more"),
        ("projects", "0107_task_activity_event"),
        ("projects", "0128_acceptancecriterion_sync_seq_apitoken_sync_seq_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklink",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddIndex(
            model_name="tasklink",
            index=models.Index(fields=["-created_at", "-id"], name="tasklink_created_idx"),
        ),
        migrations.AddField(
            model_name="integrationcredential",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ExternalSyncRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("done", "Done"),
                            ("dead", "Dead"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("manual", "Manual"), ("on_open", "On Open"), ("poll", "Poll")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=255)),
                ("last_error", models.CharField(blank=True, default="", max_length=512)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_sync_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "External sync request",
                "verbose_name_plural": "External sync requests",
                "ordering": ("requested_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"], name="external_sync_status_age_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("user", "source"),
                        name="external_sync_one_pending_per_user_source",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "dispatched")),
                        fields=("user", "source"),
                        name="external_sync_one_dispatched_per_user_source",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalWorkItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("external_id", models.CharField(max_length=255)),
                ("external_url", models.URLField(blank=True, default="", max_length=2000)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("external_status", models.CharField(blank=True, default="", max_length=64)),
                ("display_bucket", models.CharField(default="todo", max_length=12)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("is_stale", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_work_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "External work item",
                "verbose_name_plural": "External work items",
                "ordering": ("display_bucket", "external_id"),
                "indexes": [
                    models.Index(
                        fields=["user", "is_stale", "display_bucket"],
                        name="external_item_user_bucket_idx",
                    ),
                    models.Index(
                        fields=["is_stale", "last_synced_at"], name="external_item_stale_age_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source", "external_id"),
                        name="integrations_external_item_unique",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="tasklink",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="tasklink",
            index=models.Index(fields=["task", "sync_seq"], name="tasklink_syncseq_idx"),
        ),
        migrations.AddField(
            model_name="boardautomation",
            name="last_delivery_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boardautomation",
            name="last_delivery_outcome",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="boardautomation",
            name="last_delivery_provider",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="boardautomation",
            name="last_refusal_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boardautomation",
            name="last_refusal_outcome",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="boardautomation",
            name="last_refusal_provider",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="externalsyncrequest",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="externalsyncrequest",
            name="next_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Earliest time the drain may re-dispatch this row (rate-limit backoff).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tasklink",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
