# Generated by Django 5.2.15 on 2026-07-05 18:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0007_tasklink_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationcredential",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ExternalWorkItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("external_id", models.CharField(max_length=255)),
                ("external_url", models.URLField(blank=True, default="", max_length=2000)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("external_status", models.CharField(blank=True, default="", max_length=64)),
                ("display_bucket", models.CharField(default="todo", max_length=12)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("is_stale", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_work_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "External work item",
                "verbose_name_plural": "External work items",
                "ordering": ("display_bucket", "external_id"),
                "indexes": [
                    models.Index(
                        fields=["user", "is_stale", "display_bucket"],
                        name="external_item_user_bucket_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source", "external_id"),
                        name="integrations_external_item_unique",
                    )
                ],
            },
        ),
    ]
