# Generated by Django 5.2.15 on 2026-07-06 01:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0008_integrationcredential_config_externalworkitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSyncRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("done", "Done"),
                            ("dead", "Dead"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("manual", "Manual"), ("on_open", "On Open"), ("poll", "Poll")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=255)),
                ("last_error", models.CharField(blank=True, default="", max_length=512)),
            ],
            options={
                "verbose_name": "External sync request",
                "verbose_name_plural": "External sync requests",
                "ordering": ("requested_at",),
            },
        ),
        migrations.AddIndex(
            model_name="externalworkitem",
            index=models.Index(
                fields=["is_stale", "last_synced_at"], name="external_item_stale_age_idx"
            ),
        ),
        migrations.AddField(
            model_name="externalsyncrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_sync_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="externalsyncrequest",
            index=models.Index(
                fields=["status", "requested_at"], name="external_sync_status_age_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalsyncrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user", "source"),
                name="external_sync_one_pending_per_user_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalsyncrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "dispatched")),
                fields=("user", "source"),
                name="external_sync_one_dispatched_per_user_source",
            ),
        ),
    ]
