# Generated by Django 5.2.15 on 2026-07-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0009_externalsyncrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalworkitem",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
