# Generated by Django 5.2.16 on 2026-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0010_externalworkitem_due_date"),
        ("projects", "0128_acceptancecriterion_sync_seq_apitoken_sync_seq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklink",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="tasklink",
            index=models.Index(fields=["task", "sync_seq"], name="tasklink_syncseq_idx"),
        ),
    ]
