# Generated by Django 5.2.16 on 2026-08-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0011_tasklink_sync_seq_tasklink_tasklink_syncseq_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardautomation",
            name="last_delivery_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boardautomation",
            name="last_delivery_outcome",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="boardautomation",
            name="last_delivery_provider",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="boardautomation",
            name="last_refusal_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boardautomation",
            name="last_refusal_outcome",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="boardautomation",
            name="last_refusal_provider",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
