# Generated by Django 5.2.16 on 2026-08-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0012_boardautomation_last_delivery_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalsyncrequest",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="externalsyncrequest",
            name="next_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Earliest time the drain may re-dispatch this row (rate-limit backoff).",
                null=True,
            ),
        ),
    ]
