"""Enterprise extension signal for object change history.

OSS fires ``history_record_created`` after every django-simple-history
``HistoricalRecord`` save. The enterprise package connects a receiver here to
implement unlimited retention, cold-storage export, and immutable audit
stamping — without any modification to OSS code.

Signal contract
---------------
- ``instance``         : the original model instance that was mutated
- ``history_instance`` : the ``HistoricalRecord`` that was just saved
- ``history_type``     : ``"+"`` (create), ``"~"`` (update), ``"-"`` (delete)
"""

from __future__ import annotations

import django.dispatch
from django.db.models.signals import post_save

history_record_created = django.dispatch.Signal()


def _dispatch_history_record_created(
    sender: type,
    instance: object,
    created: bool,
    **kwargs: object,
) -> None:
    """Fire ``history_record_created`` after any HistoricalRecord is saved."""
    # django-simple-history always creates new historical rows (never updates),
    # so we only need the ``created=True`` path.
    if not created:
        return
    # The HistoricalRecord instance carries ``instance`` (the tracked object)
    # and ``history_type`` as attributes.
    tracked = getattr(instance, "instance", None)
    history_type = getattr(instance, "history_type", None)
    history_record_created.send(
        sender=sender,
        instance=tracked,
        history_instance=instance,
        history_type=history_type,
    )


def _connect_to_historical_models() -> None:
    """Wire the receiver to every Historical* model generated by simple_history.

    Called from HistoryConfig.ready() after all apps are loaded so the
    Historical* models exist in the app registry.
    """
    from trueppm_api.apps.projects.models import Dependency, Project, Task

    for model in (Project, Task, Dependency):
        historical_model = model.history.model
        post_save.connect(_dispatch_history_record_created, sender=historical_model)


_connect_to_historical_models()
