"""Enterprise extension signal for object change history.

OSS fires ``history_record_created`` after every django-simple-history
``HistoricalRecord`` save. The enterprise package connects a receiver here to
implement unlimited retention, cold-storage export, and immutable audit
stamping — without any modification to OSS code.

Signal contract
---------------
- ``sender``           : the ``Historical<Model>`` class whose row was written —
  ``HistoricalTask``, ``HistoricalProject`` or ``HistoricalDependency``. A
  receiver that wants one model's history connects with
  ``sender=Task.history.model``; one that wants all three connects with no
  sender filter.
- ``instance``         : the original model instance that was mutated
- ``history_instance`` : the ``HistoricalRecord`` that was just saved
- ``history_type``     : ``"+"`` (create), ``"~"`` (update), ``"-"`` (delete)

Dispatched **inline**, from the ``post_save`` of the historical row, so it runs
inside the caller's transaction. ``instance`` is therefore a read-only snapshot
of a row that may still roll back: receivers must not save it and must defer any
I/O with ``transaction.on_commit()`` (see ``core/extension_signals.py`` for the
sender and kwarg conventions this follows).
"""

from __future__ import annotations

import django.dispatch
from django.db.models.signals import post_save

from trueppm_api.core.extension_signals import dispatch_extension_signal

history_record_created = django.dispatch.Signal()


def _dispatch_history_record_created(
    sender: type,
    instance: object,
    created: bool,
    **kwargs: object,
) -> None:
    """Fire ``history_record_created`` after any HistoricalRecord is saved."""
    # django-simple-history always creates new historical rows (never updates),
    # so we only need the ``created=True`` path.
    if not created:
        return
    # The HistoricalRecord instance carries ``instance`` (the tracked object)
    # and ``history_type`` as attributes.
    tracked = getattr(instance, "instance", None)
    history_type = getattr(instance, "history_type", None)
    # Robust dispatch is load-bearing here, not defensive style: this runs inside
    # the post_save of every Historical* row for Project, Task and Dependency, so
    # a raising enterprise receiver would fail every task save in the product
    # (#2606).
    # sender is the ``Historical<Model>`` class — the row this signal is about,
    # reachable Enterprise-side as ``Task.history.model``. Written as
    # ``type(instance)`` rather than the ``sender`` parameter so the class is
    # visible at the call site: ``sender`` here is post_save's argument and
    # reads as a pass-through of something the dispatcher chose (#3777).
    dispatch_extension_signal(
        history_record_created,
        sender=type(instance),
        instance=tracked,
        history_instance=instance,
        history_type=history_type,
    )


def _connect_to_historical_models() -> None:
    """Wire the receiver to every Historical* model generated by simple_history.

    Called from HistoryConfig.ready() after all apps are loaded so the
    Historical* models exist in the app registry.
    """
    from trueppm_api.apps.projects.models import Dependency, Project, Task

    for model in (Project, Task, Dependency):
        historical_model = model.history.model
        post_save.connect(_dispatch_history_record_created, sender=historical_model)


_connect_to_historical_models()
