import type { ComponentProps } from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach } from 'vitest';

import type { VelocitySuggestion } from '@/hooks/useVelocitySuggestions';
import { SprintReforecastCard } from './SprintReforecastCard';

const acceptMutate = vi.fn();
const dismissMutate = vi.fn();
let pendingData: VelocitySuggestion[] = [];

vi.mock('@/hooks/useVelocitySuggestions', () => ({
  usePendingVelocitySuggestions: () => ({ data: pendingData }),
  useAcceptSprintVelocitySuggestion: () => ({ mutate: acceptMutate, isPending: false }),
  useDismissSprintVelocitySuggestion: () => ({ mutate: dismissMutate, isPending: false }),
}));

function makeSuggestion(over: Partial<VelocitySuggestion> = {}): VelocitySuggestion {
  return {
    id: 'sug-1',
    task: 'task-1',
    sprint_id: 'sprint-1',
    sprint_name: 'Sprint 7',
    suggested_duration: 5,
    team_velocity_per_day: '1.5',
    flag_for_review: false,
    is_pending: true,
    created_at: '2026-06-20T00:00:00Z',
    accepted_at: null,
    accepted_by: null,
    dismissed_at: null,
    dismissed_by: null,
    ...over,
  };
}

const TASKS = [{ id: 'task-1', name: 'Wire the API', mostLikelyDuration: 8 }];

beforeEach(() => {
  acceptMutate.mockClear();
  dismissMutate.mockClear();
  pendingData = [];
});

function renderCard(over: Partial<ComponentProps<typeof SprintReforecastCard>> = {}) {
  return render(
    <SprintReforecastCard
      projectId="proj-1"
      sprintId="sprint-1"
      sprintName="Sprint 7"
      tasks={TASKS}
      canManage
      {...over}
    />,
  );
}

describe('SprintReforecastCard', () => {
  it("lists this sprint's pending suggestions with current → suggested duration", () => {
    pendingData = [makeSuggestion()];
    renderCard();
    expect(screen.getByRole('region', { name: /Velocity reforecast/i })).toBeInTheDocument();
    expect(screen.getByText('Wire the API')).toBeInTheDocument();
    expect(screen.getByText('8d')).toBeInTheDocument(); // current
    expect(screen.getByText('5d')).toBeInTheDocument(); // suggested
  });

  it('accepts and dismisses by suggestion id', () => {
    pendingData = [makeSuggestion()];
    renderCard();
    fireEvent.click(screen.getByRole('button', { name: /Accept reforecast/i }));
    expect(acceptMutate).toHaveBeenCalledWith('sug-1');
    fireEvent.click(screen.getByRole('button', { name: /Dismiss reforecast/i }));
    expect(dismissMutate).toHaveBeenCalledWith('sug-1');
  });

  it('renders nothing when the reader is not an admin', () => {
    pendingData = [makeSuggestion()];
    const { container } = renderCard({ canManage: false });
    expect(container).toBeEmptyDOMElement();
  });

  it('filters out suggestions generated by other sprints', () => {
    pendingData = [makeSuggestion({ id: 'other', sprint_id: 'sprint-2' })];
    const { container } = renderCard();
    expect(container).toBeEmptyDOMElement();
  });

  it('hides gate-suppressed suggestions (null suggested_duration)', () => {
    pendingData = [makeSuggestion({ suggested_duration: null })];
    const { container } = renderCard();
    expect(container).toBeEmptyDOMElement();
  });
});
