# Generated by Django 5.2.14 on 2026-06-23 21:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("resources", "0001_initial"),
        ("resources", "0002_alter_uuid_pk_serialize_false"),
        ("resources", "0003_resource_soft_delete"),
        ("resources", "0004_add_taskresource_resource_index"),
        ("resources", "0005_resource_job_role"),
        ("resources", "0006_skill"),
        ("resources", "0007_resource_skill"),
        ("resources", "0008_project_resource"),
        ("resources", "0009_task_skill_requirement"),
        ("resources", "0010_alter_resourceskill_options_and_more"),
        ("resources", "0011_alter_projectresource_notes"),
        ("resources", "0012_add_resource_user_fk"),
        ("resources", "0013_alter_projectresource_unique_together_and_more"),
    ]

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("projects", "0018_estimation_governance"),
        ("projects", "0078_alter_risktask_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "calendar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="projects.calendar",
                    ),
                ),
                ("max_units", models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("job_role", models.CharField(blank=True, max_length=120)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resources_resource",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=120)),
                ("normalized_name", models.CharField(max_length=120, unique=True)),
                ("category", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "db_table": "resources_skill",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_pool",
                        to="projects.project",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to="resources.resource",
                    ),
                ),
                ("role_title", models.CharField(blank=True, max_length=120)),
                (
                    "units_override",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "resources_project_resource",
                "unique_together": set(),
                "indexes": [
                    models.Index(fields=["project", "is_deleted"], name="proj_res_proj_del_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "resource"),
                        name="uniq_project_resource_project_resource",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResourceSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="resources.resource",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="resources.skill",
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        choices=[(1, "Beginner"), (2, "Intermediate"), (3, "Expert")], default=2
                    ),
                ),
            ],
            options={
                "db_table": "resources_resource_skill",
                "unique_together": set(),
                "indexes": [
                    models.Index(fields=["skill", "proficiency"], name="res_skill_prof_idx")
                ],
                "ordering": ["skill__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "skill"), name="uniq_resource_skill_resource_skill"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="projects.task",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="resources.resource",
                    ),
                ),
                ("units", models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
            ],
            options={
                "db_table": "resources_task_resource",
                "unique_together": set(),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "resource"), name="uniq_task_resource_task_resource"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskSkillRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_requirements",
                        to="projects.task",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_requirements",
                        to="resources.skill",
                    ),
                ),
                (
                    "min_proficiency",
                    models.IntegerField(
                        choices=[(1, "Beginner"), (2, "Intermediate"), (3, "Expert")], default=1
                    ),
                ),
            ],
            options={
                "db_table": "resources_task_skill_requirement",
                "unique_together": set(),
                "ordering": ["skill__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "skill"), name="uniq_task_skill_req_task_skill"
                    )
                ],
            },
        ),
    ]
