# Generated by Django 5.2.13 on 2026-04-25 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0009_task_skill_requirement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resourceskill",
            options={"ordering": ["skill__name"]},
        ),
        migrations.AlterModelOptions(
            name="taskskillrequirement",
            options={"ordering": ["skill__name"]},
        ),
    ]
