# Generated by Django 6.0.3 on 2026-05-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0010_alter_resourceskill_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectresource",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
