# Generated by Django 5.2.14 on 2026-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0078_alter_risktask_unique_together_and_more"),
        ("resources", "0012_add_resource_user_fk"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectresource",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="resourceskill",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="taskresource",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="taskskillrequirement",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="projectresource",
            constraint=models.UniqueConstraint(
                fields=("project", "resource"), name="uniq_project_resource_project_resource"
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceskill",
            constraint=models.UniqueConstraint(
                fields=("resource", "skill"), name="uniq_resource_skill_resource_skill"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskresource",
            constraint=models.UniqueConstraint(
                fields=("task", "resource"), name="uniq_task_resource_task_resource"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskskillrequirement",
            constraint=models.UniqueConstraint(
                fields=("task", "skill"), name="uniq_task_skill_req_task_skill"
            ),
        ),
    ]
