# Generated by Django 5.2.17 on 2026-10-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("resources", "0014_projectresource_sync_seq_resource_sync_seq_and_more"),
        ("resources", "0015_projectresource_deactivated_with_resource"),
    ]

    dependencies = [
        ("resources", "0001_squashed_0013_alter_projectresource_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectresource",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="resourceskill",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="skill",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="taskskillrequirement",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="projectresource",
            name="deactivated_with_resource",
            field=models.BooleanField(default=False),
        ),
    ]
