# Generated by Django 5.2.16 on 2026-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_squashed_0013_alter_projectresource_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectresource",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="resourceskill",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="skill",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="taskskillrequirement",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
