# Generated by Django 5.2.17 on 2026-09-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0014_projectresource_sync_seq_resource_sync_seq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectresource",
            name="deactivated_with_resource",
            field=models.BooleanField(default=False),
        ),
    ]
