"""Both CPM engines checked against an independent reference, not each other (#3987).

``test_wasm_conformance.py`` and ``packages/wasm-scheduler/tests/conformance.rs``
compare the Python and Rust engines through snapshots *generated by the Python
engine*, so they prove parity, not correctness: one fixture snapshot
(``milestone_tasks.json``) encoded a wrong rule both engines agreed on (#4079).
This module holds both engines to :mod:`tests.oracle.reference_cpm`, a slow
reference written from the documented CPM math, over Hypothesis-generated DAGs.

What is compared, exactly
-------------------------
* A task with work (``duration >= 1``): ``early_start`` and ``early_finish``,
  always. ``late_start``, ``late_finish``, ``total_float``, ``free_float`` and
  ``is_critical`` too, unless a milestone lies downstream of it or a milestone
  decides the project finish — then they depend on which edge of its day that
  milestone is *shown* on (#4174, #4183), a display convention the reference does
  not model (``RefTask.late_stated``). On a network with no milestones every one
  of these fields is compared on every task.
* A milestone (``duration == 0``): only its early **working-time position** — the
  shown day folded with ``milestone_at_day_end`` (the end of day ``D`` is the same
  position as the start of the next working day, #4178/#4207). Which of the two
  days it is shown on, its late dates, and its floats are not compared.
* Not compared at all: ``scheduled_start``, ``critical_path``, ``driving_edges``,
  ``project_finish`` (implied by the per-task dates), and Monte Carlo, which the
  Rust engine does not implement.
* Not generated: progress/actuals, the data date, ``planned_start``, per-task
  calendars, summary tasks. And two link shapes where both engines disagree with
  the reference, excluded until they are triaged — see :func:`_known_divergent`
  and TODO(#4272)/TODO(#4273).

The Rust side runs in two ways. The Hypothesis properties drive a native build of
the crate's ``oracle_runner`` example over stdin when ``cargo`` (or a prebuilt
runner named by ``TRUEPPM_ORACLE_RUST_RUNNER``) is available, and skip otherwise —
the ``scheduler:*`` CI image has no Rust toolchain. CI instead checks Rust against
a committed, seeded corpus generated *by the reference*
(``packages/wasm-scheduler/fixtures/oracle/corpus.json``), asserted by
``packages/wasm-scheduler/tests/oracle_conformance.rs`` under ``wasm:test``; the
corpus tests below keep that file in lock-step with the reference and check the
Python engine against it too. Regenerate with
``REGEN_ORACLE_CORPUS=1 pytest tests/test_cpm_oracle.py -k corpus``.
"""

from __future__ import annotations

import json
import os
import random
import shutil
import subprocess
from collections.abc import Iterator
from dataclasses import dataclass, replace
from datetime import date, timedelta
from pathlib import Path
from typing import Any

import pytest
from hypothesis import assume, given
from hypothesis import strategies as st

from tests.oracle.reference_cpm import (
    LINK_TYPES,
    MON_TO_FRI,
    RefCalendar,
    RefLink,
    RefProject,
    RefResult,
    first_working_on_or_after,
    last_working_on_or_before,
    milestone_shown_position,
    position_of,
    reference_schedule,
    working_days_between,
)
from trueppm_scheduler import (
    Calendar,
    DateRange,
    Dependency,
    DependencyType,
    Project,
    Task,
    schedule,
)

PACKAGES_DIR = Path(__file__).resolve().parents[2]
WASM_DIR = PACKAGES_DIR / "wasm-scheduler"
CORPUS_PATH = WASM_DIR / "fixtures" / "oracle" / "corpus.json"
REGEN_CORPUS = os.environ.get("REGEN_ORACLE_CORPUS") == "1"
CORPUS_SEED = 3987
CORPUS_SIZE = 160
# Same monorepo detection as test_wasm_conformance.py (#3856): outside the monorepo
# (an unpacked sdist) the corpus is absent and its tests skip; inside it, a missing
# corpus must fail loudly rather than silently skip (#1506).
IN_MONOREPO = os.environ.get("TRUEPPM_MONOREPO") == "1" or (
    PACKAGES_DIR.name == "packages" and (PACKAGES_DIR.parent / ".gitlab-ci.yml").is_file()
)

# ---------------------------------------------------------------------------
# Engine output, normalized so Python and Rust go through one comparator.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class EngineTask:
    early_start: date
    early_finish: date
    late_start: date
    late_finish: date
    total_float: int  # working days
    free_float: int
    is_critical: bool
    milestone_at_day_end: bool


def _whole_days(seconds: float) -> int:
    assert seconds % 86400 == 0, seconds
    return int(seconds // 86400)


def python_engine(project: RefProject) -> dict[str, EngineTask]:
    result = schedule(to_engine_project(project))
    return {
        t.id: EngineTask(
            early_start=t.early_start,
            early_finish=t.early_finish,
            late_start=t.late_start,
            late_finish=t.late_finish,
            total_float=_whole_days(t.total_float.total_seconds()),
            free_float=_whole_days(t.free_float.total_seconds()),
            is_critical=t.is_critical,
            milestone_at_day_end=t.milestone_at_day_end,
        )
        for t in result.tasks
    }


def _engine_task_from_json(row: dict[str, Any]) -> EngineTask:
    return EngineTask(
        early_start=date.fromisoformat(row["early_start"]),
        early_finish=date.fromisoformat(row["early_finish"]),
        late_start=date.fromisoformat(row["late_start"]),
        late_finish=date.fromisoformat(row["late_finish"]),
        total_float=_whole_days(row["total_float"]),
        free_float=_whole_days(row["free_float"]),
        is_critical=row["is_critical"],
        milestone_at_day_end=row.get("milestone_at_day_end", False),
    )


# ---------------------------------------------------------------------------
# Reference input -> engine input (serialization only; no scheduling math).
# ---------------------------------------------------------------------------


def to_engine_project(project: RefProject) -> Project:
    cal = project.calendar
    return Project(
        id="oracle",
        name="oracle",
        start_date=project.start,
        tasks=[
            Task(id=tid, name=tid, duration=timedelta(days=n))
            for tid, n in project.durations.items()
        ],
        dependencies=[
            Dependency(
                predecessor_id=link.pred,
                successor_id=link.succ,
                dep_type=DependencyType[link.kind],
                lag=timedelta(days=link.lag),
            )
            for link in project.links
        ],
        calendar=Calendar(
            working_days=cal.working_mask,
            exceptions=[DateRange(start=lo, end=hi) for lo, hi in cal.exceptions],
        ),
    )


def project_document(project: RefProject) -> dict[str, Any]:
    """The minimal ``Project.from_dict`` document both engines parse (fixture shape)."""
    cal = project.calendar
    return {
        "id": "oracle",
        "name": "oracle",
        "start_date": project.start.isoformat(),
        "tasks": [
            {"id": tid, "name": tid, "duration": n * 86400.0}
            for tid, n in project.durations.items()
        ],
        "dependencies": [
            {
                "predecessor_id": link.pred,
                "successor_id": link.succ,
                "dep_type": link.kind,
                "lag": link.lag * 86400.0,
            }
            for link in project.links
        ],
        "calendar": {
            "working_days": cal.working_mask,
            "exceptions": [
                {"start": lo.isoformat(), "end": hi.isoformat()} for lo, hi in cal.exceptions
            ],
        },
    }


# ---------------------------------------------------------------------------
# The comparator
# ---------------------------------------------------------------------------


def engine_milestone_position(task: EngineTask, ref: RefResult, cal: RefCalendar) -> int:
    """Working-time position of an engine milestone's shown early date.

    A milestone shown at the end of day ``D`` sits at the midnight closing ``D``;
    shown at the start of ``D``, at the midnight opening it (#4178, #4207).
    """
    instant = task.early_start + timedelta(days=1 if task.milestone_at_day_end else 0)
    return position_of(instant, ref.project_start_at, cal)


def mismatches(engine: dict[str, EngineTask], ref: RefResult, project: RefProject) -> list[str]:
    """Every field (in the compared set) where the engine disagrees with the reference."""
    cal = project.calendar
    out: list[str] = []
    assert set(engine) == set(ref.tasks)
    for tid, want in sorted(ref.tasks.items()):
        got = engine[tid]
        if want.is_milestone:
            have = engine_milestone_position(got, ref, cal)
            need = milestone_shown_position(want, ref, cal)
            if have != need:
                out.append(
                    f"{tid}: milestone position {have} (shown {got.early_start}, "
                    f"at_day_end={got.milestone_at_day_end}), reference {need}"
                )
            continue
        pairs = [
            ("early_start", got.early_start, want.early_start),
            ("early_finish", got.early_finish, want.early_finish),
        ]
        if want.late_stated:
            pairs += [
                ("late_start", got.late_start, want.late_start),
                ("late_finish", got.late_finish, want.late_finish),
                ("total_float", got.total_float, want.total_float),
                ("is_critical", got.is_critical, want.total_float == 0),
                ("free_float", got.free_float, want.free_float),
            ]
        out.extend(f"{tid}: {name} {g} != reference {w}" for name, g, w in pairs if g != w)
    return out


def assert_matches_reference(engine: dict[str, EngineTask], project: RefProject) -> None:
    ref = reference_schedule(project)
    problems = mismatches(engine, ref, project)
    assert not problems, "\n".join([repr(project), *problems])


# ---------------------------------------------------------------------------
# Generated networks
# ---------------------------------------------------------------------------

_EPOCH = date(2026, 1, 5)  # a Monday


@st.composite
def ref_calendars(draw: st.DrawFn) -> RefCalendar:
    mask = draw(st.one_of(st.just(MON_TO_FRI), st.integers(1, 0b1111111)))
    ranges = []
    for _ in range(draw(st.integers(0, 2))):
        lo = _EPOCH + timedelta(days=draw(st.integers(0, 40)))
        ranges.append((lo, lo + timedelta(days=draw(st.integers(0, 2)))))
    return RefCalendar(working_mask=mask, exceptions=tuple(ranges))


@st.composite
def ref_projects(draw: st.DrawFn, milestones: bool = True, max_tasks: int = 7) -> RefProject:
    """A random DAG: edges only run from a lower to a higher index, so no cycles."""
    n = draw(st.integers(1, max_tasks))
    low = 0 if milestones else 1
    durations = {f"T{i}": draw(st.integers(low, 6)) for i in range(n)}
    links = []
    for j in range(n):
        for i in range(j):
            if draw(st.integers(0, 2)) == 0:
                links.append(
                    RefLink(
                        pred=f"T{i}",
                        succ=f"T{j}",
                        kind=draw(st.sampled_from(LINK_TYPES)),
                        lag=draw(st.integers(-4, 6)),
                    )
                )
    return RefProject(
        start=_EPOCH + timedelta(days=draw(st.integers(0, 9))),
        durations=durations,
        links=tuple(links),
        calendar=draw(ref_calendars()),
    )


def random_ref_project(rng: random.Random) -> RefProject:
    """The corpus generator: the same shape as :func:`ref_projects`, from a seeded RNG."""
    n = rng.randint(1, 8)
    durations = {f"T{i}": (0 if rng.random() < 0.2 else rng.randint(1, 6)) for i in range(n)}
    links = tuple(
        RefLink(f"T{i}", f"T{j}", rng.choice(LINK_TYPES), rng.randint(-4, 6))
        for j in range(n)
        for i in range(j)
        if rng.random() < 0.35
    )
    mask = MON_TO_FRI if rng.random() < 0.6 else rng.randint(1, 0b1111111)
    ranges = []
    for _ in range(rng.randint(0, 2)):
        lo = _EPOCH + timedelta(days=rng.randint(0, 40))
        ranges.append((lo, lo + timedelta(days=rng.randint(0, 2))))
    return RefProject(
        start=_EPOCH + timedelta(days=rng.randint(0, 9)),
        durations=durations,
        links=links,
        calendar=RefCalendar(working_mask=mask, exceptions=tuple(ranges)),
    )


def _known_divergent(project: RefProject) -> bool:
    """Networks where both engines disagree with the reference — reported, unfixed.

    * TODO(#4272): a lagged FF or SF link *into* a milestone: the engines snap
      the milestone as if it were a task's finish, onto the end of a working
      day, so it can sit one working day after the same link written as FS.
      ``A(5d, Mon-Fri) -FF+1d-> M -FS-> C(1d)`` starts ``C`` on Tuesday; with
      ``-FS+1d->`` it starts Monday.
    * TODO(#4273): an FF link *out of* a milestone: the engines anchor it on
      the end of the working day before a start-of-day milestone rather than
      on its instant, so a later lag is absorbed by the weekend.
      ``M0(held at project start, Mon) -FF-> M1 -FS+1d-> T(1d)`` starts ``T``
      on Monday; with ``M0 -FS-> M1`` it starts Tuesday.

    For a zero-duration task start and finish are one instant, so in both cases
    FS and FF must agree; the reference has them agree, the engines do not.
    """
    is_milestone = {tid: n == 0 for tid, n in project.durations.items()}
    return any(
        (link.kind == "FF" and is_milestone[link.pred])  # TODO(#4273)
        or (link.lag != 0 and link.kind in ("FF", "SF") and is_milestone[link.succ])  # TODO(#4272)
        for link in project.links
    )


# ---------------------------------------------------------------------------
# Python engine == reference
# ---------------------------------------------------------------------------


@pytest.mark.fuzz
@given(ref_projects(milestones=False))
def test_python_engine_matches_reference_on_networks_of_work(project: RefProject) -> None:
    """Every compared field, every link type with lead/lag, any working-day calendar."""
    assert_matches_reference(python_engine(project), project)


@pytest.mark.fuzz
@given(ref_projects(milestones=True))
def test_python_engine_matches_reference_with_milestones(project: RefProject) -> None:
    """Milestones anywhere: their working-time position, and every task with work."""
    assume(not _known_divergent(project))
    assert_matches_reference(python_engine(project), project)


# ---------------------------------------------------------------------------
# Rust engine == reference (native build of the crate's oracle_runner example)
# ---------------------------------------------------------------------------


class RustRunner:
    """A long-lived ``oracle_runner`` process: one project JSON per stdin line."""

    def __init__(self, binary: Path) -> None:
        self._proc = subprocess.Popen(
            [str(binary)],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            text=True,
        )

    def schedule(self, project: RefProject) -> dict[str, EngineTask]:
        assert self._proc.stdin is not None and self._proc.stdout is not None
        doc = json.dumps(project_document(project))
        self._proc.stdin.write(doc + "\n")
        self._proc.stdin.flush()
        reply = json.loads(self._proc.stdout.readline())
        assert "ok" in reply, reply
        return {row["id"]: _engine_task_from_json(row) for row in reply["ok"]["tasks"]}

    def close(self) -> None:
        if self._proc.stdin is not None:
            self._proc.stdin.close()
        self._proc.wait(timeout=30)


def _rust_runner_binary() -> Path | None:
    named = os.environ.get("TRUEPPM_ORACLE_RUST_RUNNER")
    if named:
        return Path(named)
    if shutil.which("cargo") is None or not (WASM_DIR / "Cargo.toml").is_file():
        return None
    subprocess.run(
        ["cargo", "build", "--quiet", "--example", "oracle_runner"],
        cwd=WASM_DIR,
        check=True,
        timeout=900,
    )
    return WASM_DIR / "target" / "debug" / "examples" / "oracle_runner"


@pytest.fixture(scope="module")
def rust_engine() -> Iterator[RustRunner]:
    binary = _rust_runner_binary()
    if binary is None:
        pytest.skip(
            "No Rust toolchain: the live Rust-vs-reference properties need `cargo` or "
            "TRUEPPM_ORACLE_RUST_RUNNER. CI checks Rust against the committed oracle "
            "corpus in wasm:test (tests/oracle_conformance.rs) instead."
        )
    runner = RustRunner(binary)
    yield runner
    runner.close()


@pytest.mark.fuzz
@given(project=ref_projects(milestones=False))
def test_rust_engine_matches_reference_on_networks_of_work(
    rust_engine: RustRunner, project: RefProject
) -> None:
    assert_matches_reference(rust_engine.schedule(project), project)


@pytest.mark.fuzz
@given(project=ref_projects(milestones=True))
def test_rust_engine_matches_reference_with_milestones(
    rust_engine: RustRunner, project: RefProject
) -> None:
    assume(not _known_divergent(project))
    assert_matches_reference(rust_engine.schedule(project), project)


# ---------------------------------------------------------------------------
# Named milestone properties (#4079 pre-release audit). Each is asserted on the
# Python engine *and* on the reference, so a property that only the oracle
# believes cannot pass silently.
# ---------------------------------------------------------------------------


@st.composite
def networks_with_an_fs_link(draw: st.DrawFn) -> tuple[RefProject, RefLink]:
    """A network of work, and one FS link ``A -> B`` in it to split."""
    project = draw(ref_projects(milestones=False))
    n = len(project.durations)
    if n < 2:
        project = replace(project, durations={**project.durations, "T1": 2})
        n = 2
    j = draw(st.integers(1, n - 1))
    i = draw(st.integers(0, j - 1))
    link = RefLink(f"T{i}", f"T{j}", "FS", draw(st.integers(-4, 6)))
    # One link per ordered pair: replace whatever A -> B carried with the FS link.
    others = tuple(ln for ln in project.links if (ln.pred, ln.succ) != (link.pred, link.succ))
    return replace(project, links=(*others, link)), link


def _split_with_milestone(project: RefProject, link: RefLink) -> RefProject:
    """``A -FS(l)-> B`` becomes ``A -FS(0)-> M -FS(l)-> B``."""
    links = (
        *(ln for ln in project.links if ln != link),
        RefLink(link.pred, "M", "FS", 0),
        RefLink("M", link.succ, "FS", link.lag),
    )
    return replace(project, durations={**project.durations, "M": 0}, links=links)


def _unchanged_except_free_float_of(
    before: dict[str, EngineTask], after: dict[str, EngineTask], tid_with_new_successor: str
) -> None:
    """Every original task keeps every field; the one that gained a milestone
    successor may change only its free float, which is read on that milestone's
    shown day (scheduler.md, the free_float note)."""
    for tid, t in before.items():
        u = after[tid]
        if tid == tid_with_new_successor:
            u = replace(u, free_float=t.free_float)
        assert u == t, tid


def _assert_milestone_on_finish_of(
    after: dict[str, EngineTask], project: RefProject, a: str, m: str
) -> None:
    """``m`` sits on ``a``'s early finish, compared in working time (#4207).

    When ``a`` finishes after the project start, ``m`` is shown at the end of
    ``a``'s finish day exactly. An SF-only ``a`` can finish before the project
    start (#4218); ``m`` is then shown at the project start (#4225).
    """
    ref = reference_schedule(project)
    finish_at = ref.tasks[a].finish_at
    shown_at = max(finish_at, ref.project_start_at)
    cal = project.calendar
    expected = position_of(shown_at, ref.project_start_at, cal)
    assert engine_milestone_position(after[m], ref, cal) == expected
    if finish_at > ref.project_start_at:
        assert after[m].early_start == after[a].early_finish
        assert after[m].milestone_at_day_end


@pytest.mark.fuzz
@given(networks_with_an_fs_link())
def test_inserting_a_milestone_into_an_fs_link_moves_nothing(
    case: tuple[RefProject, RefLink],
) -> None:
    """``A -FS(l)-> B`` vs ``A -FS(0)-> M -FS(l)-> B``: nothing moves; ``M`` sits on A's EF.

    Every original task keeps every compared field (A's free float aside), and the
    reference agrees on both networks, so this is not a property only the engine's
    own conventions satisfy.
    """
    project, link = case
    split = _split_with_milestone(project, link)
    before, after = python_engine(project), python_engine(split)
    _unchanged_except_free_float_of(before, after, link.pred)
    _assert_milestone_on_finish_of(after, split, link.pred, "M")
    assert_matches_reference(before, project)
    assert_matches_reference(after, split)


@pytest.mark.fuzz
@given(ref_projects(milestones=True), st.data())
def test_a_start_milestone_at_project_start_delays_nothing(
    project: RefProject, data: st.DataObject
) -> None:
    """``S -FS(0)->`` any task with work that is not SF-only changes nothing at all.

    Excluded on purpose, as documented behavior rather than a delay: an SF-only
    task, which any FS link returns to the project-start floor (#4218); and a
    milestone, whose links count from its raw instant even before the project
    start (#4225), so a link from ``S`` would hold it there.
    """
    assume(not _known_divergent(project))
    eligible = sorted(
        tid
        for tid, n in project.durations.items()
        if n > 0
        and not (
            (inc := [ln for ln in project.links if ln.succ == tid])
            and all(ln.kind == "SF" for ln in inc)
        )
    )
    assume(eligible)
    targets = data.draw(st.lists(st.sampled_from(eligible), unique=True, min_size=1))
    with_start = replace(
        project,
        durations={"S": 0, **project.durations},
        links=project.links + tuple(RefLink("S", t, "FS", 0) for t in targets),
    )
    before, after = python_engine(project), python_engine(with_start)
    for tid, t in before.items():
        assert after[tid] == t, tid
    assert_matches_reference(after, with_start)


@pytest.mark.fuzz
@given(ref_projects(milestones=True))
def test_every_task_with_work_spans_exactly_its_duration(project: RefProject) -> None:
    """``EF - ES + 1 == duration`` in working days, for every non-milestone task."""
    cal = project.calendar
    engine = python_engine(project)
    ref = reference_schedule(project)
    for tid, n in project.durations.items():
        if n == 0:
            continue
        got = engine[tid]
        span = working_days_between(got.early_start, got.early_finish + timedelta(days=1), cal)
        assert span == n, tid
        late = working_days_between(got.late_start, got.late_finish + timedelta(days=1), cal)
        assert late == n, tid
        want = ref.tasks[tid]
        assert working_days_between(want.start_at, want.finish_at, cal) == n, tid


@pytest.mark.fuzz
@given(ref_projects(milestones=False), st.data())
def test_a_zero_day_fs_milestone_is_time_neutral(project: RefProject, data: st.DataObject) -> None:
    """Hanging ``A -FS(0)-> M`` off any task moves no other task (#4079).

    Before #4079 a milestone took a working day, so this moved the project finish
    whenever ``A`` was on the critical path.
    """
    anchor = data.draw(st.sampled_from(sorted(project.durations)))
    with_m = replace(
        project,
        durations={**project.durations, "M": 0},
        links=(*project.links, RefLink(anchor, "M", "FS", 0)),
    )
    before, after = python_engine(project), python_engine(with_m)
    _unchanged_except_free_float_of(before, after, anchor)
    _assert_milestone_on_finish_of(after, with_m, anchor, "M")
    assert_matches_reference(after, with_m)


# ---------------------------------------------------------------------------
# The committed corpus — how Rust is held to the reference in CI.
# ---------------------------------------------------------------------------


def _expected_row(project: RefProject, ref: RefResult, tid: str) -> dict[str, Any]:
    """What ``oracle_conformance.rs`` asserts for one task, from the reference alone."""
    want = ref.tasks[tid]
    cal = project.calendar
    if want.is_milestone:
        # Either shown reading of the reference instant is accepted: the start of
        # the first working day at or after it, or the end of the working day
        # before that one — the same working-time position (#4178, #4207).
        assert want.shown_at is not None
        day = first_working_on_or_after(want.shown_at, cal)
        prior = last_working_on_or_before(day - timedelta(days=1), cal)
        return {"milestone_shown": [[day.isoformat(), False], [prior.isoformat(), True]]}
    row: dict[str, Any] = {
        "early_start": want.early_start.isoformat(),
        "early_finish": want.early_finish.isoformat(),
    }
    if want.late_stated:
        row |= {
            "late_start": want.late_start.isoformat(),
            "late_finish": want.late_finish.isoformat(),
            "total_float_days": want.total_float,
            "free_float_days": want.free_float,
        }
    return row


def build_corpus() -> dict[str, Any]:
    rng = random.Random(CORPUS_SEED)
    cases = []
    for k in range(CORPUS_SIZE):
        project = random_ref_project(rng)
        while _known_divergent(project):
            project = random_ref_project(rng)
        ref = reference_schedule(project)
        cases.append(
            {
                "name": f"case_{k:03d}",
                "project": project_document(project),
                "expected": {tid: _expected_row(project, ref, tid) for tid in project.durations},
            }
        )
    return {
        "_comment": (
            "Generated by the independent reference CPM (packages/scheduler/tests/oracle/"
            "reference_cpm.py), NOT by either engine (#3987). Regenerate with "
            "REGEN_ORACLE_CORPUS=1 pytest packages/scheduler/tests/test_cpm_oracle.py -k corpus"
        ),
        "seed": CORPUS_SEED,
        "cases": cases,
    }


def _load_corpus() -> dict[str, Any]:
    if not CORPUS_PATH.is_file():
        if IN_MONOREPO:
            pytest.fail(
                f"oracle corpus missing at {CORPUS_PATH}; regenerate with REGEN_ORACLE_CORPUS=1"
            )
        pytest.skip(f"oracle corpus not found at {CORPUS_PATH} (outside the monorepo)")
    with open(CORPUS_PATH) as f:
        loaded: dict[str, Any] = json.load(f)
    return loaded


def _corpus_text(corpus: dict[str, Any]) -> str:
    """One case per line, so a regenerated corpus diffs case by case."""
    head = {k: v for k, v in corpus.items() if k != "cases"}
    lines = [json.dumps(case, sort_keys=True) for case in corpus["cases"]]
    return json.dumps(head, sort_keys=True)[:-1] + ', "cases": [\n' + ",\n".join(lines) + "\n]}\n"


def test_corpus_is_what_the_reference_generates() -> None:
    """The committed corpus cannot drift from the reference that generated it."""
    fresh = _corpus_text(build_corpus())
    if REGEN_CORPUS:
        CORPUS_PATH.parent.mkdir(exist_ok=True)
        CORPUS_PATH.write_text(fresh)
    _load_corpus()  # skips outside the monorepo
    assert CORPUS_PATH.read_text() == fresh, (
        "fixtures/oracle/corpus.json is stale; regenerate with REGEN_ORACLE_CORPUS=1"
    )


def _corpus_row_mismatches(row: dict[str, Any], got: EngineTask) -> list[str]:
    if "milestone_shown" in row:
        shown = [got.early_start.isoformat(), got.milestone_at_day_end]
        return [] if shown in row["milestone_shown"] else [f"milestone shown {shown}"]
    actual = {
        "early_start": got.early_start.isoformat(),
        "early_finish": got.early_finish.isoformat(),
        "late_start": got.late_start.isoformat(),
        "late_finish": got.late_finish.isoformat(),
        "total_float_days": got.total_float,
        "free_float_days": got.free_float,
    }
    return [f"{k} {actual[k]} != {v}" for k, v in row.items() if actual[k] != v]


def test_python_engine_matches_the_oracle_corpus() -> None:
    """The same check ``oracle_conformance.rs`` runs on Rust, run on Python."""
    corpus = _load_corpus()
    assert len(corpus["cases"]) == CORPUS_SIZE
    problems = []
    for case in corpus["cases"]:
        result = schedule(Project.from_dict(case["project"]))
        for t in result.tasks:
            got = EngineTask(
                t.early_start,
                t.early_finish,
                t.late_start,
                t.late_finish,
                _whole_days(t.total_float.total_seconds()),
                _whole_days(t.free_float.total_seconds()),
                t.is_critical,
                t.milestone_at_day_end,
            )
            problems += [
                f"{case['name']}/{t.id}: {p}"
                for p in _corpus_row_mismatches(case["expected"][t.id], got)
            ]
    assert not problems, "\n".join(problems)
