// Generated by openapi-typescript. Do not edit manually.
// Run: npm run generate:types
//
// This file is committed to version control so CI can typecheck without a running API.
// Regenerate when the API schema changes: npm run generate:types (requires a running API).

export type {};

/**
 * DRF PageNumberPagination envelope — all list endpoints return this shape.
 * The API uses PAGE_SIZE=50 globally (settings/base.py).
 */
export interface PaginatedResponse<T> {
  count: number;
  next: string | null;
  previous: string | null;
  results: T[];
}

// Risk Register types (issue #52). Hand-authored until openapi-typescript regeneration.
export interface Risk {
  id: string;
  /** Short per-project hex ID shared with the Task counter (e.g. "a3f1"). */
  short_id: string;
  server_version: number;
  project: string;
  title: string;
  description: string;
  status: 'OPEN' | 'MITIGATING' | 'RESOLVED' | 'ACCEPTED' | 'CLOSED';
  probability: number;
  impact: number;
  /** Computed by the API: probability × impact (1–25). */
  severity: number;
  owner: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  tasks: string[];
}
