// Generated by openapi-typescript. Do not edit manually.
// Run: npm run generate:types
//
// This file is committed to version control so CI can typecheck without a running API.
// Regenerate when the API schema changes: npm run generate:types (requires a running API).

export type {};

/**
 * DRF PageNumberPagination envelope — all list endpoints return this shape.
 * The API uses PAGE_SIZE=50 globally (settings/base.py).
 */
export interface PaginatedResponse<T> {
  count: number;
  next: string | null;
  previous: string | null;
  results: T[];
}

// Risk Register types (issues #52, #221). Hand-authored until openapi-typescript regeneration.
export interface Risk {
  id: string;
  /** Short per-project hex ID shared with the Task counter (e.g. "a3f1"). */
  short_id: string;
  server_version: number;
  project: string;
  title: string;
  description: string;
  status: 'OPEN' | 'MITIGATING' | 'RESOLVED' | 'ACCEPTED' | 'CLOSED';
  probability: number;
  impact: number;
  /** Computed by the API: probability × impact (1–25). */
  severity: number;
  owner: string | null;
  /** Display name for the owner — first+last, falls back to username. Null when unassigned. */
  owner_name?: string | null;
  /** 1–2 char initials for the owner — used in matrix bubbles and the register table avatar. */
  owner_initials?: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  tasks: string[];
  // PMI framework fields (ADR-0043, wave 7 issue #221) — all optional/nullable
  category?: 'TECHNICAL' | 'EXTERNAL' | 'ORGANIZATIONAL' | 'PROJECT_MANAGEMENT' | null;
  response?: 'AVOID' | 'MITIGATE' | 'TRANSFER' | 'ACCEPT' | null;
  mitigation_due_date?: string | null;
  trigger?: string;
  contingency?: string;
  /** Long-form PM annotations (ADR-0048). Empty string when unset. */
  notes: string;
}

// Risk comments — append-only discussion thread (ADR-0044, issue #244)
export interface RiskCommentAuthor {
  id: string;
  display_name: string;
}

export interface RiskComment {
  id: string;
  author: RiskCommentAuthor | null;
  message: string;
  created_at: string;
}
