# Generated by Django 5.2.14 on 2026-06-23 21:38

import datetime
import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("observability", "0001_initial"),
        ("observability", "0002_purgerun_retentionpolicy_retentionschedule"),
        ("observability", "0003_alter_purgerun_trigger"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BeatHeartbeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
                ),
                ("last_heartbeat", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("HISTORY_RETENTION_DAYS", "Event history"),
                            ("TASK_RUN_RETENTION_DAYS", "Task runs"),
                            ("TRUEPPM_WEBHOOK_RETENTION_DAYS", "Webhook deliveries"),
                            ("TRUEPPM_IMPORT_RETENTION_DAYS", "Import requests"),
                            ("TRUEPPM_SYNC_BATCH_RETENTION_HOURS", "Sync batches"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("value", models.PositiveIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "retention policies",
            },
        ),
        migrations.CreateModel(
            name="RetentionSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("off", "Off")],
                        default="daily",
                        max_length=8,
                    ),
                ),
                ("time_of_day_utc", models.TimeField(default=datetime.time(2, 0))),
                ("day_of_week", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "on_failure",
                    models.CharField(
                        choices=[
                            ("continue", "Continue and flag the failed table"),
                            ("stop", "Stop the run on first error"),
                        ],
                        default="continue",
                        max_length=8,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PurgeRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                            ("dry_run", "Dry run"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("ok", "OK"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=8,
                    ),
                ),
                ("tables", models.JSONField(default=list)),
                ("rows_deleted", models.PositiveIntegerField(default=0)),
                ("bytes_freed", models.PositiveBigIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
