# Generated by Django 5.2.14 on 2026-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observability", "0002_purgerun_retentionpolicy_retentionschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purgerun",
            name="trigger",
            field=models.CharField(
                choices=[("scheduled", "Scheduled"), ("manual", "Manual"), ("dry_run", "Dry run")],
                default="scheduled",
                max_length=10,
            ),
        ),
    ]
