# Generated by Django 5.2.14 on 2026-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observability", "0001_squashed_0003_alter_purgerun_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retentionpolicy",
            name="key",
            field=models.CharField(
                choices=[
                    ("HISTORY_RETENTION_DAYS", "Event history"),
                    ("TASK_RUN_RETENTION_DAYS", "Task runs"),
                    ("TRUEPPM_WEBHOOK_RETENTION_DAYS", "Webhook deliveries"),
                    ("TRUEPPM_IMPORT_RETENTION_DAYS", "Import requests"),
                    ("TRUEPPM_SYNC_BATCH_RETENTION_HOURS", "Sync batches"),
                    ("TRUEPPM_PROJECT_SOFT_DELETE_RETENTION_DAYS", "Soft-deleted projects"),
                ],
                max_length=64,
                unique=True,
            ),
        ),
    ]
