# Generated by Django 5.1.15 on 2026-03-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("ON_HOLD", "On hold"),
                    ("COMPLETE", "Complete"),
                ],
                db_index=True,
                default="NOT_STARTED",
                max_length=12,
            ),
        ),
    ]
