# Generated by Django 5.2.12 on 2026-03-27 03:52

from django.db import migrations, models

_HELP = "Start no earlier than (SNET). CPM floor applied during forward pass."


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="planned_start",
            field=models.DateField(blank=True, db_index=True, help_text=_HELP, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="planned_start",
            field=models.DateField(blank=True, db_index=True, help_text=_HELP, null=True),
        ),
    ]
