# Generated by Django 6.0.3 on 2026-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_boardcolumnconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='estimation_mode',
            field=models.CharField(choices=[('open', 'Open'), ('suggest_approve', 'Suggest & Approve'), ('pm_only', 'PM Only')], default='open', max_length=16),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='estimate_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Approval'), ('accepted', 'Accepted')], db_index=True, help_text='Approval state for three-point estimates (suggest_approve mode only).', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimation_mode',
            field=models.CharField(choices=[('open', 'Open'), ('suggest_approve', 'Suggest & Approve'), ('pm_only', 'PM Only')], default='open', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='estimate_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Approval'), ('accepted', 'Accepted')], db_index=True, help_text='Approval state for three-point estimates (suggest_approve mode only).', max_length=12, null=True),
        ),
    ]
