# Generated by Django 6.0.3 on 2026-04-28 17:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0020_task_status_5col"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardSavedView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("config", models.JSONField()),
                ("server_version", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_saved_views",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "board saved view",
                "verbose_name_plural": "board saved views",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "name"),
                        name="unique_board_saved_view_name",
                    )
                ],
            },
        ),
    ]
