# Generated by Django 6.0.3 on 2026-04-28 21:01

from django.db import migrations, models

_PRIORITY_HELP = "Priority rank within the project; lower is higher priority."
_STATUS_CHANGED_HELP = "When this task last entered its current status column."


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0021_boardsavedview"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="priority_rank",
            field=models.PositiveIntegerField(blank=True, help_text=_PRIORITY_HELP, null=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, help_text=_STATUS_CHANGED_HELP, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="priority_rank",
            field=models.PositiveIntegerField(blank=True, help_text=_PRIORITY_HELP, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, help_text=_STATUS_CHANGED_HELP, null=True),
        ),
    ]
