# Generated by Django 6.0.3 on 2026-04-29 21:12

from django.db import migrations, models

_CATEGORY_CHOICES = [
    ("TECHNICAL", "Technical"),
    ("EXTERNAL", "External"),
    ("ORGANIZATIONAL", "Organizational"),
    ("PROJECT_MANAGEMENT", "Project Management"),
]

_RESPONSE_CHOICES = [
    ("AVOID", "Avoid"),
    ("MITIGATE", "Mitigate"),
    ("TRANSFER", "Transfer"),
    ("ACCEPT", "Accept"),
]


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0022_task_status_changed_at_priority_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrisk",
            name="category",
            field=models.CharField(
                blank=True,
                choices=_CATEGORY_CHOICES,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalrisk",
            name="contingency",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalrisk",
            name="mitigation_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalrisk",
            name="response",
            field=models.CharField(
                blank=True,
                choices=_RESPONSE_CHOICES,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalrisk",
            name="trigger",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="risk",
            name="category",
            field=models.CharField(
                blank=True,
                choices=_CATEGORY_CHOICES,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="contingency",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="risk",
            name="mitigation_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="risk",
            name="response",
            field=models.CharField(
                blank=True,
                choices=_RESPONSE_CHOICES,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="trigger",
            field=models.TextField(blank=True, default=""),
        ),
    ]
