# Generated by Django 6.0.3 on 2026-05-01 04:11

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0024_riskcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="agile_features",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="story_points",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="agile_features",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="story_points",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HistoricalSprint",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("short_id", models.CharField(blank=True, editable=False, max_length=8)),
                ("name", models.CharField(max_length=255)),
                ("goal", models.TextField(blank=True, default="")),
                ("start_date", models.DateField()),
                ("finish_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PLANNED",
                        max_length=12,
                    ),
                ),
                ("committed_points", models.PositiveIntegerField(blank=True, null=True)),
                ("committed_task_count", models.PositiveIntegerField(blank=True, null=True)),
                ("completed_points", models.PositiveIntegerField(blank=True, null=True)),
                ("completed_task_count", models.PositiveIntegerField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "target_milestone",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Optional milestone task this sprint progresses toward.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sprint",
                "verbose_name_plural": "historical sprints",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("short_id", models.CharField(blank=True, editable=False, max_length=8)),
                ("name", models.CharField(max_length=255)),
                ("goal", models.TextField(blank=True, default="")),
                ("start_date", models.DateField()),
                ("finish_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PLANNED",
                        max_length=12,
                    ),
                ),
                ("committed_points", models.PositiveIntegerField(blank=True, null=True)),
                ("committed_task_count", models.PositiveIntegerField(blank=True, null=True)),
                ("completed_points", models.PositiveIntegerField(blank=True, null=True)),
                ("completed_task_count", models.PositiveIntegerField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="projects.project",
                    ),
                ),
                (
                    "target_milestone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional milestone task this sprint progresses toward.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeting_sprints",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_sprint",
                "ordering": ["start_date", "name"],
            },
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.sprint",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="projects.sprint",
            ),
        ),
        migrations.CreateModel(
            name="SprintBurnSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("remaining_points", models.PositiveIntegerField()),
                ("remaining_task_count", models.PositiveIntegerField()),
                ("completed_points", models.PositiveIntegerField()),
                ("completed_task_count", models.PositiveIntegerField()),
                ("scope_change_points", models.IntegerField(default=0)),
                ("scope_change_task_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="burn_snapshots",
                        to="projects.sprint",
                    ),
                ),
            ],
            options={
                "db_table": "projects_sprintburnsnapshot",
                "ordering": ["sprint_id", "snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="SprintCloseRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "carry_over_to",
                    models.CharField(
                        default="backlog",
                        help_text="Either 'backlog', 'none', or a sprint UUID string.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_flight", "In Flight"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sprint_close_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="close_requests",
                        to="projects.sprint",
                    ),
                ),
            ],
            options={
                "db_table": "projects_sprintcloserequest",
                "ordering": ["requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(fields=["project", "state"], name="sprint_project_state_idx"),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(fields=["project", "start_date"], name="sprint_project_start_idx"),
        ),
        migrations.AddConstraint(
            model_name="sprint",
            constraint=models.UniqueConstraint(
                fields=("project", "short_id"), name="unique_sprint_short_id_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="sprint",
            constraint=models.CheckConstraint(
                condition=models.Q(("finish_date__gt", models.F("start_date"))),
                name="sprint_finish_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="sprintburnsnapshot",
            index=models.Index(fields=["sprint", "snapshot_date"], name="sprint_burn_lookup_idx"),
        ),
        migrations.AddConstraint(
            model_name="sprintburnsnapshot",
            constraint=models.UniqueConstraint(
                fields=("sprint", "snapshot_date"), name="unique_sprint_snapshot_per_day"
            ),
        ),
        migrations.AddIndex(
            model_name="sprintcloserequest",
            index=models.Index(fields=["status", "requested_at"], name="sprint_close_status_idx"),
        ),
    ]
