# Generated by Django 5.2.13 on 2026-05-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0025_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="methodology",
            field=models.CharField(
                choices=[("WATERFALL", "Waterfall"), ("AGILE", "Agile"), ("HYBRID", "Hybrid")],
                default="HYBRID",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="methodology",
            field=models.CharField(
                choices=[("WATERFALL", "Waterfall"), ("AGILE", "Agile"), ("HYBRID", "Hybrid")],
                default="HYBRID",
                max_length=16,
            ),
        ),
    ]
