# Generated by Django 6.0.3 on 2026-05-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0027_sprint_retro"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrisk",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalsprint",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="risk",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sprint",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
