# Generated by Django 6.0.3 on 2026-05-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0030_review_implies_full_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="remaining_points",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="remaining_points",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
