# Generated by Django 6.0.3 on 2026-05-20 02:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import trueppm_api.apps.projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0037_sprint_capacity_points"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField()),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_task_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="projects.taskcomment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_taskcomment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("emoji", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="projects.taskcomment",
                    ),
                ),
            ],
            options={
                "db_table": "projects_commentreaction",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentAcknowledgement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_acknowledgements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="projects.taskcomment",
                    ),
                ),
            ],
            options={
                "db_table": "projects_commentacknowledgement",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        default="",
                        upload_to=trueppm_api.apps.projects.models._task_attachment_upload_to,
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("file_mime", models.CharField(blank=True, default="", max_length=128)),
                ("external_url", models.URLField(blank=True, default="", max_length=2048)),
                ("external_title", models.CharField(blank=True, default="", max_length=255)),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="projects.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_taskattachment",
                "ordering": ["-is_pinned", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "is_deleted", "-created_at"], name="ix_attach_task_recent"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(models.Q(("file", ""), _negated=True), ("external_url", "")),
                            models.Q(("file", ""), models.Q(("external_url", ""), _negated=True)),
                            _connector="OR",
                        ),
                        name="taskattachment_file_xor_url",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(
                fields=["task", "is_deleted", "created_at"], name="ix_comment_task_chrono"
            ),
        ),
        migrations.AddConstraint(
            model_name="commentreaction",
            constraint=models.UniqueConstraint(
                fields=("comment", "user", "emoji"), name="uq_commentreaction_comment_user_emoji"
            ),
        ),
        migrations.AddConstraint(
            model_name="commentacknowledgement",
            constraint=models.UniqueConstraint(
                fields=("comment", "user"), name="uq_commentack_comment_user"
            ),
        ),
    ]
