# Generated by Django 6.0.3 on 2026-05-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0040_program_general_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="code",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="default_view",
            field=models.CharField(
                choices=[
                    ("SCHEDULE", "Schedule"),
                    ("BOARD", "Board"),
                    ("TABLE", "Table"),
                    ("OVERVIEW", "Overview"),
                ],
                default="SCHEDULE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="health",
            field=models.CharField(
                choices=[
                    ("AUTO", "Auto"),
                    ("ON_TRACK", "On track"),
                    ("AT_RISK", "At risk"),
                    ("CRITICAL", "Critical"),
                ],
                default="AUTO",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="timezone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="visibility",
            field=models.CharField(
                choices=[("WORKSPACE", "Workspace"), ("PRIVATE", "Private")],
                default="WORKSPACE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="code",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="project",
            name="default_view",
            field=models.CharField(
                choices=[
                    ("SCHEDULE", "Schedule"),
                    ("BOARD", "Board"),
                    ("TABLE", "Table"),
                    ("OVERVIEW", "Overview"),
                ],
                default="SCHEDULE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="health",
            field=models.CharField(
                choices=[
                    ("AUTO", "Auto"),
                    ("ON_TRACK", "On track"),
                    ("AT_RISK", "At risk"),
                    ("CRITICAL", "Critical"),
                ],
                default="AUTO",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="timezone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="project",
            name="visibility",
            field=models.CharField(
                choices=[("WORKSPACE", "Workspace"), ("PRIVATE", "Private")],
                default="WORKSPACE",
                max_length=16,
            ),
        ),
    ]
