# Generated by Django 6.0.3 on 2026-05-21 23:44

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0041_ceremony_template_and_phase_gate_config"),
        ("projects", "0041_project_general_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Phase accent color as #RRGGBB hex (root tasks only).",
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Phase accent color as #RRGGBB hex (root tasks only).",
                max_length=7,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProjectCustomField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("DATE", "Date"),
                            ("SINGLE_SELECT", "Single-select"),
                            ("MULTI_SELECT", "Multi-select"),
                            ("USER", "Person"),
                            ("BOOLEAN", "Boolean"),
                        ],
                        max_length=16,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("options", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveSmallIntegerField(db_index=True, default=0)),
                ("server_version", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project custom field",
                "verbose_name_plural": "project custom fields",
                "db_table": "projects_projectcustomfield",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["project", "order"], name="projects_pr_project_86613d_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("project"),
                        name="unique_custom_field_name_per_project_ci",
                    )
                ],
            },
        ),
    ]
