# Generated by Django 6.0.3 on 2026-05-22 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0041_ceremony_template_and_phase_gate_config"),
        ("projects", "0041_project_general_fields"),
    ]

    operations = []
