# Generated by Django 5.2.14 on 2026-05-23 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0044_project_archive_program_close"),
        ("projects", "0045_program_risk_policy"),
    ]

    operations = []
