# Generated by Django 6.0.3 on 2026-05-24 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0046_merge_20260523_2248"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apitokenauditentry",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_token_audit",
                to="projects.program",
            ),
        ),
        migrations.AlterField(
            model_name="apitokenauditentry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_token_audit",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="apitokenauditentry",
            index=models.Index(fields=["program", "-created_at"], name="api_token_audit_prog_idx"),
        ),
        migrations.AddConstraint(
            model_name="apitokenauditentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("program__isnull", True), ("project__isnull", False)),
                    models.Q(("program__isnull", False), ("project__isnull", True)),
                    _connector="OR",
                ),
                name="api_token_audit_scope_xor",
            ),
        ),
    ]
