# Generated by Django 5.2.14 on 2026-05-25 20:40

import django.core.validators
from django.db import migrations, models

import trueppm_api.apps.projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0047_apitokenauditentry_program_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="working_days",
            field=models.SmallIntegerField(
                default=31,
                help_text="Bitmask: Mon=1, Tue=2, Wed=4, Thu=8, Fri=16, Sat=32, Sun=64",
                validators=[trueppm_api.apps.projects.models.validate_working_day_mask],
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="lag",
            field=models.IntegerField(
                default=0,
                help_text="Lag in calendar days (positive = delay, negative = lead)",
                validators=[
                    django.core.validators.MinValueValidator(-36525),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicaldependency",
            name="lag",
            field=models.IntegerField(
                default=0,
                help_text="Lag in calendar days (positive = delay, negative = lead)",
                validators=[
                    django.core.validators.MinValueValidator(-36525),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="duration",
            field=models.IntegerField(
                default=1,
                help_text="Duration in working days",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="most_likely_duration",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="optimistic_duration",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="pessimistic_duration",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="duration",
            field=models.IntegerField(
                default=1,
                help_text="Duration in working days",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="most_likely_duration",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="optimistic_duration",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="pessimistic_duration",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
    ]
