# Generated by Django 5.2.14 on 2026-05-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0047_apitokenauditentry_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Program accent color as #RRGGBB hex, or null when unset.",
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Program accent color as #RRGGBB hex, or null when unset.",
                max_length=7,
                null=True,
            ),
        ),
    ]
