# Generated by Django 5.2.14 on 2026-05-25 20:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0048_historicalprogram_color_program_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BacklogItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("epic", "Epic"),
                            ("feature", "Feature"),
                            ("story", "Story"),
                            ("task", "Task"),
                        ],
                        default="task",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("pulled", "Pulled"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("priority_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("story_points", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("pulled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlog_items",
                        to="projects.program",
                    ),
                ),
                (
                    "pulled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pulled_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_backlog_item",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_backlog_item",
                "ordering": ["priority_rank", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["program", "status"], name="projects_ba_program_d5df01_idx"
                    )
                ],
            },
        ),
    ]
