# Generated by Django 5.2.14 on 2026-05-25 20:42
#
# Backlog trigram search (#739). Enables the pg_trgm extension and adds a GIN
# trigram index on BacklogItem.title for fuzzy `?q=` search. TrigramExtension
# MUST precede AddIndex — the gin_trgm_ops operator class does not exist until
# the extension is created. Additive only (extension + index); no data change.

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0049_backlog_item"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="backlogitem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="backlogitem_title_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
