# Generated by Django 5.2.14 on 2026-05-26 17:52

import datetime
import uuid

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0051_alter_calendar_working_days_alter_dependency_lag_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="is_recurring",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="recurrence_occurrence_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="is_recurring",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_occurrence_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HistoricalTaskRecurrenceRule",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="WEEKLY",
                        max_length=8,
                    ),
                ),
                (
                    "interval",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "weekdays",
                    models.SmallIntegerField(
                        default=0, help_text="Weekly only: bitmask Mon=1 … Sun=64."
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        default=datetime.time(9, 0),
                        help_text="Local time the occurrence is due (morning-notification slot).",
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "end_type",
                    models.CharField(
                        choices=[
                            ("NEVER", "Never"),
                            ("ON_DATE", "On date"),
                            ("AFTER_N", "After N occurrences"),
                        ],
                        default="NEVER",
                        max_length=8,
                    ),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("end_count", models.PositiveIntegerField(blank=True, null=True)),
                ("inherit_assignee", models.BooleanField(default=True)),
                ("inherit_subtasks", models.BooleanField(default=False)),
                ("inherit_attachments", models.BooleanField(default=False)),
                ("inherit_morning_notification", models.BooleanField(default=False)),
                ("generated_through", models.DateField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The template task this rule recurs from.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical task recurrence rule",
                "verbose_name_plural": "historical task recurrence rules",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TaskRecurrenceRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="WEEKLY",
                        max_length=8,
                    ),
                ),
                (
                    "interval",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "weekdays",
                    models.SmallIntegerField(
                        default=0, help_text="Weekly only: bitmask Mon=1 … Sun=64."
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        default=datetime.time(9, 0),
                        help_text="Local time the occurrence is due (morning-notification slot).",
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "end_type",
                    models.CharField(
                        choices=[
                            ("NEVER", "Never"),
                            ("ON_DATE", "On date"),
                            ("AFTER_N", "After N occurrences"),
                        ],
                        default="NEVER",
                        max_length=8,
                    ),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("end_count", models.PositiveIntegerField(blank=True, null=True)),
                ("inherit_assignee", models.BooleanField(default=True)),
                ("inherit_subtasks", models.BooleanField(default=False)),
                ("inherit_attachments", models.BooleanField(default=False)),
                ("inherit_morning_notification", models.BooleanField(default=False)),
                ("generated_through", models.DateField(blank=True, null=True)),
                (
                    "task",
                    models.OneToOneField(
                        help_text="The template task this rule recurs from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_taskrecurrencerule",
                "ordering": ["task_id"],
            },
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="recurrence_rule",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.taskrecurrencerule",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="projects.taskrecurrencerule",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("recurrence_rule", "recurrence_occurrence_date"),
                name="unique_recurrence_occurrence_per_date",
            ),
        ),
    ]
