# Generated by Django 5.2.14 on 2026-05-29 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0052_recurring_tasks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dependency",
            index=models.Index(
                fields=["predecessor", "server_version"], name="dep_pred_serverver_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retroactionitem",
            index=models.Index(fields=["retro", "server_version"], name="rai_retro_serverver_idx"),
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(
                fields=["project", "server_version"], name="risk_proj_serverver_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["project", "server_version"], name="sprint_proj_serverver_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprintretro",
            index=models.Index(
                fields=["sprint", "server_version"], name="retro_sprint_serverver_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "server_version"], name="task_proj_serverver_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskrecurrencerule",
            index=models.Index(fields=["task", "server_version"], name="trr_task_serverver_idx"),
        ),
        migrations.AddIndex(
            model_name="tasksuggestedassignee",
            index=models.Index(fields=["task", "server_version"], name="tsa_task_serverver_idx"),
        ),
    ]
