# Generated by Django 5.2.14 on 2026-05-31 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0054_sprintscopechange_goal_impact_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="sprint_pending",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="sprintcloserequest",
            name="pending_disposition",
            field=models.CharField(
                default="carry",
                help_text="'carry' (default) or 'reject' — pending-scope disposition at close.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="sprintscopechange",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending acceptance"),
                    ("accepted", "Accepted into commitment"),
                    ("rejected", "Rejected — removed from sprint"),
                ],
                db_index=True,
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="sprint_pending",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="sprintscopechange",
            index=models.Index(fields=["sprint", "status"], name="scope_change_sprint_status_idx"),
        ),
    ]
