# Generated by Django 5.2.14 on 2026-06-02 12:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0055_historicaltask_sprint_pending_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="prioritization_model",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("wsjf", "WSJF"),
                    ("rice", "RICE"),
                    ("value_effort", "Value / Effort"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="business_value",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="dor",
            field=models.CharField(
                choices=[("idea", "Idea"), ("refine", "Refine"), ("ready", "Ready")],
                db_index=True,
                default="idea",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="effort",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="effort_estimate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="impact",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="job_size",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="parent_epic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.task",
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="reach",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="risk_reduction",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="sprint_rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="time_criticality",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="type",
            field=models.CharField(
                choices=[
                    ("epic", "Epic"),
                    ("story", "Story"),
                    ("task", "Task"),
                    ("bug", "Bug"),
                    ("spike", "Spike"),
                ],
                db_index=True,
                default="task",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="value",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="prioritization_model",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("wsjf", "WSJF"),
                    ("rice", "RICE"),
                    ("value_effort", "Value / Effort"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="business_value",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="dor",
            field=models.CharField(
                choices=[("idea", "Idea"), ("refine", "Refine"), ("ready", "Ready")],
                db_index=True,
                default="idea",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="effort",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="effort_estimate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="impact",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="job_size",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_epic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="epic_children",
                to="projects.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reach",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="risk_reduction",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="sprint_rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="time_criticality",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("epic", "Epic"),
                    ("story", "Story"),
                    ("task", "Task"),
                    ("bug", "Bug"),
                    ("spike", "Spike"),
                ],
                db_index=True,
                default="task",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="value",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AcceptanceCriterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("text", models.CharField(max_length=1000)),
                ("given", models.CharField(blank=True, default="", max_length=1000)),
                ("when", models.CharField(blank=True, default="", max_length=1000)),
                ("then", models.CharField(blank=True, default="", max_length=1000)),
                ("met", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("met_at", models.DateTimeField(blank=True, null=True)),
                (
                    "met_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptance_criteria",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_acceptance_criterion",
                "ordering": ["task", "position"],
                "indexes": [
                    models.Index(fields=["task", "position"], name="projects_ac_task_id_ced5cf_idx")
                ],
            },
        ),
    ]
