# Generated by Django 5.2.14 on 2026-06-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0057_historicalsprint_binding_committed_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="delivery_mode",
            field=models.CharField(
                choices=[
                    ("waterfall", "Waterfall"),
                    ("scrum", "Scrum"),
                    ("kanban", "Kanban"),
                    ("milestone", "Milestone"),
                ],
                db_index=True,
                default="waterfall",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="governance_class",
            field=models.CharField(
                choices=[("gated", "Gated"), ("flow", "Flow"), ("hybrid", "Hybrid")],
                db_index=True,
                default="flow",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="parent_governance_inherited",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="task",
            name="delivery_mode",
            field=models.CharField(
                choices=[
                    ("waterfall", "Waterfall"),
                    ("scrum", "Scrum"),
                    ("kanban", "Kanban"),
                    ("milestone", "Milestone"),
                ],
                db_index=True,
                default="waterfall",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="governance_class",
            field=models.CharField(
                choices=[("gated", "Gated"), ("flow", "Flow"), ("hybrid", "Hybrid")],
                db_index=True,
                default="flow",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_governance_inherited",
            field=models.BooleanField(default=True),
        ),
    ]
