# Generated by Django 5.2.14 on 2026-06-05 16:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0058_historicaltask_delivery_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("monte_carlo", "Monte Carlo"),
                            ("velocity_band", "Velocity band"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cpm_finish", models.DateField(blank=True, null=True)),
                ("p50", models.DateField(blank=True, null=True)),
                ("p80", models.DateField(blank=True, null=True)),
                ("velocity_low", models.PositiveIntegerField(blank=True, null=True)),
                ("velocity_high", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "confidence",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        max_length=10,
                    ),
                ),
                ("unmodeled_dependency", models.BooleanField(default=False)),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forecast_snapshots",
                        to="projects.task",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_snapshots",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_forecastsnapshot",
                "ordering": ["-taken_at"],
                "indexes": [
                    models.Index(
                        fields=["milestone", "-taken_at"], name="forecast_milestone_recent_idx"
                    ),
                    models.Index(
                        fields=["project", "-taken_at"], name="forecast_project_recent_idx"
                    ),
                ],
            },
        ),
    ]
