# Generated by Django 5.2.14 on 2026-06-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0060_historicalprojectsignalprivacypolicy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselinetask",
            name="story_points",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
