# Generated by Django 5.2.14 on 2026-06-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0061_baselinetask_story_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="is_sample",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="is_sample",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
