# Generated by Django 5.2.14 on 2026-06-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0062_project_is_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsprint",
            name="wip_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sprint",
            name="wip_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
