# Generated by Django 5.2.14 on 2026-06-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0062_project_is_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="iteration_label",
            field=models.CharField(default="Sprint", max_length=32),
        ),
        migrations.AddField(
            model_name="project",
            name="iteration_label",
            field=models.CharField(default="Sprint", max_length=32),
        ),
    ]
