# Generated by Django 5.2.14 on 2026-06-09 15:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0063_historicalsprint_wip_limit_sprint_wip_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="SprintTaskOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("task_short_id", models.CharField(max_length=12)),
                ("task_title", models.CharField(max_length=512)),
                ("story_points", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "final_status",
                    models.CharField(
                        choices=[
                            ("BACKLOG", "Backlog"),
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("REVIEW", "Review"),
                            ("ON_HOLD", "On hold"),
                            ("COMPLETE", "Complete"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("completed", "Completed in sprint"),
                            ("carried", "Carried to another sprint"),
                            ("dropped", "Dropped (not carried forward)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("was_pending", models.BooleanField(default=False)),
                ("backfilled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "next_sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="projects.sprint",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_outcomes",
                        to="projects.sprint",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sprint_outcomes",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_sprinttaskoutcome",
                "ordering": ["sprint_id", "task_short_id"],
                "indexes": [
                    models.Index(fields=["sprint", "disposition"], name="sprint_outcome_disp_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sprint", "task"), name="uniq_sprint_task_outcome"
                    )
                ],
            },
        ),
    ]
