# Generated by Django 5.2.14 on 2026-06-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0064_sprinttaskoutcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsprint",
            name="goal_outcome",
            field=models.CharField(
                blank=True,
                choices=[("MET", "Met"), ("PARTIAL", "Partially met"), ("MISSED", "Missed")],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sprint",
            name="goal_outcome",
            field=models.CharField(
                blank=True,
                choices=[("MET", "Met"), ("PARTIAL", "Partially met"), ("MISSED", "Missed")],
                max_length=12,
                null=True,
            ),
        ),
    ]
