# Generated by Django 5.2.14 on 2026-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_historicalproject_lead_project_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsprint',
            name='exclude_from_velocity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprint',
            name='exclude_from_velocity',
            field=models.BooleanField(default=False),
        ),
    ]
