# Generated by Django 5.2.14 on 2026-06-11 11:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0069_iteration_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("mood", models.PositiveSmallIntegerField()),
                ("energy", models.PositiveSmallIntegerField()),
                ("confidence", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "respondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retro_pulse_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pulse_responses",
                        to="projects.sprintretro",
                    ),
                ),
            ],
            options={
                "db_table": "projects_pulseresponse",
                "indexes": [
                    models.Index(
                        fields=["retro", "server_version"], name="pulse_retro_serverver_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("retro", "respondent"),
                        name="uniq_pulse_retro_respondent_live",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RetroBoardItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "column",
                    models.CharField(
                        choices=[
                            ("went_well", "What went well"),
                            ("to_improve", "What to improve"),
                            ("ideas", "Ideas & discussion"),
                        ],
                        default="went_well",
                        max_length=12,
                    ),
                ),
                ("text", models.TextField()),
                ("position", models.FloatField(default=0.0)),
                ("color", models.CharField(blank=True, default="", max_length=16)),
                ("converted_action_item_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retro_board_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_items",
                        to="projects.sprintretro",
                    ),
                ),
            ],
            options={
                "db_table": "projects_retroboarditem",
                "ordering": ["column", "position", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["retro", "column", "position"], name="rbi_retro_col_pos_idx"
                    ),
                    models.Index(
                        fields=["retro", "server_version"], name="rbi_retro_serverver_idx"
                    ),
                ],
            },
        ),
    ]
