# Generated by Django 5.2.14 on 2026-06-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0069_iteration_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="iteration_label",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="iteration_label",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="iteration_label",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="iteration_label",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
