# Generated by Django 5.2.14 on 2026-06-11 22:25
#
# #929 — move Risk short_ids off the shared hex object_sequence onto a dedicated
# decimal risk_sequence, then backfill existing risks to contiguous decimal IDs.

from typing import Any

from django.db import migrations, models
from django.db.models import F


def backfill_risk_short_ids(apps: Any, schema_editor: Any) -> None:
    """Renumber existing risks to a contiguous decimal sequence per project (#929).

    Existing risks carry 8-char hex short_ids allocated from the shared
    ``object_sequence`` — the bug behind every register row collapsing to
    ``R-0000``. For each project, order *all* risks (including soft-deleted ones)
    by ``created_at`` and assign ``1, 2, 3 …`` as the new decimal ``short_id``,
    then set ``project.risk_sequence`` to the high-water mark so new risks never
    reuse a number.

    Soft-deleted risks are included in the ordering on purpose: the VoC panel
    required immutability with *no reuse after deletion* (deletion leaves a gap —
    "where is R-8?" is an expected audit finding, not a bug). Numbering only the
    live rows would silently re-pack the sequence and reuse a dead risk's number.

    ``server_version`` is bumped on every renumbered risk so offline/mobile
    clients re-pull the corrected identifier on their next sync delta. The writes
    use bulk ``.update()`` / ``bulk_update()`` — a one-time data correction, not
    an audited user edit, so they intentionally leave no HistoricalRisk rows
    (matching the 0071 backfill precedent).
    """
    Project = apps.get_model("projects", "Project")
    Risk = apps.get_model("projects", "Risk")

    for project_id in Project.objects.values_list("pk", flat=True):
        risks = list(Risk.objects.filter(project_id=project_id).order_by("created_at", "pk"))
        if not risks:
            continue

        # Two-pass renumber. ``unique_risk_short_id_per_project`` is a plain
        # (non-deferrable) UniqueConstraint, so Postgres checks it per-row inside
        # the bulk UPDATE. Writing the final decimals in one pass is only safe
        # because legacy hex short_ids can't equal a bare decimal — but a
        # mixed-version deploy window (new app code minting decimal short_ids
        # before this migration runs) could break that assumption and abort the
        # migration with an IntegrityError. Routing through a sentinel namespace
        # that is disjoint from BOTH legacy hex (uppercase ``[0-9A-F]``) and the
        # final decimals (the lowercase ``x`` prefix guarantees this) makes the
        # renumber collision-proof regardless of the starting values.
        for seq, risk in enumerate(risks, start=1):
            risk.short_id = f"x{seq:07d}"
        Risk.objects.bulk_update(risks, ["short_id"], batch_size=2000)
        for seq, risk in enumerate(risks, start=1):
            risk.short_id = str(seq)
        Risk.objects.bulk_update(risks, ["short_id"], batch_size=2000)

        # Bump server_version so sync clients see the changed short_id. Done as a
        # single bulk UPDATE per project rather than per-row save().
        Risk.objects.filter(project_id=project_id).update(server_version=F("server_version") + 1)
        Project.objects.filter(pk=project_id).update(risk_sequence=len(risks))


def reverse_backfill(apps: Any, schema_editor: Any) -> None:
    """Irreversible data correction — the original hex short_ids are not recoverable.

    The schema change (dropping ``risk_sequence``) is reversed by Django; the
    decimal short_ids are left as-is. They remain valid, unique-per-project
    identifiers, so a downgrade is non-destructive even though it cannot restore
    the old hex values (which were broken anyway).
    """
    # No-op: see docstring. New risks created after a downgrade would fall back to
    # the shared hex counter via the reverted model code.


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0072_pulseresponse_retroboarditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="risk_sequence",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="project",
            name="risk_sequence",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(backfill_risk_short_ids, reverse_backfill),
    ]
