# Generated by Django 5.2.14 on 2026-06-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0072_pulseresponse_retroboarditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="blocked_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why the task is blocked; empty means not blocked.",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="blocked_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why the task is blocked; empty means not blocked.",
            ),
        ),
    ]
