# Generated by Django 5.2.14 on 2026-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0072_pulseresponse_retroboarditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprinttaskoutcome",
            name="demo_ready",
            field=models.BooleanField(default=False),
        ),
    ]
