# Generated by Django 5.2.14 on 2026-06-11 22:25
#
# #929 — move Risk short_ids off the shared hex object_sequence onto a dedicated
# decimal risk_sequence, then backfill existing risks to contiguous decimal IDs.

from typing import Any

from django.db import migrations, models

from trueppm_api.apps.projects.backfill import backfill_risk_short_ids


def reverse_backfill(apps: Any, schema_editor: Any) -> None:
    """Irreversible data correction — the original hex short_ids are not recoverable.

    The schema change (dropping ``risk_sequence``) is reversed by Django; the
    decimal short_ids are left as-is. They remain valid, unique-per-project
    identifiers, so a downgrade is non-destructive even though it cannot restore
    the old hex values (which were broken anyway).
    """
    # No-op: see docstring. New risks created after a downgrade would fall back to
    # the shared hex counter via the reverted model code.


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0074_historicaltask_blocked_reason_task_blocked_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="risk_sequence",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="project",
            name="risk_sequence",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(backfill_risk_short_ids, reverse_backfill, elidable=True),
    ]
