# Generated by Django 5.2.14 on 2026-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0077_task_blocker_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="risktask",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="risktask",
            constraint=models.UniqueConstraint(
                fields=("risk", "task"), name="uniq_risk_task_risk_task"
            ),
        ),
    ]
