# Generated by Django 5.2.14 on 2026-06-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0078_alter_risktask_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="status_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
