# Generated by Django 5.2.14 on 2026-06-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0079_historicalproject_status_date_project_status_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="allow_guests",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprogram",
            name="public_sharing",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="allow_guests",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="public_sharing",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="allow_guests",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="public_sharing",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="allow_guests",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="public_sharing",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
