# Generated by Django 5.2.14 on 2026-06-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0079_historicalproject_status_date_project_status_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltask",
            name="type",
            field=models.CharField(
                choices=[
                    ("epic", "Epic"),
                    ("story", "Story"),
                    ("task", "Task"),
                    ("bug", "Bug"),
                    ("spike", "Spike"),
                    ("tech_debt", "Tech Debt"),
                ],
                db_index=True,
                default="task",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("epic", "Epic"),
                    ("story", "Story"),
                    ("task", "Task"),
                    ("bug", "Bug"),
                    ("spike", "Spike"),
                    ("tech_debt", "Tech Debt"),
                ],
                db_index=True,
                default="task",
                max_length=16,
            ),
        ),
    ]
