# Generated by Django 5.2.14 on 2026-06-16 19:55
# Hand-edited to add the data back-fill (ADR-0142, #822).

from typing import Any

from django.db import migrations, models

# Per-project sync watermark — a verbatim copy of
# ``ProjectSyncView._snapshot_max_version``'s 12-table UNION ALL. Embedded here
# (not imported from app code) so the migration stays correct even if the view
# query later changes; the back-filled value provably equals the union the column
# replaces. Dependencies are tracked via the predecessor task's server_version,
# exactly as the live query does.
_WATERMARK_UNION = """
    SELECT COALESCE(MAX(v), 0) FROM (
        SELECT MAX(server_version) AS v
          FROM projects_project WHERE id = %(pk)s
        UNION ALL
        SELECT MAX(server_version) FROM projects_task WHERE project_id = %(pk)s
        UNION ALL
        SELECT MAX(t.server_version)
          FROM projects_dependency d
          JOIN projects_task t ON d.predecessor_id = t.id
         WHERE t.project_id = %(pk)s
        UNION ALL
        SELECT MAX(server_version) FROM projects_calendar WHERE id = (
            SELECT calendar_id FROM projects_project WHERE id = %(pk)s
        )
        UNION ALL
        SELECT MAX(server_version)
          FROM access_project_membership WHERE project_id = %(pk)s
        UNION ALL
        SELECT MAX(server_version) FROM projects_risk WHERE project_id = %(pk)s
        UNION ALL
        SELECT MAX(server_version) FROM projects_sprint WHERE project_id = %(pk)s
        UNION ALL
        SELECT MAX(r.server_version)
          FROM projects_sprintretro r
          JOIN projects_sprint s ON r.sprint_id = s.id
         WHERE s.project_id = %(pk)s
        UNION ALL
        SELECT MAX(a.server_version)
          FROM projects_retroactionitem a
          JOIN projects_sprintretro r ON a.retro_id = r.id
          JOIN projects_sprint s ON r.sprint_id = s.id
         WHERE s.project_id = %(pk)s
        UNION ALL
        SELECT MAX(sa.server_version)
          FROM projects_tasksuggestedassignee sa
          JOIN projects_task t ON sa.task_id = t.id
         WHERE t.project_id = %(pk)s
        UNION ALL
        SELECT MAX(tl.server_version)
          FROM integrations_tasklink tl
          JOIN projects_task t ON tl.task_id = t.id
         WHERE t.project_id = %(pk)s
        UNION ALL
        SELECT MAX(rr.server_version)
          FROM projects_taskrecurrencerule rr
          JOIN projects_task t ON rr.task_id = t.id
         WHERE t.project_id = %(pk)s
    ) sub
"""


def _backfill(apps: Any, schema_editor: Any) -> None:
    """Set last_sync_version = the union watermark for every existing project."""
    Project = apps.get_model("projects", "Project")
    connection = schema_editor.connection
    ids = list(Project.objects.values_list("pk", flat=True))
    with connection.cursor() as cursor:
        for pk in ids:
            cursor.execute(_WATERMARK_UNION, {"pk": str(pk)})
            (value,) = cursor.fetchone()
            Project.objects.filter(pk=pk).update(last_sync_version=value or 0)


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0081_historicalprogram_allow_guests_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_sync_version",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(_backfill, migrations.RunPython.noop, elidable=True),
    ]
