# Generated by Django 5.2.14 on 2026-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0082_project_last_sync_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="mc_history_attribution_audience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin_owner", "Admins and Owners"),
                    ("scheduler_plus", "Schedulers and above"),
                    ("none", "No one"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalprogram",
            name="mc_history_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprogram",
            name="mc_history_retention_cap",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="mc_history_attribution_audience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin_owner", "Admins and Owners"),
                    ("scheduler_plus", "Schedulers and above"),
                    ("none", "No one"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="mc_history_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="mc_history_retention_cap",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="mc_history_attribution_audience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin_owner", "Admins and Owners"),
                    ("scheduler_plus", "Schedulers and above"),
                    ("none", "No one"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="mc_history_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="mc_history_retention_cap",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="mc_history_attribution_audience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin_owner", "Admins and Owners"),
                    ("scheduler_plus", "Schedulers and above"),
                    ("none", "No one"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mc_history_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="mc_history_retention_cap",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
