# Generated by Django 5.2.14 on 2026-06-19 12:56
#
# Board card full-text search (#323, ADR-0145). Adds gin_trgm_ops GIN indexes on
# Task.name and Task.notes so the board `?q=` search's `ILIKE '%q%'` runs as an
# index scan instead of a per-row seq-scan. The pg_trgm extension is already
# enabled by 0050_backlog_item_trgm_search, so no TrigramExtension op is needed
# here. Additive only (two indexes); no data change, online-safe AddIndex.

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0085_sprint_ix_sprint_velocity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="task_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["notes"], name="task_notes_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
