# Generated by Django 5.2.14 on 2026-06-20 16:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0086_board_card_search_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="task_duration_change_percent_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("keep", "Keep percent-complete"),
                    ("prorate", "Prorate percent-complete"),
                    ("confirm", "Confirm percent-complete (client prompt)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="task_duration_change_percent_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("keep", "Keep percent-complete"),
                    ("prorate", "Prorate percent-complete"),
                    ("confirm", "Confirm percent-complete (client prompt)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="task_duration_change_percent_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("keep", "Keep percent-complete"),
                    ("prorate", "Prorate percent-complete"),
                    ("confirm", "Confirm percent-complete (client prompt)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="task_duration_change_percent_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("keep", "Keep percent-complete"),
                    ("prorate", "Prorate percent-complete"),
                    ("confirm", "Confirm percent-complete (client prompt)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TaskDurationChangeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "old_duration",
                    models.IntegerField(help_text="Working-day duration before the change."),
                ),
                (
                    "new_duration",
                    models.IntegerField(help_text="Working-day duration after the change."),
                ),
                (
                    "percent_complete_at_change",
                    models.FloatField(
                        help_text="percent_complete immediately before the duration changed."
                    ),
                ),
                ("percent_complete_after", models.FloatField(blank=True, null=True)),
                (
                    "policy_applied",
                    models.CharField(
                        choices=[
                            ("keep", "Keep percent-complete"),
                            ("prorate", "Prorate percent-complete"),
                            ("confirm", "Confirm percent-complete (client prompt)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("user_edit", "User edit"), ("cpm_cascade", "CPM cascade")],
                        default="user_edit",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who changed the duration. NULL for automated sources.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="projects.sprint",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duration_change_events",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_task_duration_change_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["task", "-created_at"], name="task_dur_evt_task_idx")
                ],
            },
        ),
    ]
