# Generated by Django 5.2.14 on 2026-06-20 15:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0087_historicalprogram_task_duration_change_percent_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="allowed_attachment_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="historicalprogram",
            name="attachments_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="allowed_attachment_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="attachments_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="allowed_attachment_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="attachments_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="allowed_attachment_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="attachments_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
