# Generated by Django 5.2.14 on 2026-06-21 21:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0088_historicalprogram_allowed_attachment_types_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalCeilingRaiseProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("signal_key", models.CharField(max_length=64)),
                (
                    "from_ceiling",
                    models.CharField(
                        choices=[
                            ("team", "Team only"),
                            ("team_sm", "Team + Scrum Master"),
                            ("team_sm_pm", "Team + SM + PM"),
                            ("program_shared", "Shared to program rollup (opt-in)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_ceiling",
                    models.CharField(
                        choices=[
                            ("team", "Team only"),
                            ("team_sm", "Team + Scrum Master"),
                            ("team_sm_pm", "Team + SM + PM"),
                            ("program_shared", "Shared to program rollup (opt-in)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open for ratification"),
                            ("ratified", "Ratified — raise applied"),
                            ("rejected", "Rejected by the team"),
                            ("expired", "Expired unratified"),
                            ("superseded", "Superseded by a ceiling change"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_ceiling_proposals",
                        to="projects.project",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signal_ceiling_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_signal_ceiling_proposal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignalCeilingRaiseVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("approve", "Approve the raise"), ("reject", "Reject the raise")],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="projects.signalceilingraiseproposal",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_ceiling_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_signal_ceiling_vote",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="signalceilingraiseproposal",
            index=models.Index(
                fields=["project", "signal_key", "status"], name="crp_proj_signal_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="signalceilingraiseproposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("project", "signal_key"),
                name="crp_one_open_per_signal",
            ),
        ),
        migrations.AddIndex(
            model_name="signalceilingraisevote",
            index=models.Index(fields=["proposal", "choice"], name="crv_proposal_choice_idx"),
        ),
        migrations.AddConstraint(
            model_name="signalceilingraisevote",
            constraint=models.UniqueConstraint(
                fields=("proposal", "voter"), name="crv_one_vote_per_member"
            ),
        ),
    ]
