"""Composite (project_id, history_date) index on the HistoricalTask table.

The board activity feed (ADR-0160) and the `burn_series` / `sprint_daily_delta`
services all scan `HistoricalTask.objects.filter(project_id=X, history_date__lt=…)`,
but the table carries only single-column indexes (FK on `project_id`, `db_index` on
`history_date`) — so Postgres leads on the FK index and filters/sorts in a second pass.
This adds the covering composite index (ADR-0160 Amendment B2, closes #1189).

Two constraints shape the mechanism:

* ``CREATE INDEX CONCURRENTLY`` cannot run inside a transaction → ``atomic = False`` (so the
  reverse ``DROP INDEX CONCURRENTLY`` is non-transactional too). Non-locking, so safe on a
  live table.
* The historical model is auto-generated by django-simple-history and does **not** declare
  this index in its ``Meta``. Adding it to Django's migration *state* would therefore make
  ``makemigrations --check`` demand a ``RemoveIndex`` on the next run. We add it DB-side only
  via raw ``RunSQL`` (no ``state_operations``) — Django never needs to reference a pure perf
  index. ``IF NOT EXISTS`` / ``IF EXISTS`` keep both directions idempotent (safe on a reused
  test DB and on re-run). This is the repo's first concurrent-index migration.

A leading ``RunPython`` repairs an INVALID index left by a prior interrupted
``CONCURRENTLY`` build (``migrate_locked``'s lock-holding pod dying mid-build, #4357)
before the ``IF NOT EXISTS`` build below would otherwise silently skip rebuilding it.
Editing this already-applied migration is safe: the repair is a no-op on every
database where this migration already succeeded cleanly, and only changes behavior on
a *rerun* of an unapplied copy of this exact migration, which only happens after the
crash this fixes. The squashed copy of this build in
``0001_squashed_0094_project_decisions_policy`` does not need the same repair — see
that squash's comment and ``test_squash_data_op_parity.py``'s ``EXEMPT`` entry: the
squash runs the plain (non-``CONCURRENTLY``), fully atomic version on a fresh install,
where an interrupted build rolls back entirely rather than leaving an INVALID index.
"""

from __future__ import annotations

from django.db import migrations

from trueppm_api.apps.projects.migration_helpers import repair_invalid_concurrent_index_op

_INDEX_NAME = "htask_proj_hist_date_idx"


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("projects", "0089_signalceilingraiseproposal_signalceilingraisevote_and_more"),
    ]

    operations = [
        repair_invalid_concurrent_index_op(_INDEX_NAME),
        migrations.RunSQL(
            sql=(
                f"CREATE INDEX CONCURRENTLY IF NOT EXISTS {_INDEX_NAME} "
                "ON projects_historicaltask (project_id, history_date);"
            ),
            reverse_sql=f"DROP INDEX CONCURRENTLY IF EXISTS {_INDEX_NAME};",
        ),
    ]
