"""Composite (project_id, history_date) index on the HistoricalTask table.

The board activity feed (ADR-0160) and the `burn_series` / `sprint_daily_delta`
services all scan `HistoricalTask.objects.filter(project_id=X, history_date__lt=…)`,
but the table carries only single-column indexes (FK on `project_id`, `db_index` on
`history_date`) — so Postgres leads on the FK index and filters/sorts in a second pass.
This adds the covering composite index (ADR-0160 Amendment B2, closes #1189).

Two constraints shape the mechanism:

* ``CREATE INDEX CONCURRENTLY`` cannot run inside a transaction → ``atomic = False`` (so the
  reverse ``DROP INDEX CONCURRENTLY`` is non-transactional too). Non-locking, so safe on a
  live table.
* The historical model is auto-generated by django-simple-history and does **not** declare
  this index in its ``Meta``. Adding it to Django's migration *state* would therefore make
  ``makemigrations --check`` demand a ``RemoveIndex`` on the next run. We add it DB-side only
  via raw ``RunSQL`` (no ``state_operations``) — Django never needs to reference a pure perf
  index. ``IF NOT EXISTS`` / ``IF EXISTS`` keep both directions idempotent (safe on a reused
  test DB and on re-run). This is the repo's first concurrent-index migration.
"""

from __future__ import annotations

from django.db import migrations

_INDEX_NAME = "htask_proj_hist_date_idx"


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("projects", "0089_signalceilingraiseproposal_signalceilingraisevote_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                f"CREATE INDEX CONCURRENTLY IF NOT EXISTS {_INDEX_NAME} "
                "ON projects_historicaltask (project_id, history_date);"
            ),
            reverse_sql=f"DROP INDEX CONCURRENTLY IF EXISTS {_INDEX_NAME};",
        ),
    ]
