# Generated by Django 5.2.14 on 2026-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0091_project_board_cadence"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
