# Generated by Django 5.2.14 on 2026-06-23 20:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0094_project_decisions_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PokerSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open for voting"),
                            ("revealed", "Revealed"),
                            ("committed", "Committed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("committed_points", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poker_sessions",
                        to="projects.sprint",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_poker_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poker_sessions",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_poker_session",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PokerVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("value", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, default="", max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="projects.pokersession",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poker_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_poker_vote",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pokersession",
            index=models.Index(fields=["sprint", "state"], name="poker_sprint_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="pokersession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["open", "revealed"])),
                fields=("task",),
                name="poker_one_live_per_task",
            ),
        ),
        migrations.AddConstraint(
            model_name="pokervote",
            constraint=models.UniqueConstraint(
                fields=("session", "voter"), name="poker_one_vote_per_member"
            ),
        ),
    ]
