# Generated by Django 5.2.14 on 2026-06-25 17:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0095_poker_session_vote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossProjectSlipConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pushed_to", models.DateField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("re_slip_count", models.PositiveIntegerField(default=0)),
                (
                    "resolution",
                    models.CharField(
                        choices=[("unresolved", "Unresolved"), ("auto_resolved", "Auto-resolved")],
                        default="unresolved",
                        max_length=16,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dependency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slip_conflicts",
                        to="projects.dependency",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slip_conflicts",
                        to="projects.sprint",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slip_conflicts",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_crossprojectslipconflict",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["resolution", "acknowledged_at"], name="slip_conflict_open_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sprint", "task"), name="unique_slip_conflict_per_sprint_task"
                    )
                ],
            },
        ),
    ]
