# Generated by Django 5.2.14 on 2026-06-28 16:16

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0096_crossprojectslipconflict"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="backlogitem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tags"], name="backlogitem_tags_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(
                fields=["project", "-impact", "-probability", "title"],
                name="risk_project_register_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(fields=["project", "finish_date"], name="sprint_project_finish_idx"),
        ),
    ]
