# Generated by Django 5.2.14 on 2026-07-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0097_backlogitem_backlogitem_tags_gin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="show_baselines",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="show_monte_carlo",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="show_reporting",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="show_time_tracking",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="show_baselines",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="show_monte_carlo",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="show_reporting",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="show_time_tracking",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
