# Generated by Django 5.2.14 on 2026-07-01 19:16

from typing import Any

import django.contrib.postgres.fields
from django.db import migrations, models

import trueppm_api.apps.projects.models


def backfill_legacy_full_scope(apps: Any, schema_editor: Any) -> None:
    """Set every pre-existing token to the legacy full scope.

    The AddField default already stamps ``[legacy:full]`` onto existing rows,
    but we make the intent explicit and idempotent: any token minted before
    scopes existed keeps its unrestricted behavior, so no in-flight inbound
    integration breaks when this migration lands.
    """
    ApiToken = apps.get_model("projects", "ApiToken")
    ApiToken.objects.filter(scopes=[]).update(scopes=["legacy:full"])


def noop_reverse(apps: Any, schema_editor: Any) -> None:
    """No-op reverse — the column is dropped by the AddField reversal."""


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0098_historicalproject_show_baselines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="scopes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("legacy:full", "legacy:full"), ("mcp:read", "mcp:read")],
                    max_length=64,
                ),
                blank=True,
                default=trueppm_api.apps.projects.models._default_api_token_scopes,
                help_text="Capabilities this token grants. 'legacy:full' is the historical unrestricted scope (and a superset satisfying any read scope); 'mcp:read' grants read-only access to the MCP-wrapped viewsets and is rejected at every write path.",
                size=None,
            ),
        ),
        migrations.RunPython(backfill_legacy_full_scope, noop_reverse),
    ]
