# Generated by Django 5.2.14 on 2026-07-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0100_task_dep_serverver_idx_concurrent"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependency",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
