# Generated by Django 5.2.14 on 2026-07-03 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0101_dependency_deleted_at_task_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_deleted", "deleted_at"], name="proj_isdel_deletedat_idx"
            ),
        ),
    ]
