# Generated by Django 5.2.14 on 2026-07-03 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0102_project_deleted_at_project_proj_isdel_deletedat_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taskdurationchangeevent",
            index=models.Index(fields=["sprint", "-created_at"], name="task_dur_evt_sprint_idx"),
        ),
    ]
