# Generated by Django 5.2.14 on 2026-07-04 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0103_taskdurationchangeevent_task_dur_evt_sprint_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="stale_task_threshold_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="project",
            name="stale_task_threshold_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["project", "status", "status_changed_at"],
                name="task_status_changed_idx",
            ),
        ),
    ]
