"""Composite (project_id, history_date) indexes on HistoricalSprint / HistoricalRisk.

The unified project changelog (ADR-0201, #371) scans each project-scoped
``Historical*`` table with ``filter(project_id=X, history_date <= cursor)
ORDER BY history_date DESC``. ``HistoricalTask`` already has this covering
composite (migration 0090); ``HistoricalSprint`` and ``HistoricalRisk`` are the
other two higher-volume project-FK history tables and carry only single-column
indexes, so Postgres would lead on the ``project_id`` FK index and sort in a
second pass. This adds the covering composite for both.

Same mechanism and constraints as migration 0090:

* ``CREATE INDEX CONCURRENTLY`` cannot run inside a transaction → ``atomic =
  False``. Non-locking, safe on a live table.
* The historical models are auto-generated by django-simple-history and do not
  declare these indexes in ``Meta``; adding them to Django's migration *state*
  would make ``makemigrations --check`` demand a ``RemoveIndex``. We add them
  DB-side only via raw ``RunSQL`` (no ``state_operations``). ``IF NOT EXISTS`` /
  ``IF EXISTS`` keep both directions idempotent (safe on a reused test DB).

The remaining changelog sources need no new index: ``HistoricalProject`` is
filtered by PK and is low-volume; the three policy history tables are singletons
(a handful of rows per project); ``HistoricalDependency`` is join-scoped and
bounded by the per-source page limit.
"""

from __future__ import annotations

from django.db import migrations

_SPRINT_INDEX = "hsprint_proj_hist_date_idx"
_RISK_INDEX = "hrisk_proj_hist_date_idx"


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("projects", "0103_taskdurationchangeevent_task_dur_evt_sprint_idx"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                f"CREATE INDEX CONCURRENTLY IF NOT EXISTS {_SPRINT_INDEX} "
                "ON projects_historicalsprint (project_id, history_date);"
            ),
            reverse_sql=f"DROP INDEX CONCURRENTLY IF EXISTS {_SPRINT_INDEX};",
        ),
        migrations.RunSQL(
            sql=(
                f"CREATE INDEX CONCURRENTLY IF NOT EXISTS {_RISK_INDEX} "
                "ON projects_historicalrisk (project_id, history_date);"
            ),
            reverse_sql=f"DROP INDEX CONCURRENTLY IF EXISTS {_RISK_INDEX};",
        ),
    ]
