# Generated by Django 5.2.14 on 2026-07-04 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0104_historicalproject_stale_task_threshold_days_and_more"),
        ("projects", "0104_trash_restore_1113"),
    ]

    operations = []
