# Generated by Django 5.2.14 on 2026-07-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0104_historicalproject_stale_task_threshold_days_and_more"),
        ("projects", "0104_trash_restore_1113"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardsavedview",
            name="schema_version",
            field=models.IntegerField(
                default=1,
                help_text="Config shape version; upgraded on read via the migration registry (ADR-0086).",
            ),
        ),
    ]
