# Generated by Django 5.2.17 on 2026-10-05 19:50

import importlib
import uuid
from typing import Any

import django.contrib.postgres.constraints
import django.contrib.postgres.fields
import django.core.validators
import django.db.migrations.operations.special
import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import trueppm_api.apps.projects.models


def _original(app: str, module: str, name: str) -> Any:
    """Return a callable from a retained original migration module.

    Django's squashmigrations writes these references as attribute paths, which
    is a SyntaxError when the module name starts with a digit, so they are
    resolved by name here. The original migration files stay on disk (CLAUDE.md
    migration rule 6); a callable may only be deleted from its original module
    after its body is copied into this file.
    """
    # Every call site passes a constant app/module/name from this file, never user input.
    # nosemgrep: python.lang.security.audit.non-literal-import.non-literal-import
    return getattr(importlib.import_module(f"trueppm_api.apps.{app}.migrations.{module}"), name)


# RunPython callables below are resolved from the retained original migrations
# (see _original). Do not delete those originals without copying the callables here.


class Migration(migrations.Migration):
    replaces = [
        ("projects", "0106_boardsavedview_schema_version"),
        ("projects", "0107_task_activity_event"),
        ("projects", "0108_remove_apitoken_api_token_scope_xor_and_more"),
        ("projects", "0109_projectexportjob"),
        ("projects", "0110_sharelink"),
        ("projects", "0111_projectcalendarlayer"),
        ("projects", "0112_sharelink_expires_at_alter_sharelink_content_kind"),
        ("projects", "0113_alter_historicaltask_percent_complete_and_more"),
        ("projects", "0114_historicalproject_default_member_role_and_more"),
        ("projects", "0115_historicalproject_end_date_shift_threshold_days_and_more"),
        ("projects", "0116_alter_taskactivityevent_event_type"),
        ("projects", "0117_label_tasklabel_label_tasks_and_more"),
        ("projects", "0118_programexportjob"),
        ("projects", "0119_historicalprogram_calendar_program_calendar"),
        ("projects", "0120_alter_backlogitem_item_type"),
        ("projects", "0121_task_three_point_estimate_ordered"),
        ("projects", "0122_task_relation"),
        ("projects", "0123_remove_historicalproject_agile_features_and_more"),
        ("projects", "0124_dependency_is_driving"),
        ("projects", "0125_historicalprogram_estimation_scale_and_more"),
        ("projects", "0126_projectcustomfield_show_on_card_taskcustomfieldvalue"),
        ("projects", "0127_historicalprogram_mcp_enabled_and_more"),
        ("projects", "0128_acceptancecriterion_sync_seq_apitoken_sync_seq_and_more"),
        ("projects", "0129_sharelink_show_milestone_dates"),
        ("projects", "0130_programimportjob"),
        ("projects", "0131_historicalprogram_sprint_picker_ready_only_default_and_more"),
        ("projects", "0132_task_scheduled_start"),
        ("projects", "0133_project_status_date_floor_armed_at"),
        ("projects", "0134_task_edited_at_task_seeded_at_task_source_id_and_more"),
        ("projects", "0135_projecttemplate_templateapplication_and_more"),
        ("projects", "0136_schedule_outline_batch_operations"),
        ("projects", "0137_collapse_dual_scope_api_tokens"),
        ("projects", "0138_apitokenauditentry_api_token_audit_owner_idx"),
        ("projects", "0139_historicaltask_duration_unit_task_duration_unit"),
        ("projects", "0140_historicaltask_auto_container_and_more"),
        ("projects", "0141_historicalproject_draft_started_at_and_more"),
        ("projects", "0142_baseline_calendar_hours_per_day_and_more"),
        ("projects", "0143_sprintcloserequest_failure_reason_and_more"),
        ("projects", "0144_projecttemplate_source_project_and_more"),
        ("projects", "0145_seed_bundled_templates"),
        ("projects", "0146_historicaltask_board_lane_task_board_lane"),
        ("projects", "0147_structuraloperation"),
        ("projects", "0148_task_unique_task_wbs_path_per_project_live"),
        ("projects", "0149_drop_workshops_tables"),
        ("projects", "0150_clear_uncommitted_cpm_output"),
        ("projects", "0151_config_notice_request"),
        ("projects", "0152_aggregate_task_wbs_name_idx"),
        ("projects", "0153_program_sample_anchor_date"),
        ("projects", "0154_object_keys"),
        ("projects", "0155_task_milestone_at_day_end"),
        ("projects", "0156_program_import_job_replaced_project_ids"),
        ("projects", "0157_forecastsnapshot_cpm_finish_at_day_start"),
        ("projects", "0158_baselinetask_finish_at_day_start"),
    ]

    dependencies = [
        ("projects", "0105_historical_changelog_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="boardsavedview",
            name="schema_version",
            field=models.IntegerField(
                default=1,
                help_text="Config shape version; upgraded on read via the migration registry (ADR-0086).",
            ),
        ),
        migrations.CreateModel(
            name="TaskActivityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("cpm_recalculated", "CPM Recalculated"),
                            ("baseline_drift_detected", "Baseline Drift Detected"),
                            ("risk_linked", "Risk Linked"),
                            ("risk_unlinked", "Risk Unlinked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The member who caused the event. NULL for system events (CPM/baseline).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_events",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_task_activity_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "event_type", "-created_at"], name="task_activity_evt_idx"
                    )
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="apitoken",
            name="api_token_scope_xor",
        ),
        migrations.RemoveConstraint(
            model_name="apitokenauditentry",
            name="api_token_audit_scope_xor",
        ),
        migrations.AddField(
            model_name="apitoken",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional expiry (ADR-0214). Null = non-expiring. The authenticator rejects a token whose expiry is in the past; project/program tokens leave this null and are unaffected.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for a user-scoped Personal Access Token (ADR-0214). The token acts as this user, so RBAC applies exactly as their session would. CASCADE — a deleted account takes its full-access credentials with it. Exactly one of project/program/owner is non-null (DB constraint).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_api_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apitokenauditentry",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_api_token_audit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="apitoken",
            index=models.Index(
                fields=["owner", "revoked_at"], name="projects_ap_owner_i_f970a8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="apitoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("owner__isnull", True),
                        ("program__isnull", True),
                        ("project__isnull", False),
                    ),
                    models.Q(
                        ("owner__isnull", True),
                        ("program__isnull", False),
                        ("project__isnull", True),
                    ),
                    models.Q(
                        ("owner__isnull", False),
                        ("program__isnull", True),
                        ("project__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="api_token_scope_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="apitokenauditentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("owner__isnull", True),
                        ("program__isnull", True),
                        ("project__isnull", False),
                    ),
                    models.Q(
                        ("owner__isnull", True),
                        ("program__isnull", False),
                        ("project__isnull", True),
                    ),
                    models.Q(
                        ("owner__isnull", False),
                        ("program__isnull", True),
                        ("project__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="api_token_audit_scope_xor",
            ),
        ),
        migrations.CreateModel(
            name="ProjectExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=512)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="projects.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_export_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status", "created_at"],
                        name="projexport_proj_status_idx",
                    ),
                    models.Index(fields=["expires_at"], name="projexport_expires_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectCalendarLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("holidays", "Holidays"),
                            ("workspace", "Workspace / shutdown"),
                        ],
                        default="holidays",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_to_layers",
                        to="projects.calendar",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_layers",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_project_calendar_layer",
                "ordering": ["sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "calendar"), name="uniq_project_calendar_layer"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "content_kind",
                    models.CharField(
                        choices=[("board", "Board"), ("schedule", "Schedule")],
                        default="board",
                        help_text="What the link exposes — 'board' (#283) or 'schedule' (#1486).",
                        max_length=16,
                    ),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        db_index=True,
                        help_text="First 12 chars of the raw token, for non-revealing display.",
                        max_length=12,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hex digest of the raw token. The raw token is never stored.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional human label, e.g. 'Client review board'.",
                        max_length=120,
                    ),
                ),
                (
                    "show_assignees",
                    models.BooleanField(
                        default=False,
                        help_text="When false (default), assignee names are omitted from the public view so no individual is exposed without an explicit opt-in.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Set when an Admin revokes the link. Non-null = inactive.",
                        null=True,
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Successful public views; incremented atomically per hit.",
                    ),
                ),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="projects.project",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional auto-expiry (#1486). Null = never expires. Once past, the public endpoint returns 410 (gone) exactly like a revoked link.",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "projects_sharelink",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "revoked_at"], name="projects_sh_project_c8a00e_idx"
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="percent_complete",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="percent_complete",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="default_member_role",
            field=models.IntegerField(
                choices=trueppm_api.apps.projects.models._member_role_choices, default=100
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="default_member_role",
            field=models.IntegerField(
                choices=trueppm_api.apps.projects.models._member_role_choices, default=100
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="end_date_shift_threshold_days",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date_shift_threshold_days",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="taskactivityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("cpm_recalculated", "CPM Recalculated"),
                    ("baseline_drift_detected", "Baseline Drift Detected"),
                    ("risk_linked", "Risk Linked"),
                    ("risk_unlinked", "Risk Unlinked"),
                    ("assignee_added", "Assignee Added"),
                    ("assignee_removed", "Assignee Removed"),
                    ("assignee_units_changed", "Assignee Allocation Changed"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("slate", "Slate"),
                            ("teal", "Teal"),
                            ("purple", "Purple"),
                            ("blue", "Blue"),
                            ("rose", "Rose"),
                            ("amber", "Amber"),
                            ("green", "Green"),
                            ("cyan", "Cyan"),
                        ],
                        default="slate",
                        max_length=16,
                    ),
                ),
                ("position", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_label",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="TaskLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projects.label"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projects.task"
                    ),
                ),
            ],
            options={
                "db_table": "projects_task_label",
            },
        ),
        migrations.AddField(
            model_name="label",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="labels", through="projects.TaskLabel", to="projects.task"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasklabel",
            constraint=models.UniqueConstraint(
                fields=("task", "label"), name="uniq_task_label_task_label"
            ),
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(
                fields=["project", "server_version"], name="label_proj_serverver_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="uniq_label_name_per_project"
            ),
        ),
        migrations.CreateModel(
            name="ProgramExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=512)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="projects.program",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "programs_export_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["program", "status", "created_at"],
                        name="progexport_prog_status_idx",
                    ),
                    models.Index(fields=["expires_at"], name="progexport_expires_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="historicalprogram",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.calendar",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programs",
                to="projects.calendar",
            ),
        ),
        migrations.AlterField(
            model_name="backlogitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("epic", "Epic"),
                    ("feature", "Feature"),
                    ("story", "Story"),
                    ("task", "Task"),
                    ("bug", "Bug"),
                    ("spike", "Spike"),
                    ("chore", "Chore"),
                ],
                default="task",
                max_length=16,
            ),
        ),
        migrations.RunPython(
            code=_original(
                "projects", "0121_task_three_point_estimate_ordered", "_null_invalid_triples"
            ),
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("optimistic_duration__isnull", True),
                    ("most_likely_duration__isnull", True),
                    ("pessimistic_duration__isnull", True),
                    models.Q(
                        ("optimistic_duration__lte", models.F("most_likely_duration")),
                        ("most_likely_duration__lte", models.F("pessimistic_duration")),
                    ),
                    _connector="OR",
                ),
                name="task_three_point_estimate_ordered",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalTaskRelation",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("relates_to", "Relates to"),
                            ("blocks", "Blocks"),
                            ("duplicates", "Duplicates"),
                        ],
                        default="relates_to",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=280)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.task",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical task relation",
                "verbose_name_plural": "historical task relations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="agile_features",
        ),
        migrations.RemoveField(
            model_name="project",
            name="agile_features",
        ),
        migrations.AddField(
            model_name="dependency",
            name="is_driving",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalprogram",
            name="estimation_scale",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="estimation_scale",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="estimation_scale",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="estimation_scale",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectcustomfield",
            name="show_on_card",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TaskCustomFieldValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("value_text", models.TextField(blank=True, default="")),
                (
                    "value_number",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
                ),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_option", models.CharField(blank=True, default="", max_length=32)),
                ("value_multi", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="projects.projectcustomfield",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="projects.task",
                    ),
                ),
                (
                    "value_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "task custom field value",
                "verbose_name_plural": "task custom field values",
                "db_table": "projects_taskcustomfieldvalue",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "field"), name="uniq_taskcustomfieldvalue_task_field"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="historicalprogram",
            name="mcp_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="mcp_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="mcp_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="mcp_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acceptancecriterion",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="backlogitem",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="baseline",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="calendar",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="ceremonytemplate",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="dependency",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="inboundtasklink",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="label",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="phasegateconfig",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="program",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="project",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="projectcalendarlayer",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="projectdecisionspolicy",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="projectguardrailpolicy",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="projectsignalprivacypolicy",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="pulseresponse",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="retroactionitem",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="retroboarditem",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="risk",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="sprint",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="sprintretro",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="task",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="taskrecurrencerule",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name="TaskRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("relates_to", "Relates to"),
                            ("blocks", "Blocks"),
                            ("duplicates", "Duplicates"),
                        ],
                        default="relates_to",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_task_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_out",
                        to="projects.task",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_in",
                        to="projects.task",
                    ),
                ),
                ("sync_seq", models.BigIntegerField(default=0, editable=False)),
            ],
            options={
                "db_table": "projects_task_relation",
                "indexes": [
                    models.Index(
                        fields=["source", "server_version"], name="taskrel_source_ver_idx"
                    ),
                    models.Index(fields=["target"], name="taskrel_target_idx"),
                    models.Index(fields=["is_deleted", "deleted_at"], name="taskrel_isdel_del_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("source", "target", "relation_type"),
                        name="uniq_task_relation_live",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source", models.F("target")), _negated=True),
                        name="task_relation_no_self",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="tasksuggestedassignee",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="dependency",
            index=models.Index(fields=["predecessor", "sync_seq"], name="dep_pred_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(fields=["project", "sync_seq"], name="label_proj_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="pulseresponse",
            index=models.Index(fields=["retro", "sync_seq"], name="pulse_retro_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="retroactionitem",
            index=models.Index(fields=["retro", "sync_seq"], name="rai_retro_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="retroboarditem",
            index=models.Index(fields=["retro", "sync_seq"], name="rbi_retro_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(fields=["project", "sync_seq"], name="risk_proj_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(fields=["project", "sync_seq"], name="sprint_proj_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="sprintretro",
            index=models.Index(fields=["sprint", "sync_seq"], name="retro_sprint_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["project", "sync_seq"], name="task_proj_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="taskrecurrencerule",
            index=models.Index(fields=["task", "sync_seq"], name="trr_task_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="taskrelation",
            index=models.Index(fields=["source", "sync_seq"], name="taskrel_source_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="tasksuggestedassignee",
            index=models.Index(fields=["task", "sync_seq"], name="tsa_task_syncseq_idx"),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="show_milestone_dates",
            field=models.BooleanField(
                default=True,
                help_text="Schedule links only. When false, milestone rows (and their dated diamonds) are omitted from the public schedule. Defaults true — milestones are the headline an external audience wants.",
            ),
        ),
        migrations.CreateModel(
            name="ProgramImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=512)),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("replace", models.BooleanField(default=False)),
                ("replaced_program_id", models.UUIDField(blank=True, null=True)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="projects.program",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "programs_import_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["program", "status", "created_at"],
                        name="progimport_prog_status_idx",
                    ),
                    models.Index(fields=["expires_at"], name="progimport_expires_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="historicalprogram",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="scheduled_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status_date_floor_armed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="seeded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="source_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("hand", "Hand-authored"),
                    ("template", "Project template"),
                    ("seed_import", "Native seed import"),
                    ("csv_import", "CSV/Excel import"),
                    ("msproject_import", "MS Project import"),
                    ("jira_import", "Jira import"),
                    ("paste", "Pasted rows"),
                ],
                default="hand",
                help_text="What wrote this row (ADR-0786).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="source_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Template version this row was seeded from; empty for other sources.",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("edited_at__isnull", True), ("is_deleted", False)),
                fields=["project", "seeded_at"],
                name="task_untouched_seeded_idx",
            ),
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("community", "Community"),
                            ("personal", "Yours"),
                        ],
                        db_index=True,
                        default="workspace",
                        help_text="Provenance chip shown in the gallery before adoption (ADR-0789).",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("carries", models.JSONField(blank=True, default=list)),
                ("structure", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_templates",
                        to="projects.program",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_publishes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_project_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("template_name", models.CharField(blank=True, default="", max_length=200)),
                ("template_version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("undone", "Undone"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                (
                    "created_task_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_applications",
                        to="projects.project",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="projects.projecttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "projects_template_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(
                fields=["program", "is_published", "name"], name="projtmpl_prog_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templateapplication",
            index=models.Index(fields=["status", "created_at"], name="tmplapply_status_idx"),
        ),
        migrations.AddIndex(
            model_name="templateapplication",
            index=models.Index(fields=["project", "created_at"], name="tmplapply_proj_idx"),
        ),
        migrations.CreateModel(
            name="CascadeClassificationOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("subtree_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("undone", "Undone")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("task_snapshots", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cascade_classification_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cascade_classification_operations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_cascade_classification_operation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="cascclass_created_idx"),
                    models.Index(fields=["project", "created_at"], name="cascclass_proj_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasteManyOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("undone", "Undone")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_task_versions", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paste_many_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paste_many_operations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_paste_many_operation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="pastemany_created_idx"),
                    models.Index(fields=["project", "created_at"], name="pastemany_proj_idx"),
                ],
            },
        ),
        migrations.RunPython(
            code=_original(
                "projects", "0137_collapse_dual_scope_api_tokens", "collapse_dual_scope_tokens"
            ),
            reverse_code=_original(
                "projects", "0137_collapse_dual_scope_api_tokens", "noop_reverse"
            ),
        ),
        migrations.AddIndex(
            model_name="apitokenauditentry",
            index=models.Index(fields=["owner", "-created_at"], name="api_token_audit_owner_idx"),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="duration_unit",
            field=models.CharField(
                choices=[("days", "Days"), ("hours", "Hours")],
                default="days",
                help_text="Unit this task's duration is entered and displayed in. Presentation only — `duration` is always working days.",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="duration_unit",
            field=models.CharField(
                choices=[("days", "Days"), ("hours", "Hours")],
                default="days",
                help_text="Unit this task's duration is entered and displayed in. Presentation only — `duration` is always working days.",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="auto_container",
            field=models.BooleanField(
                default=False,
                help_text="Set when this row became a container by gaining a child rather than by declaration. Governs whether losing the last child reverts it.",
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="own_estimate",
            field=models.IntegerField(
                blank=True,
                help_text="Working-day duration this task had before it became a container. Parked, not used, while it has children.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="own_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BACKLOG", "Backlog"),
                    ("NOT_STARTED", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("REVIEW", "Review"),
                    ("ON_HOLD", "On hold"),
                    ("COMPLETE", "Complete"),
                ],
                help_text="Status this task had before it became a container. Parked, not used, while it has children; restored when it loses the last one.",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="structure_role",
            field=models.CharField(
                choices=[("work", "Work"), ("container", "Container"), ("milestone", "Milestone")],
                db_index=True,
                default="work",
                help_text="What this row is, as declared by its author: work, container or milestone. Presentation and grouping only — rollup still derives from structural child count.",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="auto_container",
            field=models.BooleanField(
                default=False,
                help_text="Set when this row became a container by gaining a child rather than by declaration. Governs whether losing the last child reverts it.",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="own_estimate",
            field=models.IntegerField(
                blank=True,
                help_text="Working-day duration this task had before it became a container. Parked, not used, while it has children.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="own_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BACKLOG", "Backlog"),
                    ("NOT_STARTED", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("REVIEW", "Review"),
                    ("ON_HOLD", "On hold"),
                    ("COMPLETE", "Complete"),
                ],
                help_text="Status this task had before it became a container. Parked, not used, while it has children; restored when it loses the last one.",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="structure_role",
            field=models.CharField(
                choices=[("work", "Work"), ("container", "Container"), ("milestone", "Milestone")],
                db_index=True,
                default="work",
                help_text="What this row is, as declared by its author: work, container or milestone. Presentation and grouping only — rollup still derives from structural child count.",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="draft_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="lifecycle",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active")],
                db_index=True,
                default="active",
                help_text="draft = nobody has committed to this plan yet; it stays out of rollup, portfolio health, search and notifications. active = committed. Not a write gate — use is_archived for that.",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="draft_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="lifecycle",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active")],
                db_index=True,
                default="active",
                help_text="draft = nobody has committed to this plan yet; it stays out of rollup, portfolio health, search and notifications. active = committed. Not a write gate — use is_archived for that.",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="baseline",
            name="calendar_hours_per_day",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseline",
            name="calendar_id_at_capture",
            field=models.UUIDField(
                blank=True,
                help_text="Which calendar produced these dates. Recorded for provenance, not read for arithmetic.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="baseline",
            name="calendar_working_days",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sprintcloserequest",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cancelled", "Sprint was cancelled before the close completed"),
                    ("not_closable", "Sprint state is not closable"),
                    ("stalled", "Stopped responding on every attempt and was abandoned"),
                    ("error", "Raised an exception (detail in error_message)"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="sprintcloserequest",
            name="next_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the drain may retry a FAILED row. Null means terminal — either the failure is unfixable or the attempt budget is spent.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="sprintcloserequest",
            index=models.Index(fields=["status", "next_attempt_at"], name="sprint_close_retry_idx"),
        ),
        migrations.AddField(
            model_name="projecttemplate",
            name="source_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_templates",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projecttemplate",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_by",
                to="projects.projecttemplate",
            ),
        ),
        migrations.RunPython(
            code=_original("projects", "0145_seed_bundled_templates", "seed"),
            reverse_code=_original("projects", "0145_seed_bundled_templates", "unseed"),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="board_lane",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Named lane within this task's status column. Empty = the column's first lane. Presentation only — never affects scheduling or rollup.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="board_lane",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Named lane within this task's status column. Empty = the column's first lane. Presentation only — never affects scheduling or rollup.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="StructuralOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("indent", "Indent"),
                            ("outdent", "Outdent"),
                            ("reparent", "Reparent"),
                            ("reorder", "Reorder"),
                            ("group", "Group"),
                            ("ungroup", "Ungroup"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("undone", "Undone")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("undoable", models.BooleanField(default=True)),
                ("shape_before", models.JSONField(blank=True, default=dict)),
                ("shape_after", models.JSONField(blank=True, default=dict)),
                (
                    "region_roots",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "anchor_task_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "created_task_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "deleted_task_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                ("created_task_versions", models.JSONField(blank=True, default=dict)),
                (
                    "removed_dependency_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structural_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structural_operations",
                        to="projects.project",
                    ),
                ),
                (
                    "undone_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structural_operations_undone",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_structural_operation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="structop_created_idx"),
                    models.Index(fields=["project", "created_at"], name="structop_proj_idx"),
                    models.Index(
                        fields=["project", "applied_by", "status", "created_at"],
                        name="structop_stack_idx",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS btree_gist;",
            reverse_sql="",
        ),
        migrations.RunPython(
            code=_original(
                "projects",
                "0148_task_unique_task_wbs_path_per_project_live",
                "_repair_duplicate_wbs_paths",
            ),
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("is_deleted", False)),
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                expressions=[("project", "="), ("wbs_path", "=")],
                name="unique_task_wbs_path_per_project_live",
            ),
        ),
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS workshops_participant;",
                "DROP TABLE IF EXISTS workshops_session;",
                "DELETE FROM django_migrations WHERE app = 'workshops';",
            ],
            reverse_sql="",
        ),
        migrations.RunPython(
            code=_original(
                "projects", "0150_clear_uncommitted_cpm_output", "_clear_uncommitted_cpm_output"
            ),
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="task",
            name="early_finish",
            field=models.DateField(
                blank=True,
                help_text="CPM early finish. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="early_start",
            field=models.DateField(
                blank=True,
                help_text="CPM early start. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="free_float",
            field=models.IntegerField(
                blank=True,
                help_text="Free float in working days. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_critical",
            field=models.BooleanField(
                blank=True,
                help_text="Critical-path membership. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="late_finish",
            field=models.DateField(
                blank=True,
                help_text="CPM late finish. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="late_start",
            field=models.DateField(
                blank=True,
                help_text="CPM late start. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="scheduled_start",
            field=models.DateField(
                blank=True,
                help_text="CPM span start. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="total_float",
            field=models.IntegerField(
                blank=True,
                help_text="Total float in working days. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ConfigNoticeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=8)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("dead", "Dead"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=255)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"], name="config_notice_status_idx"
                    ),
                    models.Index(
                        fields=["status", "claimed_at"], name="config_notice_recovery_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "wbs_path", "name"], name="task_proj_wbs_name_idx"
            ),
        ),
        migrations.AddField(
            model_name="historicalprogram",
            name="sample_anchor_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="sample_anchor_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ObjectKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("project", "Project"), ("program", "Program")], max_length=8
                    ),
                ),
                ("key", models.CharField(max_length=40)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "Typed by a user"),
                            ("derived", "Derived from the name"),
                            ("backfill", "Rewritten by the 0.4 upgrade"),
                        ],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="object_keys",
                        to="projects.program",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="object_keys",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_objectkey",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("kind"),
                        django.db.models.functions.text.Upper("key"),
                        name="objectkey_kind_key_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "project"), ("program__isnull", True)),
                            models.Q(("kind", "program"), ("project__isnull", True)),
                            _connector="OR",
                        ),
                        name="objectkey_owner_matches_kind",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True), ("project__isnull", False)),
                        fields=("project",),
                        name="objectkey_one_current_per_project",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True), ("program__isnull", False)),
                        fields=("program",),
                        name="objectkey_one_current_per_program",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            code=_original("projects", "0154_object_keys", "_repair_object_keys"),
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("code"),
                condition=models.Q(("code", ""), _negated=True),
                name="program_code_upper_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("code"),
                condition=models.Q(("code", ""), _negated=True),
                name="project_code_upper_uniq",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="milestone_at_day_end",
            field=models.BooleanField(
                default=False,
                help_text="CPM output: True when a zero-duration milestone sits at the END of its early_start day (it follows work), False when it sits at the start of that day or the task is not a milestone. Read-only engine output.",
            ),
        ),
        migrations.AddField(
            model_name="programimportjob",
            name="replaced_project_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="forecastsnapshot",
            name="cpm_finish_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baselinetask",
            name="finish_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
