# Generated by Django 5.2.14 on 2026-07-04 18:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0106_boardsavedview_schema_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskActivityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("cpm_recalculated", "CPM Recalculated"),
                            ("baseline_drift_detected", "Baseline Drift Detected"),
                            ("risk_linked", "Risk Linked"),
                            ("risk_unlinked", "Risk Unlinked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The member who caused the event. NULL for system events (CPM/baseline).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_events",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_task_activity_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "event_type", "-created_at"], name="task_activity_evt_idx"
                    )
                ],
            },
        ),
    ]
