# Generated by Django 5.2.15 on 2026-07-05 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0107_task_activity_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="apitoken",
            name="api_token_scope_xor",
        ),
        migrations.RemoveConstraint(
            model_name="apitokenauditentry",
            name="api_token_audit_scope_xor",
        ),
        migrations.AddField(
            model_name="apitoken",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional expiry (ADR-0214). Null = non-expiring. The authenticator rejects a token whose expiry is in the past; project/program tokens leave this null and are unaffected.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for a user-scoped Personal Access Token (ADR-0214). The token acts as this user, so RBAC applies exactly as their session would. CASCADE — a deleted account takes its full-access credentials with it. Exactly one of project/program/owner is non-null (DB constraint).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_api_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apitokenauditentry",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_api_token_audit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="apitoken",
            index=models.Index(
                fields=["owner", "revoked_at"], name="projects_ap_owner_i_f970a8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="apitoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("owner__isnull", True),
                        ("program__isnull", True),
                        ("project__isnull", False),
                    ),
                    models.Q(
                        ("owner__isnull", True),
                        ("program__isnull", False),
                        ("project__isnull", True),
                    ),
                    models.Q(
                        ("owner__isnull", False),
                        ("program__isnull", True),
                        ("project__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="api_token_scope_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="apitokenauditentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("owner__isnull", True),
                        ("program__isnull", True),
                        ("project__isnull", False),
                    ),
                    models.Q(
                        ("owner__isnull", True),
                        ("program__isnull", False),
                        ("project__isnull", True),
                    ),
                    models.Q(
                        ("owner__isnull", False),
                        ("program__isnull", True),
                        ("project__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="api_token_audit_scope_xor",
            ),
        ),
    ]
