# Generated by Django 5.2.15 on 2026-07-06 11:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0109_projectexportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "content_kind",
                    models.CharField(
                        choices=[("board", "Board")],
                        default="board",
                        help_text="What the link exposes. 'board' today; #1486 adds 'schedule'.",
                        max_length=16,
                    ),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        db_index=True,
                        help_text="First 12 chars of the raw token, for non-revealing display.",
                        max_length=12,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hex digest of the raw token. The raw token is never stored.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional human label, e.g. 'Client review board'.",
                        max_length=120,
                    ),
                ),
                (
                    "show_assignees",
                    models.BooleanField(
                        default=False,
                        help_text="When false (default), assignee names are omitted from the public view so no individual is exposed without an explicit opt-in.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Set when an Admin revokes the link. Non-null = inactive.",
                        null=True,
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Successful public views; incremented atomically per hit.",
                    ),
                ),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="projects.project",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_sharelink",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "revoked_at"], name="projects_sh_project_c8a00e_idx"
                    )
                ],
            },
        ),
    ]
