# Generated by Django 5.2.15 on 2026-07-06 12:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0110_sharelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCalendarLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("holidays", "Holidays"),
                            ("workspace", "Workspace / shutdown"),
                        ],
                        default="holidays",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_to_layers",
                        to="projects.calendar",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_layers",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_project_calendar_layer",
                "ordering": ["sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "calendar"), name="uniq_project_calendar_layer"
                    )
                ],
            },
        ),
    ]
