# Generated by Django 5.2.15 on 2026-07-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0111_projectcalendarlayer"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharelink",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional auto-expiry (#1486). Null = never expires. Once past, the public endpoint returns 410 (gone) exactly like a revoked link.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="content_kind",
            field=models.CharField(
                choices=[("board", "Board"), ("schedule", "Schedule")],
                default="board",
                help_text="What the link exposes — 'board' (#283) or 'schedule' (#1486).",
                max_length=16,
            ),
        ),
    ]
