# Generated by Django 5.2.15 on 2026-07-09 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0112_sharelink_expires_at_alter_sharelink_content_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltask",
            name="percent_complete",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="percent_complete",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
