# Generated by Django 5.2.16 on 2026-07-12 13:13

from django.db import migrations, models

import trueppm_api.apps.projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0113_alter_historicaltask_percent_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="default_member_role",
            field=models.IntegerField(
                choices=trueppm_api.apps.projects.models._member_role_choices, default=100
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="default_member_role",
            field=models.IntegerField(
                choices=trueppm_api.apps.projects.models._member_role_choices, default=100
            ),
        ),
    ]
