# Generated by Django 5.2.16 on 2026-07-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0114_historicalproject_default_member_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="end_date_shift_threshold_days",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date_shift_threshold_days",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
