# Generated by Django 5.2.16 on 2026-07-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0115_historicalproject_end_date_shift_threshold_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskactivityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("cpm_recalculated", "CPM Recalculated"),
                    ("baseline_drift_detected", "Baseline Drift Detected"),
                    ("risk_linked", "Risk Linked"),
                    ("risk_unlinked", "Risk Unlinked"),
                    ("assignee_added", "Assignee Added"),
                    ("assignee_removed", "Assignee Removed"),
                    ("assignee_units_changed", "Assignee Allocation Changed"),
                ],
                max_length=32,
            ),
        ),
    ]
