# Generated by Django 5.2.16 on 2026-07-14 11:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0115_historicalproject_end_date_shift_threshold_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("slate", "Slate"),
                            ("teal", "Teal"),
                            ("purple", "Purple"),
                            ("blue", "Blue"),
                            ("rose", "Rose"),
                            ("amber", "Amber"),
                            ("green", "Green"),
                            ("cyan", "Cyan"),
                        ],
                        default="slate",
                        max_length=16,
                    ),
                ),
                ("position", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_label",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="TaskLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projects.label"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projects.task"
                    ),
                ),
            ],
            options={
                "db_table": "projects_task_label",
            },
        ),
        migrations.AddField(
            model_name="label",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="labels", through="projects.TaskLabel", to="projects.task"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasklabel",
            constraint=models.UniqueConstraint(
                fields=("task", "label"), name="uniq_task_label_task_label"
            ),
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(
                fields=["project", "server_version"], name="label_proj_serverver_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="uniq_label_name_per_project"
            ),
        ),
    ]
