# Generated by Django 5.2.16 on 2026-07-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0118_programexportjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backlogitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("epic", "Epic"),
                    ("feature", "Feature"),
                    ("story", "Story"),
                    ("task", "Task"),
                    ("bug", "Bug"),
                    ("spike", "Spike"),
                    ("chore", "Chore"),
                ],
                default="task",
                max_length=16,
            ),
        ),
    ]
