# Generated by Django 5.2.16 on 2026-07-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0118_programexportjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.calendar",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programs",
                to="projects.calendar",
            ),
        ),
    ]
