# Generated by Django 5.2.16 on 2026-07-16 12:18

from typing import Any

from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Q


def _null_invalid_triples(apps: Any, schema_editor: Any) -> None:
    """Null the estimate on any row that violates the ordering, before the
    constraint is added (#2005).

    A complete-but-mis-ordered three-point triple (e.g. ``1, 5, 0``) is already
    unusable — the scheduler engine rejects it at compute time and it detonates the
    next program-schedule recompute — so nulling the three duration fields is
    non-destructive: the task falls back to its deterministic ``duration`` and
    becomes schedulable again. Without this step ``AddConstraint`` would fail on any
    existing deployment carrying such a row (including a demo with a stray task).
    """
    Task = apps.get_model("projects", "Task")
    invalid = Task.objects.filter(
        optimistic_duration__isnull=False,
        most_likely_duration__isnull=False,
        pessimistic_duration__isnull=False,
    ).exclude(
        Q(optimistic_duration__lte=F("most_likely_duration"))
        & Q(most_likely_duration__lte=F("pessimistic_duration"))
    )
    invalid.update(
        optimistic_duration=None,
        most_likely_duration=None,
        pessimistic_duration=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0120_alter_backlogitem_item_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Clean pre-existing invalid triples first so AddConstraint validates.
        # Irreversible: the original mis-ordered values cannot be reconstructed and
        # were already unusable, so the reverse is a no-op.
        migrations.RunPython(_null_invalid_triples, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("optimistic_duration__isnull", True),
                    ("most_likely_duration__isnull", True),
                    ("pessimistic_duration__isnull", True),
                    models.Q(
                        ("optimistic_duration__lte", models.F("most_likely_duration")),
                        ("most_likely_duration__lte", models.F("pessimistic_duration")),
                    ),
                    _connector="OR",
                ),
                name="task_three_point_estimate_ordered",
            ),
        ),
    ]
