# Generated by Django 5.2.16 on 2026-07-16 14:47

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0121_task_three_point_estimate_ordered"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTaskRelation",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("relates_to", "Relates to"),
                            ("blocks", "Blocks"),
                            ("duplicates", "Duplicates"),
                        ],
                        default="relates_to",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=280)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.task",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical task relation",
                "verbose_name_plural": "historical task relations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TaskRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("server_version", models.BigIntegerField(default=0, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_version", models.BigIntegerField(blank=True, editable=False, null=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("relates_to", "Relates to"),
                            ("blocks", "Blocks"),
                            ("duplicates", "Duplicates"),
                        ],
                        default="relates_to",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_task_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_out",
                        to="projects.task",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_in",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "db_table": "projects_task_relation",
                "indexes": [
                    models.Index(
                        fields=["source", "server_version"], name="taskrel_source_ver_idx"
                    ),
                    models.Index(fields=["target"], name="taskrel_target_idx"),
                    models.Index(fields=["is_deleted", "deleted_at"], name="taskrel_isdel_del_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("source", "target", "relation_type"),
                        name="uniq_task_relation_live",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source", models.F("target")), _negated=True),
                        name="task_relation_no_self",
                    ),
                ],
            },
        ),
    ]
