# Generated by Django 5.2.16 on 2026-07-16 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0122_task_relation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="agile_features",
        ),
        migrations.RemoveField(
            model_name="project",
            name="agile_features",
        ),
    ]
