# Generated by Django 5.2.16 on 2026-07-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0123_remove_historicalproject_agile_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependency",
            name="is_driving",
            field=models.BooleanField(default=False),
        ),
    ]
