# Generated by Django 5.2.16 on 2026-07-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0123_remove_historicalproject_agile_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="estimation_scale",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="estimation_scale",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="estimation_scale",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="estimation_scale",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fibonacci", "Fibonacci (1, 2, 3, 5, 8, 13, 21)"),
                    ("linear", "Linear (1-10)"),
                    ("tshirt", "T-shirt (XS-XL)"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
