# Generated by Django 5.2.16 on 2026-07-18 23:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0125_historicalprogram_estimation_scale_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcustomfield",
            name="show_on_card",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TaskCustomFieldValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("value_text", models.TextField(blank=True, default="")),
                (
                    "value_number",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
                ),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_option", models.CharField(blank=True, default="", max_length=32)),
                ("value_multi", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="projects.projectcustomfield",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="projects.task",
                    ),
                ),
                (
                    "value_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "task custom field value",
                "verbose_name_plural": "task custom field values",
                "db_table": "projects_taskcustomfieldvalue",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "field"), name="uniq_taskcustomfieldvalue_task_field"
                    )
                ],
            },
        ),
    ]
