# Generated by Django 5.2.16 on 2026-07-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0126_projectcustomfield_show_on_card_taskcustomfieldvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="mcp_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="mcp_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="mcp_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="mcp_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
