# Generated by Django 5.2.16 on 2026-07-28 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0127_historicalprogram_mcp_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptancecriterion",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="backlogitem",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="baseline",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="calendar",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="ceremonytemplate",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="dependency",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="inboundtasklink",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="label",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="phasegateconfig",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="program",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="project",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="projectcalendarlayer",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="projectdecisionspolicy",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="projectguardrailpolicy",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="projectsignalprivacypolicy",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="pulseresponse",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="retroactionitem",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="retroboarditem",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="risk",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="sprint",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="sprintretro",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="task",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="taskrecurrencerule",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="taskrelation",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="tasksuggestedassignee",
            name="sync_seq",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="dependency",
            index=models.Index(fields=["predecessor", "sync_seq"], name="dep_pred_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(fields=["project", "sync_seq"], name="label_proj_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="pulseresponse",
            index=models.Index(fields=["retro", "sync_seq"], name="pulse_retro_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="retroactionitem",
            index=models.Index(fields=["retro", "sync_seq"], name="rai_retro_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="retroboarditem",
            index=models.Index(fields=["retro", "sync_seq"], name="rbi_retro_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(fields=["project", "sync_seq"], name="risk_proj_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(fields=["project", "sync_seq"], name="sprint_proj_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="sprintretro",
            index=models.Index(fields=["sprint", "sync_seq"], name="retro_sprint_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["project", "sync_seq"], name="task_proj_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="taskrecurrencerule",
            index=models.Index(fields=["task", "sync_seq"], name="trr_task_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="taskrelation",
            index=models.Index(fields=["source", "sync_seq"], name="taskrel_source_syncseq_idx"),
        ),
        migrations.AddIndex(
            model_name="tasksuggestedassignee",
            index=models.Index(fields=["task", "sync_seq"], name="tsa_task_syncseq_idx"),
        ),
    ]
