# Generated by Django 5.2.16 on 2026-07-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0128_acceptancecriterion_sync_seq_apitoken_sync_seq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharelink",
            name="show_milestone_dates",
            field=models.BooleanField(
                default=True,
                help_text="Schedule links only. When false, milestone rows (and their dated diamonds) are omitted from the public schedule. Defaults true — milestones are the headline an external audience wants.",
            ),
        ),
    ]
