# Generated by Django 5.2.16 on 2026-07-30 16:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0129_sharelink_show_milestone_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=512)),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("replace", models.BooleanField(default=False)),
                ("replaced_program_id", models.UUIDField(blank=True, null=True)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="projects.program",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "programs_import_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["program", "status", "created_at"],
                        name="progimport_prog_status_idx",
                    ),
                    models.Index(fields=["expires_at"], name="progimport_expires_idx"),
                ],
            },
        ),
    ]
