# Generated by Django 5.2.16 on 2026-07-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0130_programimportjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="sprint_picker_ready_only_default",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
