# Generated by Django 5.2.16 on 2026-07-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0130_programimportjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="scheduled_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
