# Generated by Django 5.2.16 on 2026-08-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0131_historicalprogram_sprint_picker_ready_only_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="scheduled_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
