# Generated by Django 5.2.16 on 2026-08-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0132_task_scheduled_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status_date_floor_armed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
