# Generated by Django 5.2.16 on 2026-08-04 17:49

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0133_project_status_date_floor_armed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("community", "Community"),
                            ("personal", "Yours"),
                        ],
                        db_index=True,
                        default="workspace",
                        help_text="Provenance chip shown in the gallery before adoption (ADR-0789).",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("carries", models.JSONField(blank=True, default=list)),
                ("structure", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_templates",
                        to="projects.program",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_publishes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_project_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("template_name", models.CharField(blank=True, default="", max_length=200)),
                ("template_version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("undone", "Undone"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                (
                    "created_task_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_applications",
                        to="projects.project",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="projects.projecttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "projects_template_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(
                fields=["program", "is_published", "name"], name="projtmpl_prog_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templateapplication",
            index=models.Index(fields=["status", "created_at"], name="tmplapply_status_idx"),
        ),
        migrations.AddIndex(
            model_name="templateapplication",
            index=models.Index(fields=["project", "created_at"], name="tmplapply_proj_idx"),
        ),
    ]
