# Generated by Django 5.2.16 on 2026-08-04 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0133_project_status_date_floor_armed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="seeded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="source_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("hand", "Hand-authored"),
                    ("template", "Project template"),
                    ("seed_import", "Native seed import"),
                    ("csv_import", "CSV/Excel import"),
                    ("msproject_import", "MS Project import"),
                    ("jira_import", "Jira import"),
                    ("paste", "Pasted rows"),
                ],
                default="hand",
                help_text="What wrote this row (ADR-0786).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="source_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Template version this row was seeded from; empty for other sources.",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("edited_at__isnull", True), ("is_deleted", False)),
                fields=["project", "seeded_at"],
                name="task_untouched_seeded_idx",
            ),
        ),
    ]
