# Generated by Django 5.2.16 on 2026-08-06 17:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0135_projecttemplate_templateapplication_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CascadeClassificationOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("subtree_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("undone", "Undone")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("task_snapshots", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cascade_classification_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cascade_classification_operations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_cascade_classification_operation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="cascclass_created_idx"),
                    models.Index(fields=["project", "created_at"], name="cascclass_proj_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasteManyOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("undone", "Undone")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_task_versions", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paste_many_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paste_many_operations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_paste_many_operation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="pastemany_created_idx"),
                    models.Index(fields=["project", "created_at"], name="pastemany_proj_idx"),
                ],
            },
        ),
    ]
