# Generated by Django 5.2.16 on 2026-08-17 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0137_collapse_dual_scope_api_tokens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apitokenauditentry",
            index=models.Index(fields=["owner", "-created_at"], name="api_token_audit_owner_idx"),
        ),
    ]
