# Generated by Django 5.2.16 on 2026-08-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0138_apitokenauditentry_api_token_audit_owner_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="duration_unit",
            field=models.CharField(
                choices=[("days", "Days"), ("hours", "Hours")],
                default="days",
                help_text="Unit this task's duration is entered and displayed in. Presentation only — `duration` is always working days.",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="duration_unit",
            field=models.CharField(
                choices=[("days", "Days"), ("hours", "Hours")],
                default="days",
                help_text="Unit this task's duration is entered and displayed in. Presentation only — `duration` is always working days.",
                max_length=5,
            ),
        ),
    ]
