# Generated by Django 5.2.16 on 2026-08-18 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0139_historicaltask_duration_unit_task_duration_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="auto_container",
            field=models.BooleanField(
                default=False,
                help_text="Set when this row became a container by gaining a child rather than by declaration. Governs whether losing the last child reverts it.",
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="own_estimate",
            field=models.IntegerField(
                blank=True,
                help_text="Working-day duration this task had before it became a container. Parked, not used, while it has children.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="own_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BACKLOG", "Backlog"),
                    ("NOT_STARTED", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("REVIEW", "Review"),
                    ("ON_HOLD", "On hold"),
                    ("COMPLETE", "Complete"),
                ],
                help_text="Status this task had before it became a container. Parked, not used, while it has children; restored when it loses the last one.",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="structure_role",
            field=models.CharField(
                choices=[("work", "Work"), ("container", "Container"), ("milestone", "Milestone")],
                db_index=True,
                default="work",
                help_text="What this row is, as declared by its author: work, container or milestone. Presentation and grouping only — rollup still derives from structural child count.",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="auto_container",
            field=models.BooleanField(
                default=False,
                help_text="Set when this row became a container by gaining a child rather than by declaration. Governs whether losing the last child reverts it.",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="own_estimate",
            field=models.IntegerField(
                blank=True,
                help_text="Working-day duration this task had before it became a container. Parked, not used, while it has children.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(36525),
                ],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="own_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BACKLOG", "Backlog"),
                    ("NOT_STARTED", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("REVIEW", "Review"),
                    ("ON_HOLD", "On hold"),
                    ("COMPLETE", "Complete"),
                ],
                help_text="Status this task had before it became a container. Parked, not used, while it has children; restored when it loses the last one.",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="structure_role",
            field=models.CharField(
                choices=[("work", "Work"), ("container", "Container"), ("milestone", "Milestone")],
                db_index=True,
                default="work",
                help_text="What this row is, as declared by its author: work, container or milestone. Presentation and grouping only — rollup still derives from structural child count.",
                max_length=9,
            ),
        ),
    ]
