# Generated by Django 5.2.16 on 2026-08-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0140_historicaltask_auto_container_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="draft_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="lifecycle",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active")],
                db_index=True,
                default="active",
                help_text="draft = nobody has committed to this plan yet; it stays out of rollup, portfolio health, search and notifications. active = committed. Not a write gate — use is_archived for that.",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="draft_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="lifecycle",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active")],
                db_index=True,
                default="active",
                help_text="draft = nobody has committed to this plan yet; it stays out of rollup, portfolio health, search and notifications. active = committed. Not a write gate — use is_archived for that.",
                max_length=6,
            ),
        ),
    ]
