# Generated by Django 5.2.16 on 2026-08-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0141_historicalproject_draft_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseline",
            name="calendar_hours_per_day",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseline",
            name="calendar_id_at_capture",
            field=models.UUIDField(
                blank=True,
                help_text="Which calendar produced these dates. Recorded for provenance, not read for arithmetic.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="baseline",
            name="calendar_working_days",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
