# Generated by Django 5.2.16 on 2026-08-21 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0142_baseline_calendar_hours_per_day_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sprintcloserequest",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cancelled", "Sprint was cancelled before the close completed"),
                    ("not_closable", "Sprint state is not closable"),
                    ("stalled", "Stopped responding on every attempt and was abandoned"),
                    ("error", "Raised an exception (detail in error_message)"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="sprintcloserequest",
            name="next_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the drain may retry a FAILED row. Null means terminal — either the failure is unfixable or the attempt budget is spent.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="sprintcloserequest",
            index=models.Index(fields=["status", "next_attempt_at"], name="sprint_close_retry_idx"),
        ),
    ]
