# Generated by Django 5.2.16 on 2026-08-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0143_sprintcloserequest_failure_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttemplate",
            name="source_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_templates",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projecttemplate",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_by",
                to="projects.projecttemplate",
            ),
        ),
    ]
