# Generated by Django 5.2.16 on 2026-08-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0145_seed_bundled_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="board_lane",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Named lane within this task's status column. Empty = the column's first lane. Presentation only — never affects scheduling or rollup.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="board_lane",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Named lane within this task's status column. Empty = the column's first lane. Presentation only — never affects scheduling or rollup.",
                max_length=32,
            ),
        ),
    ]
