# Generated by Django 5.2.16 on 2026-08-23 00:18

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0146_historicaltask_board_lane_task_board_lane"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StructuralOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("indent", "Indent"),
                            ("outdent", "Outdent"),
                            ("reparent", "Reparent"),
                            ("reorder", "Reorder"),
                            ("group", "Group"),
                            ("ungroup", "Ungroup"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("undone", "Undone")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("undoable", models.BooleanField(default=True)),
                ("shape_before", models.JSONField(blank=True, default=dict)),
                ("shape_after", models.JSONField(blank=True, default=dict)),
                (
                    "region_roots",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "anchor_task_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "created_task_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "deleted_task_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                ("created_task_versions", models.JSONField(blank=True, default=dict)),
                (
                    "removed_dependency_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structural_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structural_operations",
                        to="projects.project",
                    ),
                ),
                (
                    "undone_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structural_operations_undone",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_structural_operation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="structop_created_idx"),
                    models.Index(fields=["project", "created_at"], name="structop_proj_idx"),
                    models.Index(
                        fields=["project", "applied_by", "status", "created_at"],
                        name="structop_stack_idx",
                    ),
                ],
            },
        ),
    ]
