# Generated by Django 5.2.16 on 2026-08-26 00:24

from typing import Any

import django.contrib.postgres.constraints
import django.db.models.constraints
from django.conf import settings
from django.db import migrations, models

from trueppm_api.apps.projects.backfill import repair_duplicate_wbs_paths


def _repair_duplicate_wbs_paths(apps: Any, schema_editor: Any) -> None:
    """Clear duplicate live ``(project, wbs_path)`` rows so ``AddConstraint`` can validate.

    Without this, ``migrate`` aborts on any database that already holds two live tasks
    sharing a path — and because migrations run on container start, that is an upgrade
    crash-loop rather than an error an operator can step around (#3068).

    A three-line wrapper on purpose. The repair AND its WARNING log both live in
    ``projects.backfill`` so a test can reach them without importing this module by
    name, which a squash would delete (CLAUDE.md migration rule 3).
    """
    repair_duplicate_wbs_paths(apps.get_model("projects", "Task"))


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0147_structuraloperation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # btree_gist adds GiST support for scalar equality (=) on ordinary types
        # like the UUID `project` column below — ltree already has its own native
        # GiST opclass, so only the UUID side of this exclusion constraint needs it.
        #
        # Forward is `IF NOT EXISTS`, so reverse must be a noop rather than
        # `DROP EXTENSION IF EXISTS`: on a database where the extension was already
        # present — installed by the operator, or by another schema sharing the
        # database — this migration did not create it, and a rollback dropping it
        # would take out whatever else depends on it. An unused extension left
        # behind is the cheap mistake; a dropped one other objects need is not.
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS btree_gist;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Must precede AddConstraint: the constraint cannot validate while a
        # duplicate exists, and this is what removes them.
        migrations.RunPython(
            _repair_duplicate_wbs_paths,
            # Reverse is a noop by necessity rather than omission. The repair moved
            # rows onto free paths, and those paths may since have been taken by newer
            # work; re-creating the duplicate state is neither possible nor wanted.
            # Dropping the constraint is what makes the old state legal again, and
            # that is the reverse of AddConstraint, not of this.
            migrations.RunPython.noop,
            elidable=False,
        ),
        # LOCK WINDOW — read before upgrading a large install. `EXCLUDE USING GIST`
        # takes ACCESS EXCLUSIVE on `projects_task` for the whole index build, which
        # blocks reads as well as writes. Unlike the `CREATE INDEX CONCURRENTLY` in
        # siblings 0090/0100/0105, an exclusion constraint cannot be built
        # concurrently — PostgreSQL has no `ADD CONSTRAINT ... CONCURRENTLY` — so this
        # is documented rather than fixed. Plan a maintenance window proportional to
        # the row count.
        migrations.AddConstraint(
            model_name="task",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("is_deleted", False)),
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                expressions=[("project", "="), ("wbs_path", "=")],
                name="unique_task_wbs_path_per_project_live",
            ),
        ),
    ]
