# Generated by Django 5.2.16 on 2026-08-26 00:24

import django.contrib.postgres.constraints
import django.db.models.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0147_structuraloperation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # btree_gist adds GiST support for scalar equality (=) on ordinary types
        # like the UUID `project` column below — ltree already has its own native
        # GiST opclass, so only the UUID side of this exclusion constraint needs it.
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS btree_gist;",
            reverse_sql="DROP EXTENSION IF EXISTS btree_gist;",
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("is_deleted", False)),
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                expressions=[("project", "="), ("wbs_path", "=")],
                name="unique_task_wbs_path_per_project_live",
            ),
        ),
    ]
