# Generated by Django 5.2.16 on 2026-08-25 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0147_structuraloperation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("project", "wbs_path"),
                name="unique_task_wbs_path_per_project_live",
            ),
        ),
    ]
