# Generated by Django 5.2.17 on 2026-09-09 17:09

from typing import Any

from django.db import migrations, models

from trueppm_api.apps.projects.services import clear_uncommitted_cpm_output


def _clear_uncommitted_cpm_output(apps: Any, schema_editor: Any) -> None:
    """One-time clear of CPM output on rows that already left the committed set.

    ADR-1152 makes the eight CPM columns non-null iff the row is in
    ``Task.committed``, and the recompute now enforces that going forward. It does
    not reach backwards: the rows carrying residue are by definition NOT in the
    recompute's input, so a project only converges when it next recalculates — and
    an archived or finished project never will. Its overview would keep serving
    phantom late counts indefinitely (#3578).

    A three-line wrapper on purpose: the predicate lives in ``projects.services`` so
    a test can reach it without importing this module by name, which a squash would
    delete (CLAUDE.md migration rule 3).

    No constraint is added, so ``api:migration-constraint-safety`` does not apply.
    All eight columns are in ``_HISTORY_EXCLUDED_TASK``, so this writes no
    ``HistoricalTask`` rows, and it deliberately does not bump ``server_version``
    or trigger a recompute — it is the same derived-output write the CPM task
    already performs (ADR-0091).
    """
    clear_uncommitted_cpm_output(apps.get_model("projects", "Task"))


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0149_drop_workshops_tables"),
    ]

    operations = [
        # Reverse is a noop by necessity, not omission: the cleared values were the
        # engine's output from a run whose inputs no longer exist, and nothing
        # retained them. Re-creating the residue is neither possible nor wanted —
        # the next recompute is what repopulates any row that re-enters the
        # committed set.
        migrations.RunPython(
            _clear_uncommitted_cpm_output,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="task",
            name="early_finish",
            field=models.DateField(
                blank=True,
                help_text="CPM early finish. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="early_start",
            field=models.DateField(
                blank=True,
                help_text="CPM early start. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="free_float",
            field=models.IntegerField(
                blank=True,
                help_text="Free float in working days. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_critical",
            field=models.BooleanField(
                blank=True,
                help_text="Critical-path membership. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="late_finish",
            field=models.DateField(
                blank=True,
                help_text="CPM late finish. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="late_start",
            field=models.DateField(
                blank=True,
                help_text="CPM late start. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="scheduled_start",
            field=models.DateField(
                blank=True,
                help_text="CPM span start. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="total_float",
            field=models.IntegerField(
                blank=True,
                help_text="Total float in working days. Read-only engine output. Null when the task is outside the schedulable set (BACKLOG status, EPIC type, a recurring template or occurrence, or soft-deleted) or has not been scheduled yet.",
                null=True,
            ),
        ),
    ]
