# Generated by Django 5.2.17 on 2026-09-13 22:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0150_clear_uncommitted_cpm_output"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigNoticeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=8)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("dead", "Dead"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=255)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"], name="config_notice_status_idx"
                    ),
                    models.Index(
                        fields=["status", "claimed_at"], name="config_notice_recovery_idx"
                    ),
                ],
            },
        ),
    ]
