# Generated by Django 5.2.17 on 2026-09-15 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0151_config_notice_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "wbs_path", "name"], name="task_proj_wbs_name_idx"
            ),
        ),
    ]
