# Generated by Django 5.2.17 on 2026-09-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0152_aggregate_task_wbs_name_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogram",
            name="sample_anchor_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="sample_anchor_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
