# Generated by Django 5.2.17 on 2026-09-26 16:31

import uuid
from typing import Any

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

from trueppm_api.apps.projects.backfill import repair_object_keys


def _repair_object_keys(apps: Any, schema_editor: Any) -> None:
    """Derive blank codes, suffix duplicates, write one current ObjectKey per object.

    A thin wrapper on purpose: the repair and its WARNING log live in
    ``projects.backfill`` so a test can reach them without importing this module
    by name, which a squash would delete (migration rule 3).
    """
    repair_object_keys(
        apps.get_model("projects", "Project"),
        apps.get_model("projects", "Program"),
        apps.get_model("projects", "ObjectKey"),
        historical_project_model=apps.get_model("projects", "HistoricalProject"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0153_program_sample_anchor_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("project", "Project"), ("program", "Program")], max_length=8
                    ),
                ),
                ("key", models.CharField(max_length=40)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "Typed by a user"),
                            ("derived", "Derived from the name"),
                            ("backfill", "Rewritten by the 0.4 upgrade"),
                        ],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "projects_objectkey",
            },
        ),
        migrations.AddField(
            model_name="objectkey",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="objectkey",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="object_keys",
                to="projects.program",
            ),
        ),
        migrations.AddField(
            model_name="objectkey",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="object_keys",
                to="projects.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectkey",
            constraint=models.UniqueConstraint(
                models.F("kind"),
                django.db.models.functions.text.Upper("key"),
                name="objectkey_kind_key_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectkey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "project"), ("program__isnull", True)),
                    models.Q(("kind", "program"), ("project__isnull", True)),
                    _connector="OR",
                ),
                name="objectkey_owner_matches_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectkey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True), ("project__isnull", False)),
                fields=("project",),
                name="objectkey_one_current_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectkey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True), ("program__isnull", False)),
                fields=("program",),
                name="objectkey_one_current_per_program",
            ),
        ),
        # Must precede the two AddConstraints below (migration rule 7): the
        # constraints cannot validate while a duplicate code exists, and this is
        # what removes them — and gives every project and program its first
        # ObjectKey row.
        migrations.RunPython(
            _repair_object_keys,
            # Reverse is a noop by necessity: the repair rewrote blank and
            # duplicate codes, and restoring the duplicates is neither possible
            # (the originals are only in the upgrade log) nor wanted. Reversing
            # CreateModel drops the ObjectKey rows; dropping the constraints is what
            # makes duplicates legal again.
            migrations.RunPython.noop,
            elidable=False,
        ),
        # ROLLING-UPGRADE WINDOW (migration rule 8, ADR-1237 §4). The blank
        # exclusion is deliberate, not an oversight: values-prod.yaml runs
        # replicaCount: 2 under the default RollingUpdate, so an OLD pod can still
        # create a project/program with code="" after this migration runs, and a
        # full unique index would 500 its second such create. With the condition
        # the old pod's insert succeeds and the new code heals the blank on its
        # next touch. 0.5 drops the condition and adds CheckConstraint(code <> '')
        # after one full release in which no code path writes a blank.
        #
        # Residual gap, accepted (ADR-1237 §4): only the BLANK case is covered.
        # An old pod (no assign_key()) can still save two case-insensitively
        # identical NON-blank codes during the window; the index still catches
        # it, but as an unhandled IntegrityError (500) rather than a graceful
        # 400. Needs two users typing the same code inside a minutes-long
        # rollout, self-resolves once every pod is on the new image, and an old
        # pod cannot be patched retroactively to catch it more gracefully.
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("code"),
                condition=models.Q(("code", ""), _negated=True),
                name="program_code_upper_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("code"),
                condition=models.Q(("code", ""), _negated=True),
                name="project_code_upper_uniq",
            ),
        ),
    ]
