# Generated by Django 5.2.17 on 2026-09-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0153_program_sample_anchor_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="milestone_at_day_end",
            field=models.BooleanField(
                default=False,
                help_text="CPM output: True when a zero-duration milestone sits at the END of its early_start day (it follows work), False when it sits at the start of that day or the task is not a milestone. Read-only engine output.",
            ),
        ),
    ]
