# Generated by Django 5.2.17 on 2026-09-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0155_task_milestone_at_day_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="programimportjob",
            name="replaced_project_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
