# Generated by Django 5.2.17 on 2026-09-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0156_program_import_job_replaced_project_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastsnapshot",
            name="cpm_finish_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
