# Generated by Django 5.2.17 on 2026-09-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0157_forecastsnapshot_cpm_finish_at_day_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselinetask",
            name="finish_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
