# Generated by Django 5.2.14 on 2026-06-23 21:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("scheduling", "0001_failed_task"),
        ("scheduling", "0002_schedulerequest"),
        ("scheduling", "0003_add_schedule_request_reason"),
        ("scheduling", "0004_velocity_suggestion"),
        ("scheduling", "0005_montecarlorun"),
        ("scheduling", "0006_montecarlorun_distribution"),
        ("scheduling", "0007_projectforecastsnapshot"),
    ]

    initial = True

    dependencies = [
        ("projects", "0015_backfill_short_ids"),
        ("projects", "0032_task_is_subtask_and_sprint_scope_change"),
        ("projects", "0060_historicalprojectsignalprivacypolicy_and_more"),
        ("projects", "0086_board_card_search_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("task_name", models.CharField(db_index=True, max_length=255)),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("args", models.JSONField(default=list)),
                ("kwargs", models.JSONField(default=dict)),
                ("exception_type", models.CharField(max_length=255)),
                ("exception_message", models.TextField()),
                ("traceback", models.TextField()),
                ("failure_count", models.PositiveIntegerField(default=1)),
                ("first_failed_at", models.DateTimeField(auto_now_add=True)),
                ("last_failed_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_retry", "Pending Retry"),
                            ("dead", "Dead"),
                            ("dismissed", "Dismissed"),
                            ("retried", "Retried"),
                        ],
                        db_index=True,
                        default="dead",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_failed_at"],
                "indexes": [
                    models.Index(fields=["status", "last_failed_at"], name="failed_task_status_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduleRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("done", "Done"),
                            ("dead", "Dead"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("task_change", "Task Change"),
                            ("dependency_change", "Dependency Change"),
                            ("sprint_closed", "Sprint Closed"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        default="task_change",
                        max_length=24,
                    ),
                ),
            ],
            options={
                "ordering": ["requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"], name="schedule_request_status_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("project",),
                        name="schedule_request_one_pending_per_project",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "dispatched")),
                        fields=("project",),
                        name="schedule_request_one_dispatched_per_project",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VelocitySuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("suggested_duration", models.PositiveIntegerField()),
                (
                    "team_velocity_per_day",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Rolling 6-sprint average of completed_points / sprint_working_days.",
                        max_digits=6,
                    ),
                ),
                ("flag_for_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_velocity_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dismissed_velocity_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="velocity_suggestions",
                        to="projects.sprint",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="velocity_suggestions",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "accepted_at", "dismissed_at"],
                        name="velocity_sugg_task_pending_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "sprint"), name="unique_velocity_suggestion_per_task_sprint"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MonteCarloRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                ("p50", models.DateField(blank=True, null=True)),
                ("p80", models.DateField(blank=True, null=True)),
                ("p95", models.DateField(blank=True, null=True)),
                ("cpm_finish", models.DateField(blank=True, null=True)),
                ("n_simulations", models.PositiveIntegerField()),
                ("task_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monte_carlo_runs",
                        to="projects.project",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("distribution", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "scheduling_montecarlorun",
                "ordering": ["-taken_at"],
                "indexes": [
                    models.Index(fields=["project", "-taken_at"], name="mcrun_project_recent_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectForecastSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("recompute", "Recompute"),
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                        ],
                        default="recompute",
                        max_length=16,
                    ),
                ),
                ("cpm_finish", models.DateField(blank=True, null=True)),
                ("total_float_days", models.IntegerField(blank=True, null=True)),
                ("mc_p50_finish", models.DateField(blank=True, null=True)),
                ("mc_p80_finish", models.DateField(blank=True, null=True)),
                ("mc_p95_finish", models.DateField(blank=True, null=True)),
                ("mc_iterations", models.PositiveIntegerField(blank=True, null=True)),
                ("task_count", models.PositiveIntegerField(default=0)),
                ("completed_task_count", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_forecast_snapshots",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "scheduling_projectforecastsnapshot",
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-captured_at"], name="projfcast_proj_recent_idx"
                    )
                ],
            },
        ),
    ]
