# Generated by Django 6.0.3 on 2026-04-12 15:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0015_backfill_short_ids"),
        ("scheduling", "0001_failed_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("done", "Done"),
                            ("dead", "Dead"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_requests",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"],
                        name="schedule_request_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(status="pending"),
                        fields=("project",),
                        name="schedule_request_one_pending_per_project",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(status="dispatched"),
                        fields=("project",),
                        name="schedule_request_one_dispatched_per_project",
                    ),
                ],
            },
        ),
    ]
