# Generated by Django 6.0.3 on 2026-04-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0002_schedulerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulerequest",
            name="reason",
            field=models.CharField(
                choices=[
                    ("task_change", "Task Change"),
                    ("dependency_change", "Dependency Change"),
                    ("sprint_closed", "Sprint Closed"),
                    ("manual", "Manual"),
                ],
                db_index=True,
                default="task_change",
                max_length=24,
            ),
        ),
    ]
