# Generated by Django 6.0.3 on 2026-05-17 19:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0032_task_is_subtask_and_sprint_scope_change"),
        ("scheduling", "0003_add_schedule_request_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VelocitySuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("suggested_duration", models.PositiveIntegerField()),
                (
                    "team_velocity_per_day",
                    models.DecimalField(
                        decimal_places=3,
                        help_text=(
                            "Rolling 6-sprint average of completed_points / sprint_working_days."
                        ),
                        max_digits=6,
                    ),
                ),
                ("flag_for_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_velocity_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dismissed_velocity_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="velocity_suggestions",
                        to="projects.sprint",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="velocity_suggestions",
                        to="projects.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "accepted_at", "dismissed_at"],
                        name="velocity_sugg_task_pending_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "sprint"), name="unique_velocity_suggestion_per_task_sprint"
                    )
                ],
            },
        ),
    ]
