# Generated by Django 5.2.14 on 2026-06-06 17:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0060_historicalprojectsignalprivacypolicy_and_more"),
        ("scheduling", "0004_velocity_suggestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonteCarloRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                ("p50", models.DateField(blank=True, null=True)),
                ("p80", models.DateField(blank=True, null=True)),
                ("p95", models.DateField(blank=True, null=True)),
                ("cpm_finish", models.DateField(blank=True, null=True)),
                ("n_simulations", models.PositiveIntegerField()),
                ("task_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monte_carlo_runs",
                        to="projects.project",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scheduling_montecarlorun",
                "ordering": ["-taken_at"],
                "indexes": [
                    models.Index(fields=["project", "-taken_at"], name="mcrun_project_recent_idx")
                ],
            },
        ),
    ]
