# Generated by Django 5.2.14 on 2026-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0005_montecarlorun"),
    ]

    operations = [
        migrations.AddField(
            model_name="montecarlorun",
            name="distribution",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
