# Generated by Django 5.2.14 on 2026-06-20 19:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0086_board_card_search_trgm"),
        ("scheduling", "0006_montecarlorun_distribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectForecastSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("recompute", "Recompute"),
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                        ],
                        default="recompute",
                        max_length=16,
                    ),
                ),
                ("cpm_finish", models.DateField(blank=True, null=True)),
                ("total_float_days", models.IntegerField(blank=True, null=True)),
                ("mc_p50_finish", models.DateField(blank=True, null=True)),
                ("mc_p80_finish", models.DateField(blank=True, null=True)),
                ("mc_p95_finish", models.DateField(blank=True, null=True)),
                ("mc_iterations", models.PositiveIntegerField(blank=True, null=True)),
                ("task_count", models.PositiveIntegerField(default=0)),
                ("completed_task_count", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_forecast_snapshots",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "scheduling_projectforecastsnapshot",
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-captured_at"], name="projfcast_proj_recent_idx"
                    )
                ],
            },
        ),
    ]
