# Generated by Django 5.2.14 on 2026-06-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0008_alter_schedulerequest_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulerequest",
            name="reason",
            field=models.CharField(
                choices=[
                    ("task_change", "Task Change"),
                    ("dependency_change", "Dependency Change"),
                    ("calendar_change", "Calendar Change"),
                    ("cross_project_dependency", "Cross-Project Dependency"),
                    ("sprint_closed", "Sprint Closed"),
                    ("manual", "Manual"),
                ],
                db_index=True,
                default="task_change",
                max_length=24,
            ),
        ),
    ]
