# Generated by Django 5.2.14 on 2026-07-04 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0009_alter_schedulerequest_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="failedtask",
            name="resolution_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Operator's free-text note recorded when the task was dropped.",
            ),
        ),
        migrations.AddField(
            model_name="failedtask",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, help_text="When an operator requeued or dropped this task.", null=True
            ),
        ),
        migrations.AddField(
            model_name="failedtask",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace admin who requeued or dropped this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
