# Generated by Django 5.2.17 on 2026-10-05 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("scheduling", "0010_failedtask_resolution_note_failedtask_resolved_at_and_more"),
        ("scheduling", "0011_failedtask_project"),
        ("scheduling", "0012_montecarlorun_diagnostic"),
        ("scheduling", "0013_montecarlorun_status_date"),
        ("scheduling", "0014_montecarlorun_plan_version"),
        ("scheduling", "0015_projectforecastsnapshot_cpm_finish_at_day_start"),
        ("scheduling", "0016_montecarlorun_finish_readings"),
    ]

    dependencies = [
        ("projects", "0114_historicalproject_default_member_role_and_more"),
        ("scheduling", "0009_alter_schedulerequest_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="failedtask",
            name="resolution_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Operator's free-text note recorded when the task was dropped.",
            ),
        ),
        migrations.AddField(
            model_name="failedtask",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, help_text="When an operator requeued or dropped this task.", null=True
            ),
        ),
        migrations.AddField(
            model_name="failedtask",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace admin who requeued or dropped this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="failedtask",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project the failing task acted on, when known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="failed_tasks",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="montecarlorun",
            name="diagnostic",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="montecarlorun",
            name="status_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="montecarlorun",
            name="plan_version",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectforecastsnapshot",
            name="cpm_finish_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="montecarlorun",
            name="cpm_finish_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="montecarlorun",
            name="p50_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="montecarlorun",
            name="p80_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="montecarlorun",
            name="p95_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
