# Generated by Django 5.2.16 on 2026-07-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0114_historicalproject_default_member_role_and_more"),
        ("scheduling", "0010_failedtask_resolution_note_failedtask_resolved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="failedtask",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project the failing task acted on, when known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="failed_tasks",
                to="projects.project",
            ),
        ),
    ]
