# Generated by Django 5.2.16 on 2026-07-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0011_failedtask_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="montecarlorun",
            name="diagnostic",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
