# Generated by Django 5.2.16 on 2026-08-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0012_montecarlorun_diagnostic"),
    ]

    operations = [
        migrations.AddField(
            model_name="montecarlorun",
            name="status_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
