# Generated by Django 5.2.16 on 2026-08-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0013_montecarlorun_status_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="montecarlorun",
            name="plan_version",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
