# Generated by Django 5.2.17 on 2026-09-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0014_montecarlorun_plan_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectforecastsnapshot",
            name="cpm_finish_at_day_start",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
