# Generated by Django 5.2.17 on 2026-09-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0015_projectforecastsnapshot_cpm_finish_at_day_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="montecarlorun",
            name="cpm_finish_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="montecarlorun",
            name="p50_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="montecarlorun",
            name="p80_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="montecarlorun",
            name="p95_at_day_start",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
