# Generated by Django 5.2.17 on 2026-10-05 20:20

import importlib
import uuid
from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _original(app: str, module: str, name: str) -> Any:
    """Return a callable from a retained original migration module.

    Django's squashmigrations writes these references as attribute paths, which
    is a SyntaxError when the module name starts with a digit, so they are
    resolved by name here. The original migration files stay on disk (CLAUDE.md
    migration rule 6); a callable may only be deleted from its original module
    after its body is copied into this file.
    """
    # Every call site passes a constant app/module/name from this file, never user input.
    # nosemgrep: python.lang.security.audit.non-literal-import.non-literal-import
    return getattr(importlib.import_module(f"trueppm_api.apps.{app}.migrations.{module}"), name)


# RunPython callables below are resolved from the retained original migrations
# (see _original). Do not delete those originals without copying the callables here.


class Migration(migrations.Migration):
    replaces = [
        ("agents", "0001_initial"),
        ("agents", "0002_agentactioncheckpoint"),
        ("agents", "0003_agentactionrefusaldetail"),
    ]

    dependencies = [
        ("projects", "0113_alter_historicaltask_percent_complete_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentActionChainHead",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "last_sequence",
                    models.BigIntegerField(
                        default=0,
                        help_text="Highest sequence allocated so far (0 before the first record).",
                    ),
                ),
                (
                    "last_record_hash",
                    models.CharField(
                        default="42af3268b63f31216a85893bad7ac5410dee120bef6b50afbbb6e225afd6882f",
                        help_text="record_hash of the most recent AgentAction — the next row's prev_hash.",
                        max_length=64,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agents_agent_action_chain_head",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="agent_action_chain_head_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="AGENT_ACTION_SCHEMA_VERSION at write time (part of the hashed record).",
                    ),
                ),
                (
                    "actor_kind",
                    models.CharField(choices=[("mcp_token", "MCP token")], max_length=16),
                ),
                (
                    "actor_token_prefix",
                    models.CharField(
                        db_index=True,
                        help_text="First 8 hex chars of the acting token — denormalized, never the token material. Preserved after token deletion.",
                        max_length=8,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Stable operation identifier (e.g. the MCP tool / view name).",
                        max_length=128,
                    ),
                ),
                ("method", models.CharField(help_text="HTTP method (GET, POST, …).", max_length=8)),
                ("object_type", models.CharField(blank=True, default="", max_length=64)),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "capability_used",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The scope/capability that authorized (or was checked for) the action, e.g. 'mcp:read'.",
                        max_length=64,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("refused", "Refused"),
                            ("requires_approval", "Requires approval"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "refusal_reason",
                    models.CharField(
                        blank=True,
                        choices=[("identity", "Identity"), ("policy", "Policy")],
                        default="",
                        help_text="Set (identity|policy) when verdict=refused; empty otherwise.",
                        max_length=16,
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        help_text="sha256 over the canonicalized operation payload (method, path, sorted query, body shape) — the reproducibility anchor for the request.",
                        max_length=64,
                    ),
                ),
                (
                    "engine_version",
                    models.CharField(
                        help_text="trueppm-scheduler version at decision time (the answer-stamp engine anchor).",
                        max_length=64,
                    ),
                ),
                (
                    "sequence",
                    models.BigIntegerField(
                        help_text="Per-instance monotonic sequence (RC2). Gap-free and strictly increasing; a gap or reorder is a tamper signal.",
                        unique=True,
                    ),
                ),
                (
                    "prev_hash",
                    models.CharField(
                        help_text="record_hash of the predecessor row (GENESIS_PREV_HASH for the first).",
                        max_length=64,
                    ),
                ),
                (
                    "record_hash",
                    models.CharField(
                        help_text="sha256(prev_hash ‖ canonical(record)) — the chain link. Recomputed and checked by `manage.py audit_verify`.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, default="", help_text="Human-readable, team-facing."
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Set explicitly at write time (NOT auto_now_add) because its exact value is part of the hashed record.",
                    ),
                ),
                (
                    "actor_token",
                    models.ForeignKey(
                        blank=True,
                        help_text="The API token that acted. SET_NULL — a deleted token leaves its audit trail behind (identified by actor_token_prefix).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_actions",
                        to="projects.apitoken",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        blank=True,
                        help_text="The human on whose behalf the actor acted (the token owner). SET_NULL so the row survives account deletion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_actions_as_principal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="The project in scope, when resolvable from the request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_actions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_action",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(fields=["project", "-occurred_at"], name="agent_action_proj_idx"),
                    models.Index(
                        fields=["principal", "-occurred_at"], name="agent_action_princ_idx"
                    ),
                ],
            },
        ),
        migrations.RunPython(
            code=_original("agents", "0001_initial", "seed_chain_head"),
            reverse_code=_original("agents", "0001_initial", "unseed_chain_head"),
        ),
        migrations.CreateModel(
            name="AgentActionCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "pruned_through_sequence",
                    models.BigIntegerField(
                        help_text="Highest AgentAction.sequence deleted by this prune; the retained chain resumes at pruned_through_sequence + 1.",
                        unique=True,
                    ),
                ),
                (
                    "pruned_through_hash",
                    models.CharField(
                        help_text="record_hash of the last-deleted row — the prev_hash the first surviving row points at, and the seed audit_verify re-anchors from.",
                        max_length=64,
                    ),
                ),
                (
                    "first_retained_sequence",
                    models.BigIntegerField(
                        help_text="Sequence of the lowest surviving row (pruned_through_sequence + 1); audit_verify asserts the retained chain starts here."
                    ),
                ),
                (
                    "pruned_count",
                    models.BigIntegerField(help_text="Number of rows deleted by this prune."),
                ),
                (
                    "created_at",
                    models.DateTimeField(help_text="When the prune ran (set at write time)."),
                ),
                (
                    "pruned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who ran the prune, when known. SET_NULL so the row survives account deletion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_action_prunes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_action_checkpoint",
                "ordering": ["pruned_through_sequence"],
            },
        ),
        migrations.CreateModel(
            name="AgentActionRefusalDetail",
            fields=[
                (
                    "action",
                    models.OneToOneField(
                        help_text="The refused AgentAction this detail explains (1:1, PK).",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="refusal_detail",
                        serialize=False,
                        to="agents.agentaction",
                    ),
                ),
                (
                    "constraint",
                    models.CharField(
                        choices=[
                            ("capability_scope", "Capability scope"),
                            ("token_identity", "Token identity"),
                            ("graph_validation", "Graph validation"),
                            ("sprint_sovereignty", "Sprint sovereignty"),
                            ("rollup_lock", "Rollup lock"),
                            ("engine_referee", "Engine referee"),
                        ],
                        help_text="Which specific guard fired — a finer axis than the chain's refusal_reason (identity|policy).",
                        max_length=32,
                    ),
                ),
                (
                    "projected_impact",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured projected schedule impact of the refused write. Empty {} for the current MCP-scope/identity producers (no schedule impact); the 0.6 gated-write producers populate {affected_task_count, slip_days, critical_path_delta_days, affected_task_ids}.",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_action_refusal_detail",
                "indexes": [
                    models.Index(fields=["constraint"], name="agent_refusal_constraint_idx")
                ],
            },
        ),
    ]
