# Generated by Django 5.2.16 on 2026-07-11 11:28

import uuid
from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_chain_head(apps: Any, schema_editor: Any) -> None:
    """Seed the singleton chain head (id=1) so record_agent_action can lock-and-get it
    without a create race on the very first request (ADR-0112 RC2)."""
    ChainHead = apps.get_model("agents", "AgentActionChainHead")
    ChainHead.objects.get_or_create(id=1)


def unseed_chain_head(apps: Any, schema_editor: Any) -> None:
    ChainHead = apps.get_model("agents", "AgentActionChainHead")
    ChainHead.objects.filter(id=1).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0113_alter_historicaltask_percent_complete_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentActionChainHead",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "last_sequence",
                    models.BigIntegerField(
                        default=0,
                        help_text="Highest sequence allocated so far (0 before the first record).",
                    ),
                ),
                (
                    "last_record_hash",
                    models.CharField(
                        default="42af3268b63f31216a85893bad7ac5410dee120bef6b50afbbb6e225afd6882f",
                        help_text="record_hash of the most recent AgentAction — the next row's prev_hash.",
                        max_length=64,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agents_agent_action_chain_head",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="agent_action_chain_head_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="AGENT_ACTION_SCHEMA_VERSION at write time (part of the hashed record).",
                    ),
                ),
                (
                    "actor_kind",
                    models.CharField(choices=[("mcp_token", "MCP token")], max_length=16),
                ),
                (
                    "actor_token_prefix",
                    models.CharField(
                        db_index=True,
                        help_text="First 8 hex chars of the acting token — denormalized, never the token material. Preserved after token deletion.",
                        max_length=8,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Stable operation identifier (e.g. the MCP tool / view name).",
                        max_length=128,
                    ),
                ),
                ("method", models.CharField(help_text="HTTP method (GET, POST, …).", max_length=8)),
                ("object_type", models.CharField(blank=True, default="", max_length=64)),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "capability_used",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The scope/capability that authorized (or was checked for) the action, e.g. 'mcp:read'.",
                        max_length=64,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("refused", "Refused"),
                            ("requires_approval", "Requires approval"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "refusal_reason",
                    models.CharField(
                        blank=True,
                        choices=[("identity", "Identity"), ("policy", "Policy")],
                        default="",
                        help_text="Set (identity|policy) when verdict=refused; empty otherwise.",
                        max_length=16,
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        help_text="sha256 over the canonicalized operation payload (method, path, sorted query, body shape) — the reproducibility anchor for the request.",
                        max_length=64,
                    ),
                ),
                (
                    "engine_version",
                    models.CharField(
                        help_text="trueppm-scheduler version at decision time (the answer-stamp engine anchor).",
                        max_length=64,
                    ),
                ),
                (
                    "sequence",
                    models.BigIntegerField(
                        help_text="Per-instance monotonic sequence (RC2). Gap-free and strictly increasing; a gap or reorder is a tamper signal.",
                        unique=True,
                    ),
                ),
                (
                    "prev_hash",
                    models.CharField(
                        help_text="record_hash of the predecessor row (GENESIS_PREV_HASH for the first).",
                        max_length=64,
                    ),
                ),
                (
                    "record_hash",
                    models.CharField(
                        help_text="sha256(prev_hash ‖ canonical(record)) — the chain link. Recomputed and checked by `manage.py audit_verify`.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, default="", help_text="Human-readable, team-facing."
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Set explicitly at write time (NOT auto_now_add) because its exact value is part of the hashed record.",
                    ),
                ),
                (
                    "actor_token",
                    models.ForeignKey(
                        blank=True,
                        help_text="The API token that acted. SET_NULL — a deleted token leaves its audit trail behind (identified by actor_token_prefix).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_actions",
                        to="projects.apitoken",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        blank=True,
                        help_text="The human on whose behalf the actor acted (the token owner). SET_NULL so the row survives account deletion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_actions_as_principal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="The project in scope, when resolvable from the request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_actions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_action",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(fields=["project", "-occurred_at"], name="agent_action_proj_idx"),
                    models.Index(
                        fields=["principal", "-occurred_at"], name="agent_action_princ_idx"
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_chain_head, unseed_chain_head),
    ]
