# Generated by Django 5.2.16 on 2026-07-11 18:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentActionCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "pruned_through_sequence",
                    models.BigIntegerField(
                        help_text="Highest AgentAction.sequence deleted by this prune; the retained chain resumes at pruned_through_sequence + 1.",
                        unique=True,
                    ),
                ),
                (
                    "pruned_through_hash",
                    models.CharField(
                        help_text="record_hash of the last-deleted row — the prev_hash the first surviving row points at, and the seed audit_verify re-anchors from.",
                        max_length=64,
                    ),
                ),
                (
                    "first_retained_sequence",
                    models.BigIntegerField(
                        help_text="Sequence of the lowest surviving row (pruned_through_sequence + 1); audit_verify asserts the retained chain starts here."
                    ),
                ),
                (
                    "pruned_count",
                    models.BigIntegerField(help_text="Number of rows deleted by this prune."),
                ),
                (
                    "created_at",
                    models.DateTimeField(help_text="When the prune ran (set at write time)."),
                ),
                (
                    "pruned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who ran the prune, when known. SET_NULL so the row survives account deletion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_action_prunes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_action_checkpoint",
                "ordering": ["pruned_through_sequence"],
            },
        ),
    ]
