# Generated by Django 5.2.16 on 2026-07-15 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_agentactioncheckpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentActionRefusalDetail",
            fields=[
                (
                    "action",
                    models.OneToOneField(
                        help_text="The refused AgentAction this detail explains (1:1, PK).",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="refusal_detail",
                        serialize=False,
                        to="agents.agentaction",
                    ),
                ),
                (
                    "constraint",
                    models.CharField(
                        choices=[
                            ("capability_scope", "Capability scope"),
                            ("token_identity", "Token identity"),
                            ("graph_validation", "Graph validation"),
                            ("sprint_sovereignty", "Sprint sovereignty"),
                            ("rollup_lock", "Rollup lock"),
                            ("engine_referee", "Engine referee"),
                        ],
                        help_text="Which specific guard fired — a finer axis than the chain's refusal_reason (identity|policy).",
                        max_length=32,
                    ),
                ),
                (
                    "projected_impact",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured projected schedule impact of the refused write. Empty {} for the current MCP-scope/identity producers (no schedule impact); the 0.6 gated-write producers populate {affected_task_count, slip_days, critical_path_delta_days, affected_task_ids}.",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_action_refusal_detail",
                "indexes": [
                    models.Index(fields=["constraint"], name="agent_refusal_constraint_idx")
                ],
            },
        ),
    ]
