# Generated by Django 5.2.16 on 2026-08-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csvimport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvimportrequest",
            name="created_task_versions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="csvimportrequest",
            name="undone_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="csvimportrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispatched", "Dispatched"),
                    ("done", "Done"),
                    ("dead", "Dead"),
                    ("undone", "Undone"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
