# Generated by Django 5.2.16 on 2026-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csvimport", "0002_schedule_outline_batch_operations"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvimportrequest",
            name="date_order",
            field=models.CharField(
                default="auto",
                help_text="auto | mdy | dmy | iso — the date convention this import was committed under.",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="csvimportrequest",
            name="date_order_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
