# Generated by Django 5.2.14 on 2026-06-23 21:38

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("webhooks", "0001_initial"),
        ("webhooks", "0002_alter_webhook_events"),
        ("webhooks", "0003_delivery_status_created_idx"),
        ("webhooks", "0004_webhook_program_alter_webhook_project_and_more"),
        ("webhooks", "0005_webhook_delivery_sequence_numbers"),
        ("webhooks", "0006_webhook_format_alter_webhook_events_and_more"),
        ("webhooks", "0007_sprint_lifecycle_events"),
    ]

    initial = True

    dependencies = [
        ("projects", "0013_task_planned_start"),
        ("projects", "0039_apitoken_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("secret", models.CharField(max_length=255)),
                (
                    "events",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("task.created", "Task Created"),
                                ("task.updated", "Task Updated"),
                                ("task.deleted", "Task Deleted"),
                                ("dependency.created", "Dependency Created"),
                                ("dependency.deleted", "Dependency Deleted"),
                                ("schedule.recalculated", "Schedule Recalculated"),
                                ("project.created", "Project Created"),
                            ],
                            max_length=30,
                        ),
                        help_text="List of event types this webhook subscribes to.",
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the webhook fires for events on a single project. Exactly one of project/program is non-null (DB constraint).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="projects.project",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the webhook fires for events on any project within this program. Exactly one of project/program is non-null (DB constraint).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="projects.program",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["project", "is_active"], name="webhook_project_active_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("task.created", "Task Created"),
                            ("task.updated", "Task Updated"),
                            ("task.deleted", "Task Deleted"),
                            ("dependency.created", "Dependency Created"),
                            ("dependency.deleted", "Dependency Deleted"),
                            ("schedule.recalculated", "Schedule Recalculated"),
                            ("project.created", "Project Created"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("response_status", models.SmallIntegerField(blank=True, null=True)),
                ("attempt_count", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhook",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["webhook", "created_at"], name="delivery_webhook_created_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="delivery_status_created_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["program", "is_active"], name="webhook_program_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("program__isnull", True), ("project__isnull", False)),
                    models.Q(("program__isnull", False), ("project__isnull", True)),
                    _connector="OR",
                ),
                name="webhook_scope_xor",
            ),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="sequence_number",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="webhook",
            name="delivery_sequence",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="webhook",
            name="format",
            field=models.CharField(default="generic", max_length=32),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="events",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("task.created", "Task Created"),
                        ("task.updated", "Task Updated"),
                        ("task.deleted", "Task Deleted"),
                        ("dependency.created", "Dependency Created"),
                        ("dependency.deleted", "Dependency Deleted"),
                        ("schedule.recalculated", "Schedule Recalculated"),
                        ("project.created", "Project Created"),
                        ("task.assigned", "Task Assigned"),
                        ("task.assignee_changed", "Task Assignee Changed"),
                        ("task.mentioned", "Task Mentioned"),
                        ("task.due_date_changed", "Task Due Date Changed"),
                        ("sprint.activated", "Sprint Activated"),
                        ("sprint.closed", "Sprint Closed"),
                        ("sprint.scope_changed", "Sprint Scope Changed"),
                    ],
                    max_length=30,
                ),
                help_text="List of event types this webhook subscribes to.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("task.created", "Task Created"),
                    ("task.updated", "Task Updated"),
                    ("task.deleted", "Task Deleted"),
                    ("dependency.created", "Dependency Created"),
                    ("dependency.deleted", "Dependency Deleted"),
                    ("schedule.recalculated", "Schedule Recalculated"),
                    ("project.created", "Project Created"),
                    ("task.assigned", "Task Assigned"),
                    ("task.assignee_changed", "Task Assignee Changed"),
                    ("task.mentioned", "Task Mentioned"),
                    ("task.due_date_changed", "Task Due Date Changed"),
                    ("sprint.activated", "Sprint Activated"),
                    ("sprint.closed", "Sprint Closed"),
                    ("sprint.scope_changed", "Sprint Scope Changed"),
                ],
                max_length=30,
            ),
        ),
    ]
