# Generated by Django 6.0.3 on 2026-04-11 23:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="events",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("task.created", "Task Created"),
                        ("task.updated", "Task Updated"),
                        ("task.deleted", "Task Deleted"),
                        ("dependency.created", "Dependency Created"),
                        ("dependency.deleted", "Dependency Deleted"),
                        ("schedule.recalculated", "Schedule Recalculated"),
                        ("project.created", "Project Created"),
                    ],
                    max_length=30,
                ),
                help_text="List of event types this webhook subscribes to.",
            ),
        ),
    ]
