# Generated by Django 6.0.3 on 2026-05-21 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0039_apitoken_and_more"),
        ("webhooks", "0003_delivery_status_created_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Set when the webhook fires for events on any project within "
                    "this program. Exactly one of project/program is non-null (DB constraint)."
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhooks",
                to="projects.program",
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Set when the webhook fires for events on a single project. "
                    "Exactly one of project/program is non-null (DB constraint)."
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhooks",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["program", "is_active"], name="webhook_program_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("program__isnull", True), ("project__isnull", False)),
                    models.Q(("program__isnull", False), ("project__isnull", True)),
                    _connector="OR",
                ),
                name="webhook_scope_xor",
            ),
        ),
    ]
