# Generated by Django 6.0.3 on 2026-05-24 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0005_webhook_delivery_sequence_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="format",
            field=models.CharField(default="generic", max_length=32),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="events",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("task.created", "Task Created"),
                        ("task.updated", "Task Updated"),
                        ("task.deleted", "Task Deleted"),
                        ("dependency.created", "Dependency Created"),
                        ("dependency.deleted", "Dependency Deleted"),
                        ("schedule.recalculated", "Schedule Recalculated"),
                        ("project.created", "Project Created"),
                        ("task.assigned", "Task Assigned"),
                        ("task.assignee_changed", "Task Assignee Changed"),
                        ("task.mentioned", "Task Mentioned"),
                        ("task.due_date_changed", "Task Due Date Changed"),
                    ],
                    max_length=30,
                ),
                help_text="List of event types this webhook subscribes to.",
            ),
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("task.created", "Task Created"),
                    ("task.updated", "Task Updated"),
                    ("task.deleted", "Task Deleted"),
                    ("dependency.created", "Dependency Created"),
                    ("dependency.deleted", "Dependency Deleted"),
                    ("schedule.recalculated", "Schedule Recalculated"),
                    ("project.created", "Project Created"),
                    ("task.assigned", "Task Assigned"),
                    ("task.assignee_changed", "Task Assignee Changed"),
                    ("task.mentioned", "Task Mentioned"),
                    ("task.due_date_changed", "Task Due Date Changed"),
                ],
                max_length=30,
            ),
        ),
    ]
