# Generated by Django 5.2.14 on 2026-06-19 19:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0006_webhook_format_alter_webhook_events_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="events",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("task.created", "Task Created"),
                        ("task.updated", "Task Updated"),
                        ("task.deleted", "Task Deleted"),
                        ("dependency.created", "Dependency Created"),
                        ("dependency.deleted", "Dependency Deleted"),
                        ("schedule.recalculated", "Schedule Recalculated"),
                        ("project.created", "Project Created"),
                        ("task.assigned", "Task Assigned"),
                        ("task.assignee_changed", "Task Assignee Changed"),
                        ("task.mentioned", "Task Mentioned"),
                        ("task.due_date_changed", "Task Due Date Changed"),
                        ("sprint.activated", "Sprint Activated"),
                        ("sprint.closed", "Sprint Closed"),
                        ("sprint.scope_changed", "Sprint Scope Changed"),
                    ],
                    max_length=30,
                ),
                help_text="List of event types this webhook subscribes to.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("task.created", "Task Created"),
                    ("task.updated", "Task Updated"),
                    ("task.deleted", "Task Deleted"),
                    ("dependency.created", "Dependency Created"),
                    ("dependency.deleted", "Dependency Deleted"),
                    ("schedule.recalculated", "Schedule Recalculated"),
                    ("project.created", "Project Created"),
                    ("task.assigned", "Task Assigned"),
                    ("task.assignee_changed", "Task Assignee Changed"),
                    ("task.mentioned", "Task Mentioned"),
                    ("task.due_date_changed", "Task Due Date Changed"),
                    ("sprint.activated", "Sprint Activated"),
                    ("sprint.closed", "Sprint Closed"),
                    ("sprint.scope_changed", "Sprint Scope Changed"),
                ],
                max_length=30,
            ),
        ),
    ]
