# Generated by Django 5.2.16 on 2026-08-17 14:09
#
# Hand-ordered (#2885): the generated migration emitted RemoveField(secret) first,
# which would have dropped every signing secret in the install. The AddField must
# come first, the RunPython copies the plaintext into the new encrypted column
# while both exist, and only then is the plaintext column dropped. The data step
# lives in webhooks/backfill.py so a test can exercise it without importing this
# module by name (CLAUDE.md migration rule 3).

from django.db import migrations, models

from trueppm_api.apps.webhooks.backfill import (
    encrypt_webhook_secrets,
    reverse_encrypt_webhook_secrets,
)


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0008_risk_baseline_comment_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="secret_ciphertext",
            field=models.BinaryField(blank=True, default=b""),
        ),
        # elidable: safe for the optimizer to drop IF this migration's originals
        # ship and run in a released version before the squash that replaces them
        # is generated — a squash only guarantees an empty table for ops whose
        # originals already applied in an earlier release (#4320 correction; see
        # CLAUDE.md migration-discipline rule 1/6 and access/migrations/
        # 0017_viewer_ordinal_one.py for the upgrade-path counterexample this was
        # wrong about). As of this writing 0009 is UNRELEASED, so that condition
        # does not yet hold: whichever 0.x squash first spans this migration will
        # run it directly against populated tables on upgrade, exactly like the
        # access squash did. Re-check this comment, and verify with a test in the
        # shape of tests/apps/access/test_viewer_ordinal_upgrade.py, before that
        # squash is generated — do not assume elision is still safe by then.
        # Leaving it non-elidable would make squashmigrations keep it as an
        # optimizer barrier, pinning the add-copy-drop dance for a column no model
        # has — plus a hard import of webhooks.backfill — into the baseline.
        migrations.RunPython(
            encrypt_webhook_secrets,
            reverse_encrypt_webhook_secrets,
            elidable=True,
        ),
        # State-only, and a no-op forward: `blank`/`default` are not DDL in Django.
        # It exists for the REVERSE direction. RemoveField's backwards pass re-adds
        # the field from the previous state, where `secret` was CharField(max_length=255)
        # with no default and blank=False — so Django emits a bare
        # `ADD COLUMN "secret" varchar(255) NOT NULL`, which PostgreSQL rejects on any
        # table with rows ("contains null values"). That aborts the reverse *before*
        # reverse_encrypt_webhook_secrets can put the plaintext back, on exactly the
        # databases that have webhooks. Declaring blank/default here makes the
        # re-added column carry `DEFAULT ''`. (Passing `field=` to RemoveField would
        # not work: its database_backwards reads the field off to_state.)
        migrations.AlterField(
            model_name="webhook",
            name="secret",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="secret",
        ),
        migrations.AddField(
            model_name="webhook",
            name="consecutive_failures",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Terminal delivery failures since the last success. Resets to 0 on any successful delivery.",
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="disabled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the automatic failure guard deactivated this subscription. Null when it is active, or when an admin deactivated it by hand.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="disabled_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="webhook",
            name="last_failure_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webhook",
            name="last_failure_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
