//! Conformance tests that load shared JSON fixtures and verify the Rust CPM
//! engine produces identical output to the expected results (generated by the
//! Python engine, the source of record).
//!
//! The suite iterates the fixtures directory directly (#1505): every
//! `fixtures/*.json` is exercised automatically, so a new fixture added on the
//! Python side can never be silently ignored by Rust. A missing `expected/`
//! snapshot is a hard `panic!` (#1506) — it must never warn-and-pass.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use trueppm_wasm_scheduler::models::Project;
use trueppm_wasm_scheduler::{incremental_update, schedule_impl};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures")
}

/// Fixtures whose Rust output is a known, tracked divergence from the Python
/// engine. Each entry pins the fixture to its follow-up issue; the fixture stays
/// committed (and its `expected/` snapshot generated from Python) so the gap is
/// visible and cannot regress further, but the cross-engine comparison is skipped
/// until the Rust engine is fixed. Empty in the normal case — a divergence must
/// be a deliberate, reviewed entry here, never a silently-loosened assertion.
const KNOWN_DIVERGENT: &[(&str, &str)] = &[
    // ("fixture_stem", "#NNNN"),
];

/// Every top-level `*.json` under `fixtures/` (excludes the `expected/`,
/// `invalid/`, and `rust_rejects/` subdirectories — `read_dir` yields those as
/// directories, which have no `.json` extension).
fn valid_fixture_stems() -> Vec<String> {
    let mut stems: Vec<String> = fs::read_dir(fixtures_dir())
        .expect("fixtures/ directory must exist")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("json"))
        .filter_map(|p| p.file_stem().and_then(|s| s.to_str()).map(String::from))
        .collect();
    stems.sort();
    stems
}

fn load_project(fixture_name: &str) -> Project {
    let input_path = fixtures_dir().join(format!("{fixture_name}.json"));
    let input_json = fs::read_to_string(&input_path)
        .unwrap_or_else(|_| panic!("Failed to read fixture: {}", input_path.display()));
    serde_json::from_str(&input_json)
        .unwrap_or_else(|e| panic!("{fixture_name}: fixture should parse, got {e}"))
}

fn load_and_check(fixture_name: &str) {
    let expected_path = fixtures_dir()
        .join("expected")
        .join(format!("{fixture_name}.json"));

    let project = load_project(fixture_name);
    let result = schedule_impl(&project).unwrap();
    let result_json = serde_json::to_value(&result).unwrap();

    // #1506: a missing expected snapshot is a hard failure, never a warn-and-pass.
    // Regenerate committed snapshots from the Python engine with
    //   REGEN_EXPECTED=1 pytest packages/scheduler/tests/test_wasm_conformance.py
    // and commit the expected/ output.
    assert!(
        expected_path.exists(),
        "{fixture_name}: missing expected snapshot {}. A new fixture must not warn-and-pass \
         the conformance suite (#1506). Regenerate it from the Python engine with \
         `REGEN_EXPECTED=1 pytest packages/scheduler/tests/test_wasm_conformance.py` \
         and commit packages/wasm-scheduler/fixtures/expected/.",
        expected_path.display()
    );

    let expected_json_str = fs::read_to_string(&expected_path).unwrap();
    let expected: serde_json::Value = serde_json::from_str(&expected_json_str).unwrap();

    assert_eq!(
        result_json["project_id"], expected["project_id"],
        "{fixture_name}: project_id mismatch"
    );
    assert_eq!(
        result_json["project_start"], expected["project_start"],
        "{fixture_name}: project_start mismatch"
    );
    assert_eq!(
        result_json["project_finish"], expected["project_finish"],
        "{fixture_name}: project_finish mismatch"
    );
    assert_eq!(
        result_json["critical_path"], expected["critical_path"],
        "{fixture_name}: critical_path mismatch"
    );
    // Driving-edge parity (#2095): both engines must agree on which links have
    // zero relationship free float, in the same deterministic order. `.get(...)`
    // with an empty-array default mirrors the Python conformance assertion.
    let expected_driving = expected
        .get("driving_edges")
        .cloned()
        .unwrap_or_else(|| serde_json::json!([]));
    assert_eq!(
        result_json["driving_edges"], expected_driving,
        "{fixture_name}: driving_edges mismatch"
    );

    let result_tasks = result_json["tasks"].as_array().unwrap();
    let expected_tasks = expected["tasks"].as_array().unwrap();
    assert_eq!(
        result_tasks.len(),
        expected_tasks.len(),
        "{fixture_name}: task count mismatch"
    );

    // Build a lookup by task ID so order differences don't matter.
    let expected_by_id: HashMap<&str, &serde_json::Value> = expected_tasks
        .iter()
        .map(|t| (t["id"].as_str().unwrap(), t))
        .collect();

    for rt in result_tasks {
        let task_id = rt["id"].as_str().unwrap();
        let et = expected_by_id
            .get(task_id)
            .unwrap_or_else(|| panic!("{fixture_name}: unexpected task {task_id}"));
        assert_eq!(
            rt["early_start"], et["early_start"],
            "{fixture_name}/{task_id}: early_start mismatch"
        );
        assert_eq!(
            rt["early_finish"], et["early_finish"],
            "{fixture_name}/{task_id}: early_finish mismatch"
        );
        assert_eq!(
            rt["late_start"], et["late_start"],
            "{fixture_name}/{task_id}: late_start mismatch"
        );
        assert_eq!(
            rt["late_finish"], et["late_finish"],
            "{fixture_name}/{task_id}: late_finish mismatch"
        );
        // Assert the float math too (#774). Without these, the hand-ported
        // Rust float computation in src/floats.rs could diverge from Python
        // while ES/EF/LS/LF still matched, going undetected.
        assert_eq!(
            rt["total_float"], et["total_float"],
            "{fixture_name}/{task_id}: total_float mismatch"
        );
        assert_eq!(
            rt["free_float"], et["free_float"],
            "{fixture_name}/{task_id}: free_float mismatch"
        );
        assert_eq!(
            rt["is_critical"], et["is_critical"],
            "{fixture_name}/{task_id}: is_critical mismatch"
        );
    }
}

/// Cross-engine conformance for every fixture (#1505). Iterating the directory
/// (rather than a static list of `#[test]` functions) means a fixture added on
/// the Python side is automatically checked here — closing the "new fixture
/// silently ignored by Rust" gap the audit flagged.
#[test]
fn conformance_all_fixtures() {
    let stems = valid_fixture_stems();
    assert!(
        !stems.is_empty(),
        "no fixtures found in {} — path break? (#1506)",
        fixtures_dir().display()
    );

    let mut checked = 0;
    for stem in &stems {
        if let Some((_, issue)) = KNOWN_DIVERGENT.iter().find(|(n, _)| n == stem) {
            eprintln!("SKIP known-divergent fixture {stem} (tracked in {issue})");
            continue;
        }
        load_and_check(stem);
        checked += 1;
    }
    assert!(checked > 0, "every fixture is on the divergence allowlist?");
}

/// Property test (#1505): for every fixture and every possible drag target, the
/// downstream-only result of `incremental_update` must equal the corresponding
/// tasks from a fresh full `schedule_impl`. `incremental_update` runs the full
/// CPM internally and returns only downstream tasks, so a divergence here means
/// the incremental drag-preview path (the browser/offline recompute) disagrees
/// with a full recompute — the exact silent-drift risk `wasm_incremental_update`
/// had zero coverage for. Each iteration perturbs the changed task's duration
/// (a schedule-shifting change) and checks the property still holds.
#[test]
fn incremental_matches_full_recompute() {
    for stem in valid_fixture_stems() {
        let base = load_project(&stem);
        let changed_ids: Vec<String> = base.tasks.iter().map(|t| t.id.clone()).collect();

        for changed in &changed_ids {
            let mut project = base.clone();
            for t in project.tasks.iter_mut() {
                if &t.id == changed {
                    // Perturb: shift this task by two working days so the
                    // schedule genuinely shifts downstream. Extend normally,
                    // but shrink when extending would cross MAX_DURATION_DAYS
                    // (mirrors validate::MAX_DURATION_DAYS = 36,525) — the
                    // #1855 boundary fixture sits exactly at the cap, where a
                    // +2d perturbation is validator-rejected, not
                    // schedule-shifting.
                    let two_days = 2.0 * 86_400.0;
                    if t.duration + two_days > 36_525.0 * 86_400.0 {
                        t.duration -= two_days;
                    } else {
                        t.duration += two_days;
                    }
                }
            }

            let full = schedule_impl(&project)
                .unwrap_or_else(|e| panic!("{stem}: full schedule failed after perturbation: {e}"));
            let incr = incremental_update(&project, changed)
                .unwrap_or_else(|e| panic!("{stem}: incremental_update({changed}) failed: {e}"));

            // Whole-project aggregates are computed over the full task map inside
            // incremental_update, so they must match the full recompute exactly.
            assert_eq!(
                incr.project_start, full.project_start,
                "{stem}/{changed}: incremental project_start diverged"
            );
            assert_eq!(
                incr.project_finish, full.project_finish,
                "{stem}/{changed}: incremental project_finish diverged"
            );
            assert_eq!(
                incr.critical_path, full.critical_path,
                "{stem}/{changed}: incremental critical_path diverged"
            );

            let full_by_id: HashMap<&str, &_> =
                full.tasks.iter().map(|t| (t.id.as_str(), t)).collect();
            for it in &incr.tasks {
                let ft = full_by_id.get(it.id.as_str()).unwrap_or_else(|| {
                    panic!(
                        "{stem}/{changed}: incremental task {} not in full recompute",
                        it.id
                    )
                });
                assert_eq!(
                    it.early_start, ft.early_start,
                    "{stem}/{changed}/{}: early_start",
                    it.id
                );
                assert_eq!(
                    it.early_finish, ft.early_finish,
                    "{stem}/{changed}/{}: early_finish",
                    it.id
                );
                assert_eq!(
                    it.late_start, ft.late_start,
                    "{stem}/{changed}/{}: late_start",
                    it.id
                );
                assert_eq!(
                    it.late_finish, ft.late_finish,
                    "{stem}/{changed}/{}: late_finish",
                    it.id
                );
                assert_eq!(
                    it.total_float, ft.total_float,
                    "{stem}/{changed}/{}: total_float",
                    it.id
                );
                assert_eq!(
                    it.free_float, ft.free_float,
                    "{stem}/{changed}/{}: free_float",
                    it.id
                );
                assert_eq!(
                    it.is_critical, ft.is_critical,
                    "{stem}/{changed}/{}: is_critical",
                    it.id
                );
            }
        }
    }
}
