//! The Rust engine held to an independent reference CPM, not to the Python engine
//! (#3987).
//!
//! `tests/conformance.rs` compares Rust against snapshots generated by the Python
//! engine, which proves the two agree, not that either is right.
//! `fixtures/oracle/corpus.json` is generated by
//! `packages/scheduler/tests/oracle/reference_cpm.py` — a slow reference written
//! from the documented CPM math that imports neither engine — over a seeded set of
//! random networks (all four link types, leads and lags, random working-day masks
//! and calendar exceptions, milestones). The Python side
//! (`tests/test_cpm_oracle.py`) asserts the corpus still matches the reference and
//! holds the Python engine to it too.
//!
//! Each expected row carries only the fields the reference states: for a task with
//! work, its early dates always, and its late dates and floats unless they depend
//! on which edge of its day a milestone is shown on; for a milestone, the two
//! shown readings of its working-time position, either of which is accepted.

use std::fs;
use std::path::PathBuf;

use serde_json::Value;
use trueppm_wasm_scheduler::models::Project;
use trueppm_wasm_scheduler::schedule_impl;

const SECONDS_PER_DAY: f64 = 86_400.0;

fn corpus() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures")
        .join("oracle")
        .join("corpus.json");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("oracle corpus must exist at {}: {e}", path.display()));
    serde_json::from_str(&text).expect("oracle corpus must be valid JSON")
}

/// Every mismatch between one engine task row and the reference's expected row.
fn row_mismatches(expected: &Value, got: &Value) -> Vec<String> {
    if let Some(readings) = expected.get("milestone_shown") {
        let shown = serde_json::json!([
            got["early_start"],
            got.get("milestone_at_day_end")
                .cloned()
                .unwrap_or(Value::Bool(false)),
        ]);
        let ok = readings.as_array().unwrap().contains(&shown);
        return if ok {
            vec![]
        } else {
            vec![format!(
                "milestone shown {shown}, reference accepts {readings}"
            )]
        };
    }
    let mut out = vec![];
    for (key, want) in expected.as_object().unwrap() {
        let have = match key.as_str() {
            "total_float_days" => {
                Value::from(got["total_float"].as_f64().unwrap() / SECONDS_PER_DAY)
            }
            "free_float_days" => Value::from(got["free_float"].as_f64().unwrap() / SECONDS_PER_DAY),
            other => got[other].clone(),
        };
        let same = match (have.as_f64(), want.as_f64()) {
            (Some(h), Some(w)) => h == w,
            _ => have == *want,
        };
        if !same {
            out.push(format!("{key} {have} != reference {want}"));
        }
    }
    out
}

#[test]
fn rust_engine_matches_the_reference_corpus() {
    let corpus = corpus();
    let cases = corpus["cases"].as_array().expect("corpus must carry cases");
    // A corpus that silently emptied would pass every assertion below (#1506).
    assert!(
        cases.len() >= 100,
        "oracle corpus shrank to {} cases",
        cases.len()
    );

    let mut problems = vec![];
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let project: Project = serde_json::from_value(case["project"].clone())
            .unwrap_or_else(|e| panic!("{name}: project should parse, got {e}"));
        let result = schedule_impl(&project).unwrap_or_else(|e| panic!("{name}: {e}"));
        let result = serde_json::to_value(&result).unwrap();
        let expected = case["expected"].as_object().unwrap();
        let tasks = result["tasks"].as_array().unwrap();
        assert_eq!(tasks.len(), expected.len(), "{name}: task count");
        for task in tasks {
            let id = task["id"].as_str().unwrap();
            let want = expected
                .get(id)
                .unwrap_or_else(|| panic!("{name}: unexpected task {id}"));
            for p in row_mismatches(want, task) {
                problems.push(format!("{name}/{id}: {p}"));
            }
        }
    }
    assert!(problems.is_empty(), "{}", problems.join("\n"));
}
