# Generated by Django 6.0.3 on 2026-05-24 10:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("sleeping", "Sleeping"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("input", models.JSONField(default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("idempotency_key", models.CharField(max_length=64)),
                ("cancel_reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="workflow_status_idx"),
                    models.Index(fields=["completed_at"], name="workflow_completed_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("idempotency_key",), name="workflow_idempotency_key_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowHistoryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("seq", models.BigIntegerField()),
                ("event_type", models.CharField(max_length=32)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow_id", "seq"],
                "indexes": [
                    models.Index(fields=["workflow", "seq"], name="workflow_history_lookup_idx"),
                    models.Index(fields=["created_at"], name="workflow_history_retention_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workflow", "seq"), name="workflow_history_seq_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowActivityExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("activity_name", models.CharField(max_length=255)),
                ("input_hash", models.CharField(max_length=64)),
                ("result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_executions",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workflow", "activity_name", "input_hash"),
                        name="workflow_activity_oaoo_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowOutboxRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("step_name", models.CharField(max_length=255)),
                ("step_input", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("done", "Done"),
                            ("dead", "Dead"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_rows",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="workflow_outbox_drain_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("signal_name", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("consumed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow", "consumed", "created_at"],
                        name="workflow_signal_inbox_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTimer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fire_at", models.DateTimeField()),
                ("fired", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timers",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["fired", "fire_at"], name="workflow_timer_due_idx")
                ],
            },
        ),
    ]
